### ISSUE TITLE
PHP fatal error in tags.php?display_mode=letters

### ISSUE THREAD

**Issue by boge90** [Piwigo/Piwigo#1001]
After upgrading to Piwigo 2.9.5,

the tag page crashes when selecting "Group by letters", however the tag-cloud works fine.

How to reproduce:
 - Click on tags
 - Click on "Group by letters" in the upper right corner

Fatal error: Uncaught Error: Call to undefined function mb_strtoupper() in /var/www/html/tags.php:104 Stack trace: #0 {main} thrown in /var/www/html/tags.php on line 104

**Comment by flop25** [comment]
Hello
You probably don't have mb_string module for php. And you probably have
more errors due to that

Le jeu. 11 avr. 2019 à 07:35, Øivind Boge <notifications@github.com> a
écrit :

**Comment by boge90** [comment]
That was the problem, thank you!

fix:
sudo apt-get install php-mbstring
sudo service apache2 restart
