### ISSUE TITLE
Fatal error when manually ordering categories

### ISSUE THREAD

**Issue by philigrane** [Piwigo/Piwigo#1005]
I have this error when manually ordering categories in "...admin.php?page=cat_list" : 
`Fatal error: Uncaught Error: Call to undefined function save_categories_order() in .../admin/cat_list.php:196 Stack trace: #0 .../admin.php(312): include() #1 {main} thrown in .../admin/cat_list.php on line 196`
The function save_categories_order() don't exist en piwigo (functions.php).
It seems possible to rely on this function in 644 "update_global_rank" to create it.
Phil

**Comment by plegall** [comment]
Hi @philigrane 

You're running Piwigo master I suppose. I have function `save_categories_order` in ./admin/include/functions.php, don't you?

I just tested the "save manual order" button and it worked fine.

**Comment by philigrane** [comment]
It's OK! Thank you so much. I did not realize it. Sorry
Phil

**Comment by plegall** [comment]
Sorry but, what didn't you realize? Does it work now? What did you change?

**Comment by philigrane** [comment]
Yes it works now I replaced my function file by the one of the deposit
