### ISSUE TITLE
new design for upload form

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#1019]
based on Samuel's mockup
![20180827173046-21ed338a-xl](https://user-images.githubusercontent.com/9326959/58097963-dc425d80-7bd8-11e9-84a8-498c77c0bc42.png)
![20180827173046-93358226-xl](https://user-images.githubusercontent.com/9326959/58097964-dc425d80-7bd8-11e9-860e-84589bc07ebe.png)

**Comment by klaoun** [comment]
Bonjour, quand j'ai installé les correctifs #1019 m'affiche ceci et quand je souhaite cliquer sur "Outils" en haut ca ne prend plus les valeurs
![notoutils](https://user-images.githubusercontent.com/36087587/58251323-a4b3ec80-7d63-11e9-8e8e-66b98c83e64c.png)
