### ISSUE TITLE
cannot download installer package

### ISSUE THREAD

**Issue by fishingsun** [Piwigo/Piwigo#1024]
When clicking download button on piwigo.org, it keeps returning 403 Forbidden. Can somebody fix the download link?

**Comment by J0celyn** [comment]
The "Download Piwigo 2.9.5" link on https://piwigo.org/get-piwigo is working for me.
Are you still having issues?

**Comment by fishingsun** [comment]
> The "Download Piwigo 2.9.5" link on https://piwigo.org/get-piwigo is working for me.
> Are you still having issues?

**Comment by fishingsun** [comment]
@J0celyn The page of the link you pasted above can be opened of course. But the button "Download Piwigo 2.9.5" and "NetInstall" in the page doesn't work. Try to click it, you will see.

Or, you can just try to click this: https://piwigo.org/download/dlcounter.php?code=latest
See what will happen.

**Comment by J0celyn** [comment]
The link you posted in your last message is the link to the page displaying the "Download Piwigo 2.9.5" button I was referring to in my previous message.
This link (and netinstall link) both trigger a download. Both links work fine for me.
Did you try with a different browser or different device?

**Comment by fishingsun** [comment]
the source ip from china is blocked. i used a vpn to change my source ip, then download links work well.
