### ISSUE TITLE
zh lang problem,an EIGHT yesrs old bug.

### ISSUE THREAD

**Issue by edouardlicn** [Piwigo/Piwigo#1028]
https://cn.piwigo.org/forum/viewtopic.php?pid=112239#p112239

See above,about 8 years ago I use piwigo and found a bug,while I install zh_tw or zh_hk,if I set default language zh_cn it wont work,the language will be zh_tw or zh_hk.AFTER 8 YEARS I
'm back and the bug still be there.Any one can check it?

Priviosly I found it store the setting in db so after the zh_tw or zh_hk installed it will change the default lang setting.I don't know if it still be there.

**Comment by EddyLB** [comment]
@Piwigo-TranslationTeam , @plegall , would it be possible to finally fix that bug?

**Comment by plegall** [comment]
fixed thanks to #1132
