### ISSUE TITLE
[web API] Tag Groups compatibility

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo#1043]
The methods pwg.tags.getAdminList and pwg.tags.getList do not return the 'group' to which the tag belongs to, which makes impossible to present tags in groups on third party apps. Could you please add the group name in the list of returned data?

**Comment by plegall** [comment]
Hi @EddyLB 

This is more a Tag Groups issue : https://github.com/plegall/piwigo-tag_groups Can you recreate your issue there please :-)

(Piwigo core has no clue what a "group" is for tags)

**Comment by EddyLB** [comment]
Ok @plegall . Done
https://github.com/plegall/piwigo-tag_groups/issues/5
