### ISSUE TITLE
2.10.0b2 "Fatal error: Uncaught --> Smarty" after OK install

### ISSUE THREAD

**Issue by pgnd** [Piwigo/Piwigo#1046]
installing piwigo 2.10.0b2 from current git/head
```
cd /srv/www/test/piwigo
git log | head
	commit b1018694176585a0e3a3dd7fd6a14c7a68998a7b
	Author: plegall <plg@piwigo.org>
	Date:   Thu Jul 4 11:22:09 2019 +0200

	    update release to 2.10.0beta2

	commit c1eecab36415bcba022aa088463ed138fc38b92b
	Author: plegall <plg@piwigo.org>
	Date:   Fri Jun 28 18:07:53 2019 +0200
```
on nginx/linux + phpfpm, on exec of 'install' @ UI, I get:

> "Congratulations. Piwigo installation is completed"

but, on click to "Visit Gallery"

I get in my phpfpm log,
```
Notice: Undefined offset: 0 in /srv/www/test/piwigo/include/functions_user.inc.php on line 780
  
Fatal error: Uncaught --> Smarty: Unable to load template file 'no_photo_yet.tpl' <-- thrown in /srv/www/test/piwigo/include/smarty/libs/sysplugins/smarty_internal_template.php on line 139
```

Checking, the file _exists_
```
find . -name no_photo_yet.tpl
  ./themes/default/template/no_photo_yet.tpl
```

**Comment by pgnd** [comment]
fyi, dropback to release 2.9.5/release _does_ 'remove' the error^^ ...

**Comment by 1601085296710192** [comment]
> installing piwigo 2.10.0b2 from current git/head
> 
> ```
> cd /srv/www/test/piwigo
> git log | head
> 	commit b1018694176585a0e3a3dd7fd6a14c7a68998a7b
> 	Author: plegall <plg@piwigo.org>
> 	Date:   Thu Jul 4 11:22:09 2019 +0200
> 
> 	    update release to 2.10.0beta2
> 
> 	commit c1eecab36415bcba022aa088463ed138fc38b92b
> 	Author: plegall <plg@piwigo.org>
> 	Date:   Fri Jun 28 18:07:53 2019 +0200
> ```
> 
> on nginx/linux + phpfpm, on exec of 'install' @ UI, I get:
> 
> > "Congratulations. Piwigo installation is completed"
> 
> but, on click to "Visit Gallery"
> 
> I get in my phpfpm log,
> 
> ```
> Notice: Undefined offset: 0 in /srv/www/test/piwigo/include/functions_user.inc.php on line 780
>   
> Fatal error: Uncaught --> Smarty: Unable to load template file 'no_photo_yet.tpl' <-- thrown in /srv/www/test/piwigo/include/smarty/libs/sysplugins/smarty_internal_template.php on line 139
> ```
> 
> Checking, the file _exists_
> 
> ```
> find . -name no_photo_yet.tpl
>   ./themes/default/template/no_photo_yet.tpl
> ```

**Comment by PurpleBabar** [comment]
The smarty error seems to be triggered when using php 7 for me :/
