### ISSUE TITLE
2.10.0RC1: Error when opening Comments using Bootstrap Darkroom theme

### ISSUE THREAD

**Issue by jheinitz** [Piwigo/Piwigo#1067]
Hello,

I face an issue with the Piwigo 2.10.0RC1 and the Bootstrap Darkroom theme. When I navigate to Explore --> Comments, I get this error:

Piwigo ist auf einen nicht behebbaren Fehler gestoßen.
define_derivative missing width

#1	Template::func_define_derivative /var/www/_data/templates_c/b79f2g^5b2e5f7dae656e1fcfb24c416c8627acfe7f05e7_0.file.comment_list.tpl.php(56)
#2	content_5d5e9ef6aa2502_98294916 /var/www/include/smarty/libs/sysplugins/smarty_template_resource_base.php(122)
#3	Smarty_Template_Resource_Base::getRenderedTemplateCode /var/www/include/smarty/libs/sysplugins/smarty_template_compiled.php(199)
#4	Smarty_Template_Compiled::render /var/www/include/smarty/libs/sysplugins/smarty_internal_template.php(159)
#5	Smarty_Internal_Template::render /var/www/include/smarty/libs/sysplugins/smarty_internal_runtime_subtemplate.php(174)
#6	Smarty_Internal_Runtime_SubTemplate::render /var/www/_data/templates_c/b79f2g^93572b79d12c105d6ee734d69e03217a5637737f_0.file.comments.tpl.php(146)
#7	content_5d5e9ef6ac14b1_54702624 /var/www/include/smarty/libs/sysplugins/smarty_template_resource_base.php(122)
#8	Smarty_Template_Resource_Base::getRenderedTemplateCode /var/www/include/smarty/libs/sysplugins/smarty_template_compiled.php(199)
#9	Smarty_Template_Compiled::render /var/www/include/smarty/libs/sysplugins/smarty_internal_template.php(159)
#10	Smarty_Internal_Template::render /var/www/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(191)
#11	Smarty_Internal_TemplateBase::_execute /var/www/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(94)
#12	Smarty_Internal_TemplateBase::fetch /var/www/include/template.class.php(469)
#13	Template::parse /var/www/include/template.class.php(489)
#14	Template::pparse /var/www/comments.php(545)

Do you have an idea? It works fine with 2.9.5. On the other hand 2.10.0RC1 works fine with the "modus" theme.

Kind regards

Jens
PS: I have created a detailed "How to reproduce" which I can share.

**Versions:**
Piwigo 2.10.0RC1
Betriebssystem: Linux
PHP: 7.0.33-0+deb9u3 (Info anzeigen) [2019-08-22 16:04:59]
MySQL: 5.5.5-10.4.7-MariaDB-1:10.4.7+maria~bionic [2019-08-22 16:04:59]
Grafikbibliothek: ImageMagick 6.9.7-4

**Comment by plegall** [comment]
I close this issue. It will be managed in Bootstrap Darkroom issue tracker.
