### ISSUE TITLE
Promote iOS app with smart app banner

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo#1069]
Could you please add `<meta name="apple-itunes-app" content="app-id=472225196">` to the header of the welcome page of Piwigo so that iOS users are invited to use the mobile app (see [Apple documentation](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html))?

Here is for example what would be presented in Safari:
![IMG_2428E5964742-1](https://user-images.githubusercontent.com/7103032/64078074-cca5db00-ccd6-11e9-90bd-251a5b0022fc.jpeg)

**Comment by samwilson** [comment]
I think this sounds like it'd be more appropriate for a plugin than core. Personally, I wouldn't want such a banner appearing on my website, but I can see how it'd be really useful for some projects.

**Comment by EddyLB** [comment]
A smart app banner automatically determines whether the app is supported on the user’s device. If the device loading the banner does not support the iOS app, or if the app is not available in the user's location, the banner will not display. It also not reappears if it has been shown when returning to the home page.

So I believe that it should be coded in the core, unless Piwigo does not wish to promote the mobile app.

**Comment by samwilson** [comment]
I understand that it'd only be shown to iOS users of the right version etc., but it'd still show on my own site and I wouldn't be able to turn it off. I don't want to suggest to users of my site that they should install an app — there's just no need. For *contributors* to a site, it makes a lot more sense, or sites that are eliciting user photos, but generally I don't think normal read-only websites need apps.

If not a separate plugin, then this would at least need a configuration option so it could be turned off.

(Of course, this is just my personal opinion, and I'm just a user of Piwigo!)

**Comment by plegall** [comment]
Right now, I think it could be a good idea, but not in the gallery but in the admin. I still see the app mainly as an admin tool, not a visitor tool. I'm going to think about it.

@samwilson wrote:

> I don't want to suggest to users of my site that they should
> install an app — there's just no need

and I perfectly agree with that. Or else, there would be no point in working on responsive themes.

**Comment by samwilson** [comment]
Oh yes, if it was just in the admin area that'd be fine; good idea.

**Comment by plegall** [comment]
We could have a configuration setting, such as:

> Promote mobile app on mobile devices
> [] in gallery [x] in administration

**Comment by EddyLB** [comment]
Ok for a configuration setting.

**Comment by EddyLB** [comment]
When will it be implemented?

**Comment by plegall** [comment]
I hope you'll like the implementation :-)
![Screen Shot 2020-09-29 at 15 13 19](https://user-images.githubusercontent.com/9326959/94563029-69ce9c80-0266-11eb-861d-287083d42df1.png)
