### ISSUE TITLE
[mysql error 1064] You have an error in your SQL syntax

### ISSUE THREAD

**Issue by eallion** [Piwigo/Piwigo#1081]
[mysql error 1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 16

```
SELECT
    c.*,
    user_representative_picture_id,
    nb_images,
    date_last,
    max_date_last,
    count_images,
    nb_categories,
    count_categories
  FROM piwigo_categories c
    INNER JOIN piwigo_user_cache_categories ucc
    ON id = cat_id
    AND user_id = 1
  WHERE id_uppercat is NULL
      
  ORDER BY rank
```

#1	my_error /.../include/dblayer/functions_mysqli.inc.php(132)
#2	pwg_query /.../include/category_cats.inc.php(55)
#3	include /.../index.php(301)

> Piwigo:2.10.0RC1
> Ubuntu:18.04
> Nginx:1.16.1
> PHP:7.3.10
> Mysql:8.0.17

**Comment by plegall** [comment]
Piwigo 2.10.0 fixes this problem. `rank` has become a reserved keyword with MySQL 8.
