### ISSUE TITLE
' category_cats.inc.php on line 315 ' displayed on all pages after update to 2.10

### ISSUE THREAD

**Issue by dkm** [Piwigo/Piwigo#1087]
After an update to 2.10 this morning, I've this message displayed on all pages, sometimes several times at the top. I've found an old BR (https://piwigo.org/bugs/view.php?id=2917 ) dealing with user cache, so I've tried to purge the user cache, without any effect on this issue.
I'v also tried to disable all plugins (still, no luck).

Here are some info:
```
    Piwigo 2.10.0 Check for upgrade
    Operating system: Linux
    PHP: 7.0.33-0+deb9u5 (Show info) [2019-10-09 13:52:43]
    MySQL: 5.5.5-10.1.41-MariaDB-0+deb9u1 [2019-10-09 13:52:43]
    Graphics Library: GD 2.2.4
```

**Comment by plegall** [comment]
Hi @dkm 

Can you go on [Administration > Tools > Maintenance] and perform actions "Update albums' information" + "Update photos' information" ?

**Comment by dkm** [comment]
Hi ! I already tried that this morning... I've just tried it again, to be sure, but nothing has changed.

**Comment by plegall** [comment]
Can you send me a private email with your database dump? I'm "plg" on domain name "piwigo.org" :-)

**Comment by dkm** [comment]
Done :)

**Comment by dkm** [comment]
FWIW, latest update does not fix this issue.

**Comment by dkm** [comment]
This is even more problematic than I thought, as it seems that it also breaks API use (I'm using shotwell to upload to my gallery). Any luck on finding what is causing this ? I'll try to debug this, but my php skills are really rusty.

**Comment by dkm** [comment]
Could this be related ? It's in the error log of my web server after I've tried to upload image from the admin page... The upload seems to be going fine until all files are uploaded and the progress bar is stuck at 100%.

```
2019/10/21 19:46:06 [error] 836#836: *1078 FastCGI sent in stderr: "PHP message: PHP Warning:  [mysql error 1146] Table '<DATABASE>.piwigo_activity' doesn't exist

INSERT  INTO `piwigo_activity`
  (`object`,`object_id`,`action`,`performed_by`,`session_idx`,`ip_address`,`details`)
  VALUES('photo','3557','add','1','9out82n5ebtnshtlhd4kv2i0r3','<SOME_IP>','a:3:{s:6:\"method\";s:17:\"pwg.images.upload\";s:10:\"added_with\";s:7:\"browser\";s:5:\"agent\";s:68:\"Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0\";}') in <LOCAL_PATH>/piwigo/include/dblayer/functions_mysqli.inc.php on line 856" while reading response header from upstream, client: <SOME_IP>, server: <HOSTNAME>, request: "POST /ws.php?method=pwg.images.upload&format=json HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "<HOSTNAME>", referrer: "http://<HOSTNAME>/admin.php?page=photos_add"
```

**Comment by dkm** [comment]
Ok, after issuing the following SQL statement:
```
MariaDB [<DATABASE>]> CREATE TABLE `piwigo_activity` (
    ->   `activity_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    ->   `object` varchar(255) NOT NULL,
    ->   `object_id` int(11) unsigned NOT NULL,
    ->   `action` varchar(255) NOT NULL,
    ->   `performed_by` mediumint(8) unsigned NOT NULL,
    ->   `session_idx` varchar(255) NOT NULL,
    ->   `ip_address` varchar(50) DEFAULT NULL,
    ->   `occured_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ->   `details` varchar(255) DEFAULT NULL,
    ->   PRIMARY KEY (`activity_id`)
    -> ) ENGINE=MyISAM;
```

After that, I can nearly add photo from the web interface: everything seems ok (sucessful message, thumbnails, correct number of pictures being added). But when browsing the album, I have the following message : 
```
 Notice: Undefined index: display_fromto in <PATH>/piwigo/include/category_cats.inc.php on line 119
```

The more I look at this, the more I think the upgrade did not correctly update my database...

**Comment by dkm** [comment]
Ok, so I've restarted the upgrade process and everything is working now.
Something did not work as expected when upgrading from the webinterface...

I'll close this issue and let you decide if a new one is needed for tracking the possible upgrade problem...
