### ISSUE TITLE
Thanks for killing it completely

### ISSUE THREAD

**Issue by pstimpel** [Piwigo/Piwigo#1115]
Man, thanks for the work on the update. However, I would like to express how annoying it is to lose a complete installation. I would appreciate a bit of more warning in such "YOU MUST UPDATE OR WE ARE GOING TO DIE" emails. 

Finally, you tell me AFTER the update that you killed 90% of the plugins, probably due incompatibility. Man, I would have liked it to decide on my own if I want to update now where most of the plugins do not work anymore.

Writing software means not only writing cool code and nifty features, it means as well thinking about the responsibility. 

Best Regards
Peter

**Comment by plegall** [comment]
I'm sorry for your bad experience. You don't give much details and your post sound much more like a rant. Maybe the forum https://piwigo.org/forum would have been a better place for this discussion.

For now, I simply close this issue because I don't know how to "fix" it :-/

**Comment by pstimpel** [comment]
May I ask where exactly this was a rant? I really appreciate your efforts to provide Piwigo. I like it very much, wrote extensions for it, run my website for years using it.

Bit If you cannot handle simple requests for more usability on major updates, I guess you should ask someone else to maintain the software, or at least to run the issue tracker for you.

How to fix it? Hm, maybe a check for incompatible installed extensions would be cool, or a warning. But leaving the user alone after an update with a broken installation where he has to fix it himself on source code level is not my understanding of maintaining software and handling the responsibility that comes with it.

BR
Peter

**Comment by plegall** [comment]
OK Peter, please open a discussion on https://piwigo.org/forum because I don't want to discuss this matter on Github, this is not the appropriate place in my opinion.

**Comment by Nicksxs** [comment]
@plegall why the install script and doc site is all 403 forbidden

**Comment by flop25** [comment]
I've just checked and it is not

**Comment by Nicksxs** [comment]
@flop25 
![image](https://user-images.githubusercontent.com/7351669/78762720-d010eb80-79b6-11ea-8616-3f0578f4f958.png)

**Comment by flop25** [comment]
![image](https://user-images.githubusercontent.com/736909/78763035-f9b11f00-7984-11ea-9ce5-332097451a53.png)
so it comes from your side ...

**Comment by flop25** [comment]
please use another thread after checking on your side
