### ISSUE TITLE
List of "Related keywords" changed in Elegant theme

### ISSUE THREAD

**Issue by tomas-nz** [Piwigo/Piwigo#1116]
After upgrade from Piwigo 2.9 to 2.10.1 I noticed that list of Related keywords is showing _all_ keywords (in my case sometimes a very long list). In the past this included top keywords only. Strangely some albums still show the old format.

Example of new (IMO wrong) format: https://tomassobekphotography.co.nz/photos/
Example of old format (as of 6 Nov 2019 at least): https://tomassobekphotography.co.nz/photos/index.php?/category/189

Piwigo 2.10.1 
Operating system: Linux
PHP: 7.1.32 (Show info) [2019-11-06 07:19:26]
MySQL: 5.7.28-cll-lve [2019-11-06 20:19:26]
Graphics Library: External ImageMagick 6.7.8-9

**Comment by tomas-nz** [comment]
I found out that this is a new feature in Piwigo 2.10. I have posted a workaround how to revert it back to version 2.9 behaviour on forums, see https://piwigo.org/forum/viewtopic.php?pid=175185#p175185
Would it make sense to make this change in behaviour configurable? The new version 2.10 behaviour makes little sense for a large photo gallery with extensive use of keywords.

**Comment by jheinitz** [comment]
Hello Tomas,

I recognized this as well, but more due to the fact that the list of all tags is not sorted. I looked into your workaround and the solution is quite easy. There is already a way to configure this. I added this section to my local configuration file to achieve the expected behavior:

```
// menubar_tag_cloud_content: 'always_all', 'current_only' or 'all_or_current'
// For the tag cloud in the menubar.
// 'always_all': tag cloud always displays all tags available to the user
// 'current_only': tag cloud always displays the tags from the current pictures
// 'all_or_current': when pictures are displayed, tag cloud shows their tags, but
// when none are displayed, all the tags available to the user are shown.
$conf['menubar_tag_cloud_content'] = 'current_only';
```

Kind regards

Jens

**Comment by jheinitz** [comment]
By the way, the default for this option is 'all_or_current' and it is defined in 'include/config_default.inc.php'

Jens

**Comment by tomas-nz** [comment]
Thank you, Jens! It makes sense now - obviously I didn't compare the old and new code thoroughly enough. I found another reference to it here: https://github.com/Piwigo/Piwigo/issues/759
