### ISSUE TITLE
Error with datatable in users screen

### ISSUE THREAD

**Issue by sridharb1** [Piwigo/Piwigo#1123]
Unable to view/add users.

Please see attached.

I am using latest version.

![image](https://user-images.githubusercontent.com/13346687/69492221-8e7b1a80-0ec5-11ea-8179-0df12e8295e5.png)

**Comment by vensko** [comment]
`groups` is a [reserved word](https://dev.mysql.com/doc/refman/8.0/en/keywords.html) as of MySQL 8.0.2. To fix this, wrap `groups` with asterisks here https://github.com/Piwigo/Piwigo/blob/master/admin/user_list_backend.php#L204

**Comment by sridharb1** [comment]
Duplicate of #1095. Fixed by pull request #1117. Please integrate into master.
