### ISSUE TITLE
Need API for setting Album permissions and sort order

### ISSUE THREAD

**Issue by sridharb1** [Piwigo/Piwigo#1141]
Hi,

It would be nice to have an API to set album permissions and sort order. Currently, I am doing the same by calling .../admin.php?page=album-[ALBUM#]-permissions/sort-order, passing the required parameters and checking for a status of 200. This works fine, but an API would be best.

**Comment by tanty** [comment]
Sort order is already requested at #918

**Comment by sridharb1** [comment]
Duplicate of #918
