### ISSUE TITLE
Broken web upload form

### ISSUE THREAD

**Issue by mikoim** [Piwigo/Piwigo#1180]
I tried to upload photos from "Photos -> Add", but got the following error.

http://localhost/admin.php?page=photos_add

```
1vqtv4r.js:21 Uncaught TypeError: Cannot read property 'selectize' of undefined
    at m.fn.init.jQuery.fn.pwgAddAlbum (1vqtv4r.js:21)
    at admin.php?page=photos_add:256
jQuery.fn.pwgAddAlbum @ 1vqtv4r.js:21
(anonymous) @ admin.php?page=photos_add:256
```

------

* Google Chrome 81.0.4044.129 (Official Build) (64-bit)
* Piwigo 2.10.2

```
Environment
Piwigo 2.10.2
Operating system: Linux
PHP: 7.4.5 (Show info) [2020-05-03 12:52:13]
MySQL: 8.0.20 [2020-05-03 12:52:13]
Graphics Library: External ImageMagick 6.9.10-23
```

**Comment by quitchat** [comment]
I had exactly the same error today.
I fixed this issue by assign 777 permission to the "upload" folder.

**Comment by idreamerhx** [comment]
php-gd may not enabled (php.ini   extendation gd, and archlinux : pacman -S php-gd)

**Comment by AD-Wright** [comment]
@idreamerhx - similar issue for me, and it was resolved by uncommenting `;extension=gd2` (making `extension=gd2`) in php.ini.  Thank you.
