### ISSUE TITLE
Manage photos with a thesaurus ?

### ISSUE THREAD

**Issue by camillemonchicourt** [Piwigo/Piwigo#1225]
In addition of albums organization, we would need to be able to use a thesaurus, with organized hierarchized tag attached to photos. 
It was mentionned in https://github.com/Piwigo/Piwigo/issues/626
It has also been discussed here : https://fr.piwigo.org/forum/viewtopic.php?id=25378
I often hear that it is something missing to Piwigo.

Are there some projects to include a thesaurus in Piwigo or would it be something that could be added to Piwigo ?

**Comment by plegall** [comment]
Hi @camillemonchicourt 

Feature #626 (related albums) is partly coming for Piwigo 2.11. Piwigo will be able to handle "combined albums" URLs.

In Piwigo, I still think a thesaurus can only be created using albums, not tags. And if you want to rename "albums" into "Thesaurus", it's just a matter of language customization which Piwigo can do easily :-)

**Comment by tounoki** [comment]
Bonjour
La question d'un vocabulaire hiérarchisé pour décrire les images me paraît peut conciliable dans la pratique et dans le concept avec la logique d'albums.
J'ai l'habitude de travailler avec un thesaurus (donc hiérarchisé) pour décrire des images : ce dernier contient 12000 termes, et il hiérarchise aussi bien les lieux géographiques, que l'ancien testament que les "mammifères".
https://opentheso.huma-num.fr/opentheso/?idt=th285 

Bref si je tagge une image avec "chêne", "chapelle" et "chat", je trouverai cette image en cherchant "mammifère + arbre + édifice religieux".
De manière pragmatique, ce serait vraiment compliqué de reproduire l'arborescence d'un thesaurus via des albums.
Pour moi, c'est un manque majeur dans l'application pour s'adresser aux utilisateurs qui ont des pratiques d'informatique documentaire.

Les outils de gestion des thesaurus sont très normalisés maintenant et les formats d'échange comme d'API sont robustes.

Cette documentation traite du sujet : 
https://www.culture.gouv.fr/Thematiques/Musees/Pour-les-professionnels/Conserver-et-gerer-les-collections/Informatiser-les-collections-d-un-musee-de-France/Vocabulaires-scientifiques-du-Service-des-musees-de-France/Thesaurus-iconographique-systeme-descriptif-des-representations-de-Francois-Garnier 

Hope that help, dispo si besoin

**Comment by plegall** [comment]
Piwigo already has advanced indexing system, with default properties (title, description), custom properties, tags (flat), albums (hierarchy). It's advanced "for a photo library" system. It's certainly basic for a thesaurus management system, but Piwigo is a photo library manager.

Creating such a complex thesaurus system could lead to a complex User Interface, which is not what we want for a photo library. So for now, we don't plan to make tags hierarchical, considering albums already are and we can already do a lot with what we have.
