### ISSUE TITLE
Error when changing page

### ISSUE THREAD

**Issue by adadnc** [Piwigo/Piwigo#1284]
With version 11.0.0 I'm getting the error "infinite loop?" displayed whenever I click on next page in an album. The URL it calls looks like this https://myhost/piwigo/index.php?/categories/startcat-12

Is this known?

**Comment by Thibautg16** [comment]
Hi,

I have the same error as long as the url is of type "startcat-X", no worries with the URL of type "start-X".

**Comment by Thibautg16** [comment]
I think I found the bug, I just proposed a fix :
https://github.com/Piwigo/Piwigo/pull/1286
