### ISSUE TITLE
Syntax error in Norwegian language file after upgrading to Piwigo 11

### ISSUE THREAD

**Issue by boge90** [Piwigo/Piwigo#1287]
Apache error log:
PHP Parse error:  syntax error, unexpected '!' in /var/www/html/language/nb_NO/common.lang.php on line 358

Content at line 358
Velkommen!';

**Comment by plegall** [comment]
Thanks for the report!

OK, it's fixed on branch "translation". Will be fixed on 11.x when I get the new commits from branch "translation" to "11.x" when preparing the release.

**Comment by boge90** [comment]
Thanks for looking into this so quickly!
