### ISSUE TITLE
[UX] Do not hide Inactive plugins after activating a new one

### ISSUE THREAD

**Issue by mistic100** [Piwigo/Piwigo#1295]
In the plugins list after clicking "Show inactive plugins" and activating a new plugin, the list hides again.
I think it should stay visible.

Actually I don't see the point on hiding inactive plugins in the first place, at least my "preference" could be store in localStorage.

**Comment by plegall** [comment]
I have implemented a very simple "show inactive plugins after an activation" but I agree it should be better than that for a future "major" version. If possible, removing the full reload of the page, only "moving" the plugin from "inactive" to "active".
