### ISSUE TITLE
Error when running with php8

### ISSUE THREAD

**Issue by txtsd** [Piwigo/Piwigo#1305]
> 
> 
> Seems to be broken with php 8:
> ```
> [Fri Jan 29 18:24:24.149797 2021] [php:error] [pid 11906] PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /usr/share/webapps/piwigo/include/common.inc.php:20
> Stack trace:
> #0 /usr/share/webapps/piwigo/index.php(11): include_once()
> #1 {main}\n  thrown in /usr/share/webapps/piwigo/include/common.inc.php on line 20
> ```
> and this function is removed since php 8: https://www.php.net/manual/en/function.get-magic-quotes-gpc.php
> 
> any news upstream?
> 

as reported on the AUR: https://aur.archlinux.org/packages/piwigo/#comment-788761

**Comment by FanchTheSystem** [comment]
Fix are here : https://github.com/Piwigo/Piwigo/pull/1282/files

**Comment by plegall** [comment]
@MatthieuLP can you take a look at compatibility with PHP 8 please?

**Comment by txtsd** [comment]
Fixed in #1282
