### ISSUE TITLE
[11.2] admin dashboard is unavailable

### ISSUE THREAD

**Issue by extorn** [Piwigo/Piwigo#1308]
The website seems disconnected from the _data folder.
Here is the error when clicking on the  "Administration" link:

```Fatal error: Uncaught RuntimeException: SplFileInfo::getSize(): stat failed for /config/www/Piwigo-10.0.2/_data/_data in /config/www/Piwigo-10.0.2/admin/include/functions.php:644 Stack trace: #0 /config/www/Piwigo-10.0.2/admin/include/functions.php(644): SplFileInfo->getSize() #1 /config/www/Piwigo-10.0.2/admin/intro.php(415): get_fs_directory_size('/config/www/Piw...') #2 /config/www/Piwigo-10.0.2/admin.php(298): include('/config/www/Piw...') #3 {main} thrown in /config/www/Piwigo-10.0.2/admin/include/functions.php on line 644```

Note that it seems to be looking for the _data folder inside the _data folder so _data/_data.

**Comment by extorn** [comment]
Looking on a console at the actual _data folder, it appears to have a symlink inside - _data only this points to itself.
I'm not clear why this symlink is here, nor why it points to itself, but it does (it was created on Jan 5th, so likely by me when I was testing the Piwigo 11 server in parallel). Removing this symlink means the page then loads successfully.
Can the piwigo php be made more resilient?

**Comment by plegall** [comment]
If cac24635a94e7762380bd4e2165717eea7d14089 (included in Piwigo 11.2.0) didn't fix the problem, then ea69988eacc45ba7a4591a5581a2860cf7a2269a should!
