### ISSUE TITLE
Upgrade bundled Smarty to latest upstream 3.1.37 (required for php-8 compatibility and security fixes)

### ISSUE THREAD

**Issue by reubenfarrelly** [Piwigo/Piwigo#1309]
It appears Piwigo currently ships with a version close to Smarty 3.1.29, based on the change_log.txt file in piwigo/include/smarty .

This is very out of date, and subsequent upstream versions have fixed many bugs including most recently a php-8 compatiblity issue which I am now running into, that was fixed in the latest 3.1.37.  Version 3.1.37 is also the first upstream version where php-8 is tested.

There are also some security updates mentioned in the changelog (see version 3.1.32, and 3.1.33-dev-4, bugfix on 21.7.2017 as examples). 

Can we please have an updated Smarty commited to the release code to fix these issues?

**Comment by plegall** [comment]
Certainly not on 11.x. Too risky (might break plugins)

For 12.x, it's absolutely possible. We have to check the required PHP version to run the latest Smarty version.

**Comment by reubenfarrelly** [comment]
Now that version 12.0 is in beta, can this request please be reconsidered?  Smarty 3.1.39 is current:

https://www.smarty.net/

A reminder also that there are security vulnerabilities in earlier versions of Smarty which are present in the bundled version included in version 11 of Piwigo.

**Comment by plegall** [comment]
@MatthieuLP can you make some test on Piwigo 12beta with latest version of Smarty?

**Comment by plegall** [comment]
Smarty updated to version 3.1.39 in e537eac
