### ISSUE TITLE
Upgrade bundled JShrink to latest upstream (1.4.0) to fix php-8 issues

### ISSUE THREAD

**Issue by reubenfarrelly** [Piwigo/Piwigo#1310]
JShrink version 0.5.1 is included in piwigo/include/jshrink.class.php .

This is very out of date - this version was released by upstream some 6+ years ago.  Version 1.5.0 was released in December 2020:

https://github.com/tedious/JShrink

This also includes some fixes that help php-8 work better and is supported by upstream.  Prior to upgrading I was experiencing issues with image rendering hanging, but with this updated version and a minor tweak to piwigo/include/template.class.php to call the updated function name, I've now a functional piwigo 11.2.0 system that seems to work (with some warnings but it works nonetheless).

**Comment by reubenfarrelly** [comment]
Can this bundled version please be upgraded to upstream version 1.4.0 for version 12.0 of Piwigo?

**Comment by plegall** [comment]
#951 I close this issue but this is exactly the same request. I'm working on it.
