### ISSUE TITLE
Can't delete orphan tag

### ISSUE THREAD

**Issue by nicosomb** [Piwigo/Piwigo#1311]
On my tags page (back office), I have this JS error: 

```
Uncaught TypeError: dataTags.filter is not a function
    getNumberPages https://photos.loeuillet.org/_data/combined/1jg4dkm.js:151
    <anonymous> https://photos.loeuillet.org/_data/combined/1jg4dkm.js:162
1jg4dkm.js:151:48

``` 

With this issue, I can't delete the tag.

**Comment by plegall** [comment]
Hi @nicosomb (I was reading your annual report yesterday...)

Which web browser do you use? Did you try another one (just to check)?

**Comment by nicosomb** [comment]
Hello @plegall! 

I have the error on Firefox 85 and Chromium 87

![Capture d’écran_2021-02-02_09-39-14](https://user-images.githubusercontent.com/121870/106573975-99562400-653a-11eb-9144-1cbe87ceaa82.png)

**Comment by plegall** [comment]
@nicosomb can you check https://piwigo.org/forum/viewtopic.php?pid=179593#p179593 ?

**Comment by nicosomb** [comment]
Your changes fix my issue. Thank you!
