### ISSUE TITLE
Dysfunctional keywords/tags admin page in 11.2.0

### ISSUE THREAD

**Issue by erAck** [Piwigo/Piwigo#1312]
admin.php?page=tags results in a broken dysfunctional page.

Both, the pagination arrows and the Display 100,200,500,1000 buttons don't work. Typing into the Filter box doesn't. Also, when selection mode is activated the All,None,Invert buttons don't do anything. Adding a keyword works, deleting does not. Editing works, but confirming spins forever until x hit but the change is accepted after. I also noticed that the left sidebar menu is spoiled (i.e. all submenus are opened at once).

In the Firefox 78.7.0esr Web Console there are these errors:
```
Uncaught TypeError: dataTags.filter is not a function
    getNumberPages https://erack.net/gallery/_data/combined/1y747fn.js:151
    <anonymous> https://erack.net/gallery/_data/combined/1y747fn.js:162

Uncaught TypeError: AdminTools is undefined
    <anonymous> https://erack.net/gallery/admin.php?page=tags:3243
```
Firefox 84.0.2 reports even more locations of "dataTags.filter is not a function".

See also forum thread [Tags edition](https://piwigo.org/forum/viewtopic.php?id=30993).

**Comment by plegall** [comment]
Does it work any better when you deactivate plugin AdminTools?

**Comment by erAck** [comment]
No, same broken but a few more places for `dataTags.filter is not a function`.
