### ISSUE TITLE
Search in Keyword Manager not working 

### ISSUE THREAD

**Issue by dawsk-2021** [Piwigo/Piwigo#1320]
From version 11.0.0 the search for keywords in the keyword manager is no longer possible. The reason for this is a missing "toLowerCase" in the JavaScript function isDataSearched in the file admin/default/js/tags.js 

My fixed version:
function isDataSearched(tagObj) {
  let name = tagObj.name.toLowerCase();
  let stringSearch = $("#search-tag .search-input").val();
  if (name.includes(stringSearch.toLowerCase())) {
    return true;
  } else {
    return false;
  }
}

I also use the includes function instead of the startWith function. This means that the search pattern is also searched for within the keyword. Find that personally more comfortable.

**Comment by plegall** [comment]
Oh, yes thanks, that will fix #1315 

I agree, `includes` is better than `startsWith` here.

**Comment by dawsk-2021** [comment]
Thank you, that sounds good
