### ISSUE TITLE
Piwigo version 11.3.0 throws syntax error while adding 'Groups' on PHP 5.3

### ISSUE THREAD

**Issue by prbt2016** [Piwigo/Piwigo#1334]
Hello,

I was in the process of manual installation of Piwigo version 11.3.0 on PHP 5.3.29, MYSQL 5.5.62, Apache 2.2.34. However after successful manual installation when I visit inside the admin panel i.e :

Users->Groups->Add Group and enter group name and click on 'Add' button, group isn't added and following is thrown in Apache error logs:
`
PHP Parse error:  syntax error, unexpected '[' in /{{PATH}}/{{TO}}/{{PIWIGO}}/include/ws_functions/pwg.groups.php on line 362`

Could you please replicate this at your end and fix this?.

I checked on another server with PHP 5.4 and adding groups works there.

Also documentation shows that PHP 5.3 is the minimum required version for Piwigo

https://piwigo.org/doc/doku.php?id=user_documentation:learn:install:before

Are the minimum PHP requirements for installing Piwigo changed?.

**Comment by plegall** [comment]
Piwigo 11 should work with PHP 5.3. We're going to fix this one!

But in the future, certainly for Piwigo 12, we're going to request a much higher version of PHP. Something like PHP 7.2 maybe.

**Comment by prbt2016** [comment]
Okay thanks.

**Comment by prbt2016** [comment]
Thanks this is  working fine now on PHP 5.3 with Piwigo latest version 11.4.0. Thanks for the fix.
