### ISSUE TITLE
Filter album (Feature request)

### ISSUE THREAD

**Issue by boge90** [Piwigo/Piwigo#1337]
Hi,
I have been thinking it could be nice to have some kind of tag filtering mechanism when viewing an album in Piwigo.

In the sidebar we already have the "Related tags" section, however by clicking those tags, we will then see all pictures with that tag.
It would be nice to be able to apply that action on the current album instead.

Also, it would be very nice to not just only see pictures with a given tag e,g "Nature", however also be able to exclude tags. So if you have an album with nature and family pictures, you could view both sets by either "Including" the nature tag, or "Excluding" the nature tag.

I have been thinking that the the design could be simmilar to the "Related tags" section, like it has the "+" sign in front of a tag.

"+Tag" would include pictures with that tag
"-Tag" would exclude pictures with that tag

All of this could also just be an extention to the search feature in Piwigo if that would be simpler.

**Comment by plegall** [comment]
See #1955 it should produce the same result :-)
