### ISSUE TITLE
[11.x] storage calculation error, JPG files considered as "other"

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#1354]
while they should be "photo". The check on extension should be case insensitive.

**Comment by erAck** [comment]
I already wondered about my massive Other..
Fwiw, this in admin/intro.php works fine for me
`  $ext = strtolower($tabString[count($tabString) -1]);`
but faster would be a copy of $conf['picture_ext'] completed with upper case variants to search $ext in.
(mixed case like Jpg or jPG probably *can* be ignored..).
