### ISSUE TITLE
Problem with plugin AdminTools in "Tag Manager" and "Move Albums"

### ISSUE THREAD

**Issue by dawsk-2021** [Piwigo/Piwigo#1364]
The call of TagManager not include the {$ROOT_URL}plugins/AdminTools/template/admin_style.css correctly. The webpages shows following:

![Screenshot 2021-03-13 143222](https://user-images.githubusercontent.com/78554474/111031661-f6ca7400-8408-11eb-8d8f-af413a3c1d45.jpg)
 
The Problem is, the stylesheet of the admin_tools was not loaded. I can fix the problem as workaround, with a manual load in the admin/thmes/default/template/header.tpl file 
(add the line 
<link rel="stylesheet" type="text/css" href="{$ROOT_URL}plugins/AdminTools/template/admin_style.css">
).

I have test with Firefox and Chrome.

I think on both pages there is a small irregularity which causes Smarty not to correctly load the AdminTols CCS. On the other pages it works.

**Comment by plegall** [comment]
You say "add the line", but I see nothing :-/

**Comment by flop25** [comment]
@dawsk-2021 there is indeed something missing in your post ;)

> (add the line
> ).
> 
> I have test with Firefox and Chrome.

**Comment by dawsk-2021** [comment]
Sorry my mistake, i add the bold line. 

<meta charset="{$CONTENT_ENCODING}">
<title>{$GALLERY_TITLE} :: {$PAGE_TITLE}</title>
<link rel="shortcut icon" type="image/x-icon" href="{$ROOT_URL}{$themeconf.icon_dir}/favicon.ico">
<link rel="stylesheet" type="text/css" href="{$ROOT_URL}admin/themes/default/fonts/open-sans/open-sans.css">
**<link rel="stylesheet" type="text/css" href="{$ROOT_URL}plugins/AdminTools/template/admin_style.css">**

{strip}
{combine_css path="admin/themes/default/fontello/css/fontello.css" order=-10}
{assign "theme_id" ""}

I am aware that this is not a good solution since I am directly embedding a plugin at this point.

**Comment by dawsk-2021** [comment]
Sorry now the as code part 

`<meta charset="{$CONTENT_ENCODING}">
<title>{$GALLERY_TITLE} :: {$PAGE_TITLE}</title>
<link rel="shortcut icon" type="image/x-icon" href="{$ROOT_URL}{$themeconf.icon_dir}/favicon.ico">
<link rel="stylesheet" type="text/css" href="{$ROOT_URL}admin/themes/default/fonts/open-sans/open-sans.css">
<link rel="stylesheet" type="text/css" href="{$ROOT_URL}plugins/AdminTools/template/admin_style.css">

{strip}
{combine_css path="admin/themes/default/fontello/css/fontello.css" order=-10}
{assign "theme_id" ""}
`

**Comment by dawsk-2021** [comment]
----> <link rel="stylesheet" type="text/css" href="{$ROOT_URL}plugins/AdminTools/template/admin_style.css">

**Comment by dawsk-2021** [comment]
Sorry i can not insert the line because github remove the line 

link rel="stylesheet" type="text/css" href="{$ROOT_URL}plugins/AdminTools/template/admin_style.css

**Comment by plegall** [comment]
`AdminTools/template/admin_style.css` is loaded, actually. That's not the real problem in my opinion. There is something, javascript related, that causes the issue.

**Comment by plegall** [comment]
Actually, myself from the past already had found the problem... See #1080
