### ISSUE TITLE
Drop-down menu of a group not visible with Safari

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo#1379]
In Group Management of Piwigo 11.4.0, the drop-down menu allowing to "Duplicate", "Delete" and "Set as a group for new users" is not presented in Safari 14.1 as can be seen in the below screenshot:

<img width="1006" alt="Screenshot 2021-04-09 at 20 37 59" src="https://user-images.githubusercontent.com/7103032/114226782-58342300-9974-11eb-8742-b6c059c2360f.PNG">

What is expected is shown below with Firefox 87.0 on the same computer:

<img width="754" alt="Screenshot 2021-04-09 at 20 37 45" src="https://user-images.githubusercontent.com/7103032/114226660-2458fd80-9974-11eb-92da-3fd79a064c07.PNG">

**Comment by EddyLB** [comment]
Still an issue in 11.5.0 with Safari 15.1 (17612.2.6.1.1)

**Comment by EddyLB** [comment]
Still an issue with Piwigo 12.1.0 and Safari 15.1 (17612.3.3.1.2).

**Comment by plegall** [comment]
Still a bug on Piwigo 13 and upcoming 14.
