### ISSUE TITLE
[User Manager] DarkMode for user manager isn't done

### ISSUE THREAD

**Issue by MatthieuLP** [Piwigo/Piwigo#1401]
Currently the User manager in dark mode look like this : 

![Capture d’écran de 2021-05-06 14-48-03](https://user-images.githubusercontent.com/60923356/117300697-19619200-ae7a-11eb-8e7e-6a0ff8072ce8.png)

![Capture d’écran de 2021-05-06 14-49-01](https://user-images.githubusercontent.com/60923356/117300819-3d24d800-ae7a-11eb-9d49-7a71c6995bc1.png)

DarkMode needs to be added on user lines/cards and on some buttons and in the advanced filter box.

**Comment by plegall** [comment]
related to #1265
