### ISSUE TITLE
[Create User] Creating a user in the User Manager page doesn't work

### ISSUE THREAD

**Issue by MatthieuLP** [Piwigo/Piwigo#1405]
When creating a user in the user manager, you can't connect with it.

The user is saved in db.

**Comment by MatthieuLP** [comment]
Connection work if you edit the password after adding the user.

Example:
Create user : User1 pswd : 123456

Edit password to 123456789

Connection works with User1/123456789

**Comment by MatthieuLP** [comment]
Problem was that the input for password isn't in the label div. And the js was targeting an input inside the label which made the password undefined.

I changed the target in the js and it is now working fine.

**Comment by plegall** [comment]
Introduced with the new user manager for 12.x, fixed before the first 12beta
