### ISSUE TITLE
excessive mysqld usage on big piwigo instances

### ISSUE THREAD

**Issue by D33M0N** [Piwigo/Piwigo#1406]
adding to this forum topic:
https://piwigo.org/forum/viewtopic.php?id=31229

It seems that on some cases Piwigo goes mad and tries to do like 1.5MB mysql query (included in the attachment.)
when the url is like
https://-filtered-/picture.php?/478517
or
https://-filtered-/picture.php?/478517/categories

The picture even HAS CATEGORY, but when someone tampers with the URL and removes it there from there... 

it's a 7zip file, not a zip, because github doesn't allow to upload .7z, but 7z file was like 126k, whereas actual zip was 532k.
[dafuq.7z.zip](https://github.com/Piwigo/Piwigo/files/6444037/dafuq.7z.zip)

It's like serious DDOS vulnerability in Piwigo 11.4.x
And then when someone lets a crawler bot / script loose into this url that just starts "clicking" the next and previous arrow urls under there it's like game over for the site. It just kills MySQL, 100% CPU usage for hours;
When it was accidental or something, then restarting mysql service helps to stop this, until next bot comes along. Or even site own admin browsers prefetch or whatever.

**Comment by plegall** [comment]
can you show us the SQL queries directly here, simply by replacing the long list of ids with "[...]" ?

**Comment by jheinitz** [comment]
Hello,

I'm also experiencing this issue. When I skip to the next image it takes 
very long to load the page. I switched on SQL traces and could also see a 
statement with a list of many, many ids. I would be very interested in 
getting this fixed.

Please let me know if you want me to do some tests and traces for you. I'm 
still on 2.10.2 with my production site, but my sandbox running 11.4.0 has 
the same issue and a similar amount of pictures (5k) and albums (300).

Best regards

Jens

Am 7. Mai 2021 22:12:03 schrieb D33M0N ***@***.***>:

**Comment by D33M0N** [comment]
> can you show us the SQL queries directly here, simply by replacing the long list of ids with "[...]" ?

sorry no, my 3 different text editors die when I try this, because the entire query there is also in one line with 1.5M symbols. text wrap and stuff just can't handle that.

**Comment by D33M0N** [comment]
Might as well add, that for now I am using a safeguard in my MariaDB `/etc/mysql/my.cnf` under `[mysqld]` section:
`max_statement_time = 5`

(for actual MySQL you need to use `max_execution_time = 5000` instead (mysql value in milliseconds, whereas in MariaDB in seconds)

**Comment by plegall** [comment]
in [Admin>Configuration>Menu] deactivate the
« related albums » menu for all user status.
-- 
Pierrick LE GALL

**Comment by D33M0N** [comment]
You can't "deactivate" it, but only hide it?

**Comment by plegall** [comment]
I think Piwigo should even not compute the related albums on the picture.php page. It's not useful at this point.

**Comment by plegall** [comment]
related to #1392
