### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [Piwigo/Piwigo#1423]
Hello,

We recently received a vulnerability disclosure against your repository. I couldn't find an e-mail to contact or a security process to follow, so created this issue instead.

If you would like me to e-mail over the details or put them on the GitHub Issue, I'm more than happy to facilitate this for you. Otherwise, you can access the advisory [here](https://huntr.dev/bounties/1-other-Piwigo/Piwigo/).

It is private to you and the discloser of the report.

If you have any questions, let me know.

-- Jamie from huntr.dev

**Comment by flop25** [comment]
https://piwigo.org/contact
quite simple

and it seems that's about adding HTML tag (and so script) in the album name, which is a feature

**Comment by GewoonJaap** [comment]
These things shouldn't be a feature, since they put the user at risk..

**Comment by flop25** [comment]
Not at all
If an non admin user can alter a website without getting permission, that's an issue. That's a kind of an elevation of privileges 
If an admin can alter a website, well that's just the admin doing what it should do.
Be it Album title or the description of a picture, or the header, or anything.

Let's wait for the report to judge what is happening here

**Comment by GewoonJaap** [comment]
The report is already here in the first post..
However why is this a feature? Why would an admin want to insert HTML tags, and especially a script tag? There is really no useful use for it other then malicious stuff..
Take a look at a system like Wordpress, they alsofdon't have this "feature"
