### ISSUE TITLE
XSS Critical vulnerability {admin} account

### ISSUE THREAD

**Issue by nu11secur1ty** [Piwigo/Piwigo#1424]
Hello dear friends, you should fix this serious problem! [https://www.nu11secur1ty.com/2021/06/pwned-you-twice-xss-stored-and.html]
KR

**Comment by plegall** [comment]
Hi,

I don't understand. You mean that if you have access to the database and the code, you can insert some Javascript? Yes, I confirm. Not a security issue, as far as I understand.

**Comment by nu11secur1ty** [comment]
Just because you're an administrator doesn't mean you're a superman!

**Comment by nu11secur1ty** [comment]
This is a BIG Problem dear friend! Whatever KR

**Comment by nu11secur1ty** [comment]
So, please look carefully: https://streamable.com/p3ov5u
KR and have a nice day. :-)

**Comment by flop25** [comment]
You are not answering:
If you have access to the backend and the database,  you can already change every html code you want.
Can you explain why storing js script and interpretating it is more dangerous than changing every HTML template, creating a plugin who can change every urls and so on?

**Comment by nu11secur1ty** [comment]
> You are not answering:
> If you have access to the backend and the database, you can already change every html code you want.
> Can you explain why storing js script and interpretating it is more dangerous than changing every HTML template, creating a plugin who can change every urls and so on?

Because dear, some malicious guy can execute malicious code by using exactly JavaScript, that's why!
KR and exit 0;

**Comment by flop25** [comment]
Soooo executing JS in titles is more dangerous than creating a plugin in PHP, or changing a template to execute some JS or PHP ... ?

**Comment by nu11secur1ty** [comment]
Dear friends, I'm finished with this case. =) 
For the next steps, you should care of it alone. This is your software, I just trying to help you.
KR and exit 0;
