### ISSUE TITLE
Images not moved using the "move to album" batch action.

### ISSUE THREAD

**Issue by aminecmi** [Piwigo/Piwigo#1449]
Hello,

I'm trying to move images from one album to another using the batch manager.

When using the "move to album" action, the page shows a green success message saying "Information data registered in database".

When displaying the picture details, I can see that it is now linked to two albums. The first one where the file is located (the original one), and the one where I want it to be moved, but I can't remove that album.

When searching for the file in the file system, it is still located inside the original directory.

I also have these messages in the error logs of my domain

```
7/10 06:47:18 [error] 979#979: *32594 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: move in /var/www/piwigo/admin/batch_manager_global.php on line 201" while reading response header from upstream, client: IPADDR, server: DOMAIN, request: "POST /admin.php?page=batch_manager HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "DOMAIN"
```

In the file system, www-data is the owner of the galleries directory recursively, so it may not be a permission error.

I also tried to disable every plugin, but it didn't change anything.

I'm I missing something ? Is there something else I can do to move the files ?

```
    Piwigo 11.5.0 Check for upgrade
    Operating system: Linux
    PHP: 7.4.9 (Show info) [2021-07-10 06:54:16]
    MySQL: 5.5.5-10.3.29-MariaDB-0ubuntu0.20.10.1 [2021-07-10 06:54:16]
    Graphics Library: ImageMagick 6.9.10-23
```

Thanks for the help.

**Comment by klaoun** [comment]
hello, sw.js does not exist for piwigo. try delete. thanks

**Comment by aminecmi** [comment]
I don’t want to delete the pictures, I want to move them.

**Comment by klaoun** [comment]
sw.js, l'avez vous crée ou écris et mis dans la racine de piwigo ?

**Comment by aminecmi** [comment]
Non. Je ne l’ai ni rajouté ni retiré.

**Comment by klaoun** [comment]
essaye de supprimer sw.js. il ne fait pas partie de piwigo.

**Comment by aminecmi** [comment]
Pourtant l’installation web semble l’avoir installé.

Mais je ne pense pas que le problème vienne de là, puisque j’ai le message de sw.js assez souvent.
