### ISSUE TITLE
[Themes page] On first load errors are popping off

### ISSUE THREAD

**Issue by MatthieuLP** [Piwigo/Piwigo#1460]
![Capture d’écran de 2021-08-09 12-08-05](https://user-images.githubusercontent.com/60923356/128690969-5efca7d5-3f77-4d68-9a8e-2411a9a69a49.png)

To reproduce the error, purge compiled templates and go on the theme page. (+ You need to activate the plugin LocalFiles Editor)
To "fix" the error, just reload the page and they will disappear.

The objective here is that the error never occurs.

**Comment by klaoun** [comment]
hello,
yes I reproduce the error, maybe on this side --> return $s[$a['STATE']] <=> $s[$b['STATE']];

**Comment by MatthieuLP** [comment]
A fix to the error is to remove the "&" in localfiles_css_link_prefilter() function in LocalFiles Editor files in main.inc.php line 47

**Comment by plegall** [comment]
Discussion on this topic https://piwigo.org/forum/viewtopic.php?id=31414
