### ISSUE TITLE
[metadata] Exif support when host doesn't support (via PJMT)

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#15]
**Comment posted by BeSt on 17 Jun 2006 10:04**

Actually, I don&#039;t know what you mean Pierrick
&gt; My concern is the complexity of the resulting code.
Complexity is :
* size of code ? (yes, it&#039;s a problem, that&#039;s why I think it as an extension)
* speed of code ? (metadata aren&#039;t read too often ..)
* difficulty for the programmer ? (I think it&#039;s quite easy, but I don&#039;t know. Else I would have made it !)

**Comment by mistic100** [comment]
#338
