### ISSUE TITLE
Piwigo updates "new exciting features" link is blank - template var name error

### ISSUE THREAD

**Issue by 7tonin** [Piwigo/Piwigo#1546]
In Tools > Updates admin panel we can read (admin.php?page=updates - at least in version 11.*):
A new version of Piwigo is available.
This is a major update, with **new exciting features**. Some themes and plugins may be not available yet. 

I think it should link to https://piwigo.org/release-12.0.0

**Comment by 7tonin** [comment]
Here is the bug. 
https://github.com/Piwigo/Piwigo/blob/5075f97a46330dc72304695b2be3d90c3da3d18c/admin/themes/default/template/updates_pwg.tpl#L89
The link is correctly rendered by the code line before. https://github.com/Piwigo/Piwigo/blob/5075f97a46330dc72304695b2be3d90c3da3d18c/admin/themes/default/template/updates_pwg.tpl#L88
What's wrong with _translate_ ?

**Comment by klaoun** [comment]
hi ! possible ?

**Comment by 7tonin** [comment]
Oups, wrong line given...
By the way, found the problem.

**Comment by 7tonin** [comment]
Problem was easier to find with _Admin tools >  debug template_ checked
