### ISSUE TITLE
Plugins page is broken

### ISSUE THREAD

**Issue by TommyBacco** [Piwigo/Piwigo#1550]
After update to piwigo 12.0 I can't activate any plugin anymore (as a webmaster). Generally, it's not possible to click any button of the page.

I tried with firefox and chrome.

**Comment by plegall** [comment]
What's your PHP/MySQL version? (see page  [administration > tools > Maintenance > environment]

Does your web browser console says anything?

Are your administration menus (left side) all opened at the same time?

**Comment by TommyBacco** [comment]
I was on PHP 7.3 so I also tried with 7.4.24 with same outcome.
MYSQL: 5.5.5-10.4.18-MariaDB-1.

In console I get this:
![firefox_JnTlRJhUDZ](https://user-images.githubusercontent.com/65162638/140930748-d43efda5-746d-41b4-a80d-2525386de619.png)

> Are your administration menus (left side) all opened at the same time?

Yes, exactly

**Comment by plegall** [comment]
Are you in italian? https://piwigo.org/forum/viewtopic.php?id=31603

**Comment by ppbinag** [comment]
Piwigo 13.6.0 Проверить обновления
Installed on 29 Апрель 2023, 18 секунды назад
Операционная система: Linux
PHP: 7.4.27 (Показать информацию) [2023-04-29 13:49:01]
MySQL: 5.7.36-cll-lve [2023-04-29 16:49:01]
Библиотека изображений: External ImageMagick 6.9.10-68

When you try to enable the plugin, an error appears and the plugin is not activated. The file admin.lang.php has been checked and there are no errors. What to do?
