### ISSUE TITLE
Getting Blank page on frontend after upgrade from 11.5.0 to 12.0.0

### ISSUE THREAD

**Issue by GaneshKandu** [Piwigo/Piwigo#1551]
Hi,

I am getting blank page on front-end after upgrade from 11.5.0 to 12.0.0

getting following error 

Warning: Parameter 2 to TAT_no_photo_yet_prefilter() expected to be a reference, value given in /home/soft/public_html/piwi867/include/smarty/libs/sysplugins/smarty_internal_runtime_filterhandler.php on line 63 

Array ( [type] => 8 [message] => Undefined index: root_path [file] => /home/soft/public_html/piwi300/include/functions_url.inc.php [line] => 18 )

**Comment by prbt2016** [comment]
Hello,

I have an old installation of 11.5.0 and I am trying to upgrade to the latest version i.e 12.1.0 on Centos 7 with PHP 7.0, MYSQL 5.5, Apache 2.2.

I get blank page on visiting the frontend URL post upgrade and, on debug I get the same errors as mentioned above i.e  : 

```
Array ( [type] => 8 [message] => Undefined index: root_path [file] => /{{PATH}}/{{TO}}/{{PIWIGO}}/include/functions_url.inc.php [line] => 18 ) 

PHP Warning:  Parameter 2 to TAT_no_photo_yet_prefilter() expected to be a reference, value given in /{{PATH}}/{{TO}}/{{PIWIGO}}/include/smarty/libs/sysplugins/smarty_internal_runtime_filterhandler.php on line 63
```
This happens in the scenario when there are no images uploaded and when I upgrade and visit the frontend link the above error is thrown.

In another scenario on another server I checked with uploading images and then upgrading and the upgrade works fine and no error is thrown on the frontend link.

What could be the cause of this issue?. Could you please try to replicate this at your end ?

**Comment by prbt2016** [comment]
Hello,

Any update regarding the above query I posted?

**Comment by plegall** [comment]
This problem was actually in plugin Take a Tour. A new version of this plugin has been released to fix it.
