### ISSUE TITLE
Template extensions vanished?

### ISSUE THREAD

**Issue by fpoulain** [Piwigo/Piwigo#1564]
Many thanks for your work on piwigo.

I had a small template extension in place. Since upgrade to 12.1, it disappeared. I didn't fount how to recover it.

Is that feature been dropped?

Best regards.

**Comment by klaoun** [comment]
$conf['show_template_in_side_menu'] = true;

**Comment by fpoulain** [comment]
Thanks! It solved my problem.

Btw this seems neither in docs nor in release notes. Did I missed something?

**Comment by plegall** [comment]
> Btw this seems neither in docs nor in release notes. Did I missed something?

Nothing missed. We intend to make this feature "as secret as possible". I warmly recommend to avoid using it.

**Comment by fpoulain** [comment]
So maybe one should add this recommendation [here](https://fr.piwigo.org/doc/doku.php?id=utiliser:utilisation:fonctionnalites:template), as well as in the changelog. :)

Thanks for all your work on Piwigo.
