### ISSUE TITLE
Bug on switchbox.js (Tooltip behavior on album page)

### ISSUE THREAD

**Issue by Zacharieg** [Piwigo/Piwigo#1610]
Bug on tooltip behavior. 

Step to reproduce (on chrome) :
- Install Batch Downloader
- Install and set as default Bootstrap Darkroom
- Go to an album page 
- Click on the download button 
- Slide the mouse over the tooltip until the mouse is out of the tooltip

The tooltip should disappear, and click again on the button shouldn't work until page refresh.

**Comment by plegall** [comment]
Fixed on Bootstrap Darkroom theme directly, see https://github.com/tkuther/piwigo-bootstrap-darkroom/pull/309
