### ISSUE TITLE
[Admin Theme] Tags window to small with multiple tags

### ISSUE THREAD

**Issue by matthys70** [Piwigo/Piwigo#1612]
I gone add this as bug report as it seems no follow-up from forum and not able to find in bug-list/issue (also not closed).

When I'm in "edit mode" and enter more than 1 line of tags it will be difficult to 'see' all of them. The window just doesn't resize, even after saving, like it did with 11.5.0 version. See also [Piwigo forum](https://piwigo.org/forum/viewtopic.php?id=31871)

To solve this we need access to the admin theme as there is the problem:
admin/themes/default/theme.css

#action_add_tags .selectize-input.items.not-full.has-options.focus.input-active.dropdown-active, .selectize-input.items.not-full, .selectize-input.items.full {
  height: auto !important;
}

Entering the above line with LocalFiles Editor in local/css/rules.css doesn't help (out of scope?).
I edited the admin/themes/default/theme.css myself and change the above line mentioned in the css.

**Comment by outdoorbits** [comment]
Thank you for contribution or sponsorship.

**Comment by plegall** [comment]
See https://github.com/Piwigo/Piwigo/commit/e57b8b8449750eece0b091a554e85d07eee56810 on master and https://github.com/Piwigo/Piwigo/commit/bcbb44eca5bbe0a5bb6c6176382c9448351254f0 on 14.x
