### ISSUE TITLE
13.0.0beta1: syntax error in template file (updates_ext.tpl)

### ISSUE THREAD

**Issue by jradwan** [Piwigo/Piwigo#1643]
See https://piwigo.org/forum/post.php?tid=31967

After upgrading to 13.0.0beta1 and visiting the "Check for Updates" tab under Plugins I get this:

`Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:/usr/local/piwigo-beta/admin/themes/default/template/updates_ext.tpl" on line 212 "{/foreach}" unclosed {if} tag <-- thrown in /usr/local/piwigo-beta/include/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 212
`

It looks like there's a missing `{/if}` in admin/themes/default/template/updates_ext.tpl that needs to go with `{if $isWebmaster == 1}` on line 165. I just added it to the end of the file and that let the page load without error.

**Comment by plegall** [comment]
Fine, I mark this as fixed then :-)
