### ISSUE TITLE
13.0.0beta1: synced photos show as "orphan"

### ISSUE THREAD

**Issue by jradwan** [Piwigo/Piwigo#1644]
I use exclusively locally synchronized photos (I don't "upload" them). In Piwigo 13 my photos are showing up as "orphaned" on the Photo Details page under the Linked Albums section:

![image](https://user-images.githubusercontent.com/11047158/161634323-7ba0a095-30f8-4da6-bfa1-a8c494b11486.png)

The photo is _not_ an orphan since it exists in a physical album. And oddly, if I try to use the "With no album (Orphans)" filter in Batch Manager, no photos are listed (which is what I would expect):

![image](https://user-images.githubusercontent.com/11047158/161634726-5432761a-771e-4391-80fb-5d2a16143c1b.png)

**Comment by MatthieuLP** [comment]
The synced photos are not orphans now, but we still need to make the UI in such way that we can't unlink a physical album from a photo.
