### ISSUE TITLE
13.0.0beta1: "Purge Sessions" button text too large on Maintenance page

### ISSUE THREAD

**Issue by jradwan** [Piwigo/Piwigo#1645]
On the Maintenance page in 13.0.0beta1, the "Purge Sessions" button text is too large compared to the other buttons on the page.

![image](https://user-images.githubusercontent.com/11047158/161635164-0a28e4f7-7a04-4f18-add3-c43907a80d25.png)

**Comment by jradwan** [comment]
Still an issue in RC1.

**Comment by plegall** [comment]
@MatthieuLP exact same issue I also saw on 13.0.0RC1. I thought it was only in german, but it's not.
