### ISSUE TITLE
[Plugins Manager] After installing a plugin, activate action wrong redirect

### ISSUE THREAD

**Issue by MatthieuLP** [Piwigo/Piwigo#1651]
In the plugin installer, after installing a plugin, the activate link redirects to the plugin manager page but with the "Activated" filter selected. So we can't activate the plugin directly.

**Comment by MatthieuLP** [comment]
link to the forum post : https://fr.piwigo.org/forum/viewtopic.php?id=29666

**Comment by klaoun** [comment]
Hello @MatthieuLP 
Link to the forum post instead :
https://fr.piwigo.org/forum/viewtopic.php?id=29663
