### ISSUE TITLE
SVG support for piwigo

### ISSUE THREAD

**Issue by MatthieuLP** [Piwigo/Piwigo#1657]
We chosed to implement support of svg files for piwigo, this takes into account the thumbnail on the edit picture page.

**Comment by klaoun** [comment]
hello,
I try this #1657 :)
thanks

**Comment by klaoun** [comment]
hello, I see the thumbnail on the edit picture page. good job !

**Comment by klaoun** [comment]
hello, I have a syntax error on the commas (,) see below

**picture.php**
`RVAS = {
derivatives: [
{w:,h:,url:'i.php?/upload/ec-2s.svg',type:'2small'},{w:,h:,url:'i.php?/upload/ec-xs.svg',type:'xsmall'},{w:,h:,url:'i.php?/upload/ec-sm.svg',type:'small'},{w:,h:,url:'i.php?/upload/ec-me.svg',type:'medium'},{w:,h:,url:'i.php?/upload/ec-la.svg',type:'large'},{w:,h:,url:'i.php?/upload/ec-xl.svg',type:'xlarge'},{w:,h:,url:'i.php?/upload/ec-xx.svg',type:'xxlarge'}],
cp: '/mondossierinstallation/'
}`

the display of the image is not displayed and I can not put in representative. Courage continues 💯

**Comment by klaoun** [comment]
#1018 support svg
