### ISSUE TITLE
when adding new photos, add the thumbs to the right not to the left

### ISSUE THREAD

**Issue by jeyca** [Piwigo/Piwigo#1691]
while uploading photos, there will be thumbs created below the upload section. New photos are added to the left, so all thumbs jump to the right which makes this pretty choppy. Better ad new images to the right so already added image thumbs stay in their place

**Comment by plegall** [comment]
But if you do this, you won't see the 50th photo added, because out of visible screen :-/

**Comment by plegall** [comment]
We've discussed this matter with our designer (Alice) and she agrees with me (it's not always the case ;-)
