### ISSUE TITLE
Admin page not loading

### ISSUE THREAD

**Issue by LeoJr2015** [Piwigo/Piwigo#1722]
Upon completely installing a fresh copy of 13RC3, I cannot load the admin page. It returns the following:

```
Deprecated: number_format(): Passing null to parameter #1 ($num) of type float is deprecated in /mnt/2tb_usb2/html/admin/include/functions.php on line 3381

Warning: file_get_contents(./_data/cache/piwigo_news-en.cache.php): Failed to open stream: No such file or directory in /mnt/2tb_usb2/html/admin/include/functions.php on line 3507

Fatal error: Uncaught TypeError: array_slice(): Argument #1 ($array) must be of type array, bool given in /mnt/2tb_usb2/html/admin/include/functions.php:3510 Stack trace: #0 /mnt/2tb_usb2/html/admin/include/functions.php(3510): array_slice() #1 /mnt/2tb_usb2/html/admin/intro.php(177): get_piwigo_news() #2 /mnt/2tb_usb2/html/admin.php(320): include('...') #3 {main} thrown in /mnt/2tb_usb2/html/admin/include/functions.php on line 3510
```
I am using PHP 8.1.2 (cli) (built: Aug 17 2022 13:08:39) (NTS).

Thanks for any help!

**Comment by MatthieuLP** [comment]
Hello, i can not currently reproduce your problem, can you give me the names of all the activated plugins ?
Also add a screenshot so i can see how the issue occurs. 

Thank you !

**Comment by LeoJr2015** [comment]
I needed help over two weeks ago. I have since removed Piwigo and installed Chevereto. I can no longer gather information on that problem. All I did was upgrade my Ubuntu, and PHP was upgraded from 7 to 8. Then the Piwigo stopped working properly.
When you release a version that works out of the box for PHP 8, I might switch back.

**Comment by klaoun** [comment]
Hi @MatthieuLP 
Le fichier piwigo news en cache.php n'existe pas.

**Comment by viba1** [comment]
Hi all,
Same problem here with a fresh piwigo 13.4.0 install.
All plugins are disabled. 
environment:
   - alpine linux 3.17
   - php 8.1
   - nginx 1.23.3

See logs:

2022/12/22 15:52:38 [error] 11#11: *27 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: array_slice(): Argument #1 ($array) must be of type array, bool given in /usr/share/nginx/html/admin/include/functions.php:3593
Stack trace:
#0 /usr/share/nginx/html/admin/include/functions.php(3593): array_slice()
#1 /usr/share/nginx/html/admin/intro.php(198): get_piwigo_news()
#2 /usr/share/nginx/html/admin.php(341): include('...')
#3 {main}
  thrown in /usr/share/nginx/html/admin/include/functions.php on line 3593" while reading response header from upstream, client: 172.18.0.6, server: localhost, request: "GET /admin.php HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: …
