### ISSUE TITLE
pwg.images.setCategory to associate/dissociate/move photos to albums

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#1735]
As described on https://github.com/Piwigo/Piwigo/issues/802#issuecomment-944392667 we would need a dedicated API method to associate/dissociate/move photos and albums... instead of multiple calls to `pwg.images.setInfo`

cc @EddyLB @remi-martin

**Comment by plegall** [comment]
@EddyLB I have implemented `pwg.images.setCategory`. It returns nothing (except a `stat=ok`, of course). Would you like some specific data in return?

**Comment by EddyLB** [comment]
@plg Would it be possible to return the same album data as those returned by `pwg.categories.getList` so that we can update data in cache?
