### ISSUE TITLE
 Warning: Cannot modify header information - headers already sent in /var/www/piwigo/action.php on line 228

### ISSUE THREAD

**Issue by jspam** [Piwigo/Piwigo#1746]
I'm getting the above warning when trying to download an image in Piwigo 13.0.0. This corrupts the download.

Could be related to dd44d0e40999632fb1d80f313f51b6decbfa937c, as I think headers can't be sent after calling `flush()`

**Comment by plegall** [comment]
OK, looks a lot like https://piwigo.org/forum/viewtopic.php?id=32254

Did you try to install the previous version of `action.php` ?

**Comment by plegall** [comment]
and also, is it related to #1741 (version of Firefox)

**Comment by jspam** [comment]
What I did as a quick fix is to move the `flush()` call after the `foreach` loop. That works.

**Comment by erAck** [comment]
Just created https://github.com/Piwigo/Piwigo/pull/1749

**Comment by plegall** [comment]
Fixed on aca0771
