### ISSUE TITLE
 Fatal error: Uncaught Error: Call to undefined function userprefs_get_param() - themes.class.php:423

### ISSUE THREAD

**Issue by coop2540** [Piwigo/Piwigo#1751]
I got this error after upgrade version 13

Fatal error: Uncaught Error: Call to undefined function userprefs_get_param() in /admin/include/themes.class.php:423 Stack trace: #0 /admin/include/themes.class.php(50): themes->get_fs_themes() #1 /admin/include/updates.class.php(38): themes->__construct() #2 /admin/updates_pwg.php(29): updates->__construct() #3 /admin/updates.php(28): include('/var/www/client...') #4 //admin.php(320): include('/var/www/client...') #5 {main} thrown in /admin/include/themes.class.php on line 423

**Comment by WilliamFromTW** [comment]
i have the same problem by executing upgrade ( https://ip:port/admin.php?page=updates )
it will back to old version (12.3.0 docker version)  after replace old admin/include/themes.class.php.

**Comment by plegall** [comment]
Curious issue. Don't you find the function `userprefs_get_param` in file include/functions_user.inc.php ?

**Comment by WilliamFromTW** [comment]
my env:
docker piwigo (https://hub.docker.com/r/linuxserver/piwigo) 12.3.0 

1. no "include/functions_user.inc.php" after upgrade 
i think it's not finish update new version files
2. 
appear "gateway timeout"   after  auto upgrade for a while.
![image](https://user-images.githubusercontent.com/5213198/195811698-fea20980-a649-46cb-b16d-2b3137d52902.png)

then  show nothing 
when fresh page (F5)

![image](https://user-images.githubusercontent.com/5213198/195811856-a5aa5c35-e84a-43d6-bbf6-7804bcc6ede6.png)

**Comment by plegall** [comment]
function `userprefs_get_param` was introduced in Piwigo 13. You should not have it on a Piwigo 12.3.0. You seem to have an "hybrid" environment mixing files from Piwigo 13.0.0 and Piwigo 12.3.0.

**Comment by WilliamFromTW** [comment]
thanks.
 maybe i should restore to 12.3.0 and try again

**Comment by coop2540** [comment]
I did the update through piwigo, due to the announcement of the new version 13. I got the error.
Afterwards, I downloaded version 13 from github and ftp it, and the error continues.
The update section in piwigo says I have 12.3.0, but if I try to update it says I'm up to date.
I need to check this: Can't find the userprefs_get_param function in the include/functions_user.inc.php file?

**Comment by coop2540** [comment]
> Curious issue. Don't you find the function `userprefs_get_param` in file include/functions_user.inc.php ?

The function is there, line 1854. Then seems that this isn't the problem.

**Comment by plegall** [comment]
If the problem is related to a specific architecture in Docker, I'm afraid we can't do much about it. Unless someone says "I have this problem and I'm not using Docker".

**Comment by coop2540** [comment]
> If the problem is related to a specific architecture in Docker, I'm afraid we can't do much about it. Unless someone says "I have this problem and I'm not using Docker".

I'm not using Docker
Apache and PHP 7.4

**Comment by coop2540** [comment]
> If the problem is related to a specific architecture in Docker, I'm afraid we can't do much about it. Unless someone says "I have this problem and I'm not using Docker".

I'm not using Docker
Apache and PHP 7.4

**Comment by capste** [comment]
I have PHP versione 7.1.33

**Comment by coop2540** [comment]
The problem has disappeared.
Possibly in my case it was something related to the php-fpm cache.
Thanks for everything.
