### ISSUE TITLE
[sync] images with ill longitude/latitude crashes sync

### ISSUE THREAD

**Issue by rgrr** [Piwigo/Piwigo#1760]
I have old images which have 720 for longitude/latitude which correctly is rejected on database sync.  Unfortunately the sync aborts at this point.
sync should check the limits before sending the SQL statement to mysql.

(PR available)

**Comment by rgrr** [comment]
PR is here: https://github.com/Piwigo/Piwigo/pull/1762

**Comment by klaoun** [comment]
hi
I propose this pr #1762 for 14beta 3 :)

thanks
