### ISSUE TITLE
Mobile album photo view in 13.1.0 not working anymore due to syntax error in footer.tpl in smartpocket theme (with PHP 7.x)

### ISSUE THREAD

**Issue by bigcookie** [Piwigo/Piwigo#1766]
Hello,

i updated to 13.1.0 recently, but the photo view inside an album is not working anymore. Thrown error in GUI:

`
Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:/var/www/vhosts/xxxx/xxxx/themes/smartpocket/template/footer.tpl" on line 20 "document.cookie = 'screen_size='+jQuery(document).width()+'x'+jQuery(document).height()+';path={isset($COOKIE_PATH) ? $COOKIE_PATH : ''}';" - Unexpected " ? ", expected one of: "}" <-- thrown in /var/www/vhosts/xxxx/xxxxx/include/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 20
`

Standard view works fine. Albums are still listed on mobile, but when opening an album, no photos are shown and the error is listed at the bottom of the page

**Comment by bigcookie** [comment]
![Uploading 52F3062F-BD2E-4886-859F-4FC48147AE96.jpeg…]()

**Comment by bigcookie** [comment]
![64F451EB-BE05-4A7D-BCE0-816CB0053CEF](https://user-images.githubusercontent.com/2866102/197384497-88fb949e-4664-46c4-ad65-0e4aafebf9ec.jpeg)
![5A33AFF6-8305-423A-91E9-2A4963AC13CA](https://user-images.githubusercontent.com/2866102/197384502-e7ac83a1-62c8-4f6b-8433-8708548c720a.jpeg)

**Comment by bigcookie** [comment]
I checked the footer template in
themes/smartpocket/template/footer.tpl
I changed the line 20 from:
`document.cookie = 'screen_size='+jQuery(document).width()+'x'+jQuery(document).height()+';path={isset($COOKIE_PATH) ? $COOKIE_PATH : ''}';`
to
`document.cookie = 'screen_size='+jQuery(document).width()+'x'+jQuery(document).height()+';path={$COOKIE_PATH}';`

So I reverted the latest php 8.x change for now. The template error is gone and all photos are showing properly.
Unfortunately I dont know how the syntax should be in a corrected way, so I cannot fix it and commit :-(...

**Comment by bigcookie** [comment]
I tried this syntax:
`document.cookie = 'screen_size='+jQuery(document).width()+'x'+jQuery(document).height()+';path={$COOKIE_PATH|default:''}';`
Not sure if correct, if confirmed to be working for others, this would be a solution...

**Comment by erAck** [comment]
This part
`+';path={isset($COOKIE_PATH) ? $COOKIE_PATH : ''}';`
of course is wrong for the levels of single quotes forming string literals to assemble.
I'd guess it should instead be
```
+';path='{isset($COOKIE_PATH) ? $COOKIE_PATH : ''};
```

**Comment by bigcookie** [comment]
Tested my patch (https://github.com/Piwigo/Piwigo/issues/1766#issuecomment-1288154812) also on PHP 8 - works so far. I created a PR
https://github.com/Piwigo/piwigo-smartpocket/pull/8

**Comment by jamie-marchant** [comment]
Any work around in the meantime?

**Comment by erAck** [comment]
Sure, try the patch of the pull request mentioned and give feedback whether it works for you. Or try the change of my previous comment. One of them should work. Or replace that line with the old code as mentioned above in https://github.com/Piwigo/Piwigo/issues/1766#issuecomment-1288151049 .

**Comment by erAck** [comment]
> Tested my patch
I'm not convinced of that approach, see my comment at the patch.

**Comment by plegall** [comment]
@erAck @bigcookie have you tested the commit pushed by @MatthieuLP ? https://github.com/Piwigo/piwigo-smartpocket/commit/738dcde354d73fad6b08442dcebdc9b5e8fbc002

**Comment by erAck** [comment]
@plegall @MatthieuLP yes that works, thanks!

**Comment by jamie-marchant** [comment]
I don't have a phone with this problem but my friend says the site is now working for her.

**Comment by bigcookie** [comment]
@plegall the patch from @MatthieuLP works for me.
I agree, that I didnt understand to replace a missing string with an empty one. I just tried to fix the syntax error. The new patch looks better to me.
I will cancel my PR.
