### ISSUE TITLE
[13.3.0] Missing '?' in links

### ISSUE THREAD

**Issue by mathieu-massaviol** [Piwigo/Piwigo#1813]
Just upgraded from 12.3.0 to 13.3.0 (with php 7.4)

I have a problem with all internal links of the frontend (not in the administration) that are missing a '?' (when i add it manually i can see the correct page). It happens on all the themes i have tested (elegant, bootstrap_darkroom and smartpocket).

For exemple the link to a category is
> mypiwigoinstance/index.php/category/mycategory

but should be

> mypiwigoinstance/index.php?/category/mycategory

**Comment by mathieu-massaviol** [comment]
I temporarily solved the problem by adding the following line in *includes/functions_url.inc.php* at line 128 on my server

`$conf['question_mark_in_urls'] = true;`

**Comment by plegall** [comment]
but that's the default configuration!

Is your file `include/config_defaults.inc.php` corrupted? Use plugin Check Files Integrity to very https://piwigo.org/ext/extension_view.php?eid=844
don't you have this setting set to `false` in your `local/config/config.inc.php` file?

**Comment by mathieu-massaviol** [comment]
The config file was indeed corrupted, i restored it to default and everything is okay now. 

Thanks for the help.
