### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by mike993** [Piwigo/Piwigo#1829]
Hi,
i reported a security vulnerability about a stored XSS.

you can see all the details here:

https://huntr.dev/bounties/24782873-43d5-4315-bacc-a3ae18ce41f9/

i hope i was helpful

**Comment by plegall** [comment]
Please see [the "Security" section on Github](https://github.com/Piwigo/Piwigo/security/policy#reporting-a-vulnerability).
