### ISSUE TITLE
[Album Manager] Add custom tooltip for the badges

### ISSUE THREAD

**Issue by MatthieuLP** [Piwigo/Piwigo#1837]
![image](https://user-images.githubusercontent.com/60923356/208913849-a533979b-9e84-4fd8-b1ba-f1c82b3424f6.png)
We want to implement a dropdown under the badges for more clarity in the album manager.

**Comment by plegall** [comment]
Can you increase distance between icon and text?
![Screen Shot 2022-12-25 at 11 07 56](https://user-images.githubusercontent.com/9326959/209463942-fc7d562d-6069-4a0e-9d31-a05f0d9208a6.png)

I also wonder if "lineage" is the right word to use. We will rediscuss it.

**Comment by MatthieuLP** [comment]
Dark mode isn't implemented.
