### ISSUE TITLE
[activities] hide connections from user activity list

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#1838]
On photo libraries with many users connecting everyday, the list of user activities quickly becomes "polluted" with "not that important" information.

We would like to be able to hide all connections or just hide connections from "non admins".

**Comment by klaoun** [comment]
hello
with the modif I have this error ?
<br />
<b>Parse error</b>:  syntax error, unexpected 'else' (T_ELSE) in <b>../include/ws_functions/pwg.php</b> on line <b>452</b><br />
