### ISSUE TITLE
How to move piwigo to new server?

### ISSUE THREAD

**Issue by Fsociety-one** [Piwigo/Piwigo#1860]
Can anyone to help me?
here's mine simple move:
1. copy /usr/local/nginx/html/piwigo to the new server
2. back up MySQL database from source, restore it into new database on new server
It works, but there's some problem, the photo seems to lost (the second photo)：
![20230206221545809](https://user-images.githubusercontent.com/49600740/217127022-4d8e7dd1-dab6-43da-a7be-75566c5ad3bc.jpg)
![20230206222038167](https://user-images.githubusercontent.com/49600740/217127044-d77be06f-561b-4dc9-b645-af237e5bff39.jpg)

Most grateful for any hints.

**Comment by plegall** [comment]
Did you have a watermark configured? if yes, reconfigure it.

**Comment by Fsociety-one** [comment]
> Did you have a watermark configured? if yes, reconfigure it.

Thx，I'll try
