### ISSUE TITLE
[PHP8.1] RSS feed: Function strptime() is deprecated

### ISSUE THREAD

**Issue by math-GH** [Piwigo/Piwigo#1897]
This warning makes the export of an RSS feed impossible:
`Deprecated:  Function strptime() is deprecated in /.../include/functions_notification.inc.php on line 604`

How to reproduce:
![grafik](https://user-images.githubusercontent.com/1645099/229267455-a944708b-5590-410e-bdf6-4757e477420e.png)

![grafik](https://user-images.githubusercontent.com/1645099/229267458-1e961c8d-b5e4-46e0-9ff6-ddd0d66d3546.png)

![grafik](https://user-images.githubusercontent.com/1645099/229267464-30262d2b-2759-4a6f-8c3a-b86c05033d04.png)

Expected:
have a valid RSS feed

Environment:
Piwigo 13.6.0
PHP8.1

**Comment by klaoun** [comment]
hello
the strptime() function is deprecated since php 8.1
try replacing this with date_parse_from_format
I use by installing an extension on google "rss feed reader" to read it
If there is a way to include this idea in piwigo I'm interested :)

**Comment by klaoun** [comment]
Hi @plegall
I propose it from version 14 🙏

**Comment by plegall** [comment]
@klaoun I made a simpler fix

**Comment by klaoun** [comment]
@plegall ok approved fix
