### ISSUE TITLE
menubar_related_categories.tpl not in template_extension list

### ISSUE THREAD

**Issue by ahtoagah** [Piwigo/Piwigo#1898]
Please add **menubar_related_categories.tpl** to the **admin/extend_for_templates.php** file.

Explanation: I would like to customize the default menubar_related_categories.tpl and put it in my template-extension directory. However, there is no Original menubar_related_categories.tpl listed under Configuration >> Templates which I could bind it to. All my other customized templates are the default list, but not this one.

Right now I can directly modify the original file in themes/default/template/, and that works fine. However, modifying that file will not survive upgrades to Piwigo, unlike those in template-extension/ . 

Thank you.
Mike Williams

Piwigo 13.6,
apache2.4
php8.1

**Comment by klaoun** [comment]
hi
which theme installed ?
thank you
