### ISSUE TITLE
[13.6] pwg.category.calculateOrphans returns a wrong number of orphans

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo#1899]
When deleting an album from the web UI, the server returns a wrong number of orphans. For example, in the below screenshots, we see that the selected album contains 2 photos and the server calculates 4 future orphans:

<img width="993" alt="Screenshot 2023-04-14 at 16 33 55" src="https://user-images.githubusercontent.com/7103032/232075291-811b42e1-963b-4cba-ba64-9c9e3618291a.png">

<img width="430" alt="Screenshot 2023-04-14 at 16 39 50" src="https://user-images.githubusercontent.com/7103032/232075823-a3417672-a688-4bcb-b205-5cca0223f4b5.png">

Consequently, the iOS app also returns a wrong number of orphans:
![Simulator Screenshot - iPhone 14 Plus - 2023-04-14 at 16 46 02](https://user-images.githubusercontent.com/7103032/232077414-ac314aeb-1c8d-434a-a06b-6b4ba40cafb6.png)

**Comment by plegall** [comment]
did you also test it on `master` ? (for the future version 14) The "edit album" administration page is completely rewritten.

**Comment by plegall** [comment]
@EddyLB I can't reproduce. Can you tell us what your web browser (or the iOS app) gets as reply to `pwg.categories.calculateOrphans` ?

<img width="694" alt="Screenshot 2023-04-17 at 18 02 29" src="https://user-images.githubusercontent.com/9326959/232544143-e8517252-445f-4050-82b0-450d91c9285a.png">

**Comment by EddyLB** [comment]
@plegall I have deleted the album and sub-album with which I was encountering the issue. I have recreated albums, uploaded photos, copied and moved some photos, etc. but cannot reproduce the problem either. 

This issue probably appears after a specific manipulation or a series of manipulations. I propose to close it. I will reopen it when I will be able to reproduce it.

**Comment by plegall** [comment]
Fine, let's close for now.
