### ISSUE TITLE
Bad Request on Automatic Sort Order

### ISSUE THREAD

**Issue by pgl1920** [Piwigo/Piwigo#1918]
After upgrade from 13.6.0 to 13.7.0 I noticed an issue with "Automatic sort order" function.

**Http 400 Bad request  - missing token**

**Step to reproduce this issue:**

1. Albums > Manage > Automatic Sort Order 
2.  Select any type of option and submit.

With previous release (13.6.0) this feature was working fine.

**Comment by plegall** [comment]
See issue #1914
