### ISSUE TITLE
[installation & upgrade] update 122 fails on Windows due to rename()

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#194]
**Reported by flop25 on 12 Jul 2012 16:22**

**Version:** 2.4.1

the update 122
&quot;derivatives: new organization of &quot;upload&quot; and &quot;galleries&quot; directories&quot;
fails because of the bad behavior of rename() on Windows : it seems there is problem to overwrite exiting files using rename() under Windows

my searches give me :
https://bugs.php.net/bug.php?id=29812
http://www.php.net/manual/fr/function.rename.php#102274
https://github.com/contao/core/issues/3593
https://github.com/contao/core/issues/3390

[Piwigo Bugtracker #2691](http://piwigo.org/bugs/view.php?id=2691)

**Comment by plegall** [comment]
@flop25 do you still encounter the problem?

**Comment by flop25** [comment]
ouch
I need to install an old one and do the update but it would be on a Win10
I will try I assign myself

**Comment by flop25** [comment]
cant reproduce
