### ISSUE TITLE
[search] Empty filter deletion is bugged

### ISSUE THREAD

**Issue by MatthieuLP** [Piwigo/Piwigo#1945]
In the new multi-criteria search when you delete an empty filter and then go to the filter manager and validate the form, on the reload, the deleted filter is back in the filter list.

Reproduce the issue :
- Open a filter and click 'Delete' action
- Open the filter manager
- Click validate

When the page reloads, the filter you deleted should be back.

A semi-fix to this issue is to change ``` $("#addLinkedAlbum").has(e.target).length === 0 ``` to ``` $("#addLinkedAlbum").has(e.target).length !== 0 ``` But it breaks the filter's closing when you click outside them.
For now we choose to keep it as it is because the path to reproduce is unlikely to happen and can be worked around if needed.

**Comment by MatthieuLP** [comment]
A quick way to solve this would be to trigger the page reload even if the filter we delete is empty.

In ```mcs.js``` :
For earch filter ```.delete").on("click"``` listenner just change the ```performSearch()``` function's second param to ```true```.
It will trigger the reload.

**Comment by plegall** [comment]
Bug fixed with the proposed workaround, see https://github.com/Piwigo/Piwigo/commit/f62d255e0ab689d8195bc7d19c16811b3f9560b3
