### ISSUE TITLE
Theme does not change 

### ISSUE THREAD

**Issue by lbm-services** [Piwigo/Piwigo#1950]
I installed Bootstrap Darkroom, activated, made it default, even cleared user cache and disabled Modus but I still see Modus theme.
What's going on? This simple things should not be a pain in the ass. 
I am using latest version 13.8.
If I disable the other themes I get:
```
Warning: include(/themeconf.inc.php): Failed to open stream: No such file or directory in /var/www/piwigo/include/template.class.php on line 1141

Warning: include(): Failed opening '/themeconf.inc.php' for inclusion (include_path='.:/usr/share/php') in /var/www/piwigo/include/template.class.php on line 1141

Fatal error: Uncaught --> Smarty: Unable to load template 'file:menubar.tpl' <-- thrown in /var/www/piwigo/include/smarty/libs/sysplugins/smarty_internal_template.php on line 195
```
wtf?

**Comment by lbm-services** [comment]
Nevermind. I switched to Photoprism. No hassle with themes anymore.

**Comment by plegall** [comment]
I don't know Photoprism enough. I've looked at it and it seems really nice. They made some very basic design choices different from Piwigo, such as "only one user interface, not one for gallery and another one for administration" and it makes things very different, indeed :-)
