### ISSUE TITLE
Implement /health api endpoint

### ISSUE THREAD

**Issue by tfagart** [Piwigo/Piwigo#1954]
Hello,

Is this possible to implement a /health endpoint on your API.

Something that will do

https://testfully.io/blog/api-health-check-monitoring/

Thanks

Thomas

**Comment by plegall** [comment]
Wouldnt't `https://demo1.piwigo.com/ws.php?method=pwg.session.getStatus` be good?

**Comment by tfagart** [comment]
Hello, thanks for your answer, it will do the trick.

Regards

Thomas
