### ISSUE TITLE
Why lower text?

### ISSUE THREAD

**Issue by osworx** [Piwigo/Piwigo#1963]
https://github.com/Piwigo/Piwigo/blob/4ac772224f25f1b2f3bf94bd1f9c45b653d561f5/include/functions_html.inc.php#L614

While this funtion with strtolower may have rights for some languages, it makes no sense for a language like German.
Maybe also other languages will write the first letter uppercase, there should be a (config) setting to avoid such behaviour.

That is also valid for the line 618 below.

**Comment by plegall** [comment]
I think the idea was to avoid having the word "visits" translated twice. One for `%d visits` and another one as title `Visits`. But you're absolutely right, changing the case may result in a grammatical error, depending on language.

I fixed it.

**Comment by osworx** [comment]
Thx for thinking about that.
I understand that it may be fine for some languages.

So, why not adding another config setting vor such?
e.g. in config_default.inc.php > **$conf['lower_upper'] = true; // or false .. which one is preferred as default**

And inside the language file(s) a value which will override the confg value.
OR, only inside the language files common.lang.php and (if exists) plugin.lang.php a simple **$lang['_lower'] = true; // false**
(the _ indicates here that it is not a translateable value ..

Therefore both cases can be true (when needed).
