### ISSUE TITLE
undefined array key

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [Piwigo/Piwigo#1970]
Goodmorning,i receive multiple errors on collection tab

Warning: Undefined array key "cat" in /opt/lampp/htdocs/xxx/_data/templates_c/xr1exc^0bb276d1f6c18ee93c79b1cfc4aa034f5a00551d_0.file.menubar_user_collections.tpl.php on line 51

Warning: Attempt to read property "value" on null in /opt/lampp/htdocs/xxx/_data/templates_c/xr1exc^0bb276d1f6c18ee93c79b1cfc4aa034f5a00551d_0.file.menubar_user_collections.tpl.php on line 51

Warning: Trying to access array offset on value of type null in /opt/lampp/htdocs/xxx/_data/templates_c/xr1exc^0bb276d1f6c18ee93c79b1cfc4aa034f5a00551d_0.file.menubar_user_collections.tpl.php on line 51

**Comment by klaoun** [comment]
Hi
Normally it IS plugin "user collections" in function bug

Not bug piwigo

Wich PHP ? Please
Wich sql ? Please

Tks

**Comment by andreameneguzzoinfol** [comment]
> Hi Normally it IS plugin "user collections" in function bug
> 
> Not bug piwigo
> 
> Wich PHP ? Please Wich sql ? Please I test with me
> 
> If it IS désactived, it s ok👍
> 
> Tks

seems to be a problem of bootstrap darkroom theme 
i have changed the theme and it doesn't show any errors on the user collections

**Comment by klaoun** [comment]
hello
this happens when when it's php 8+

**Comment by plegall** [comment]
What does a test of Piwigo 14 give? We've made many changes to be more compatible with PHP 8.x

**Comment by BarryTice** [comment]
My Piwigo tells me I am currently running version 13.8.0, which it then says is the latest version. If there's a version 14 available, it's not obvious to me how to get it.

**Comment by osworx** [comment]
@BarryTice You can get the latest version here: https://piwigo.org/forum/viewtopic.php?id=33105
Be informed, this release is currently in a beta stadium (v.3) - but as far as I can see, quite stable.
