### ISSUE TITLE
[14.0.3pre] Search menu & icons / search by date (translating)

### ISSUE THREAD

**Issue by osworx** [Piwigo/Piwigo#2000]
Current display is (very) strange.

1. When hoovering the search menu, icons are hiden - width of the whole menu is flickering (see video).

https://github.com/Piwigo/Piwigo/assets/1905204/4878823f-0791-4a24-8060-ac557b93357b

2. Searching by date will not let me to translate the items (see image):

![piwigo_1403pre_search_by_date](https://github.com/Piwigo/Piwigo/assets/1905204/95143110-7399-4ac0-8b11-76cc1ef624e3)

**Comment by plegall** [comment]
what modus "skin" are you using?

**Comment by plegall** [comment]
You need to be sure you have the "git updated master" version of theme Modus.

**Comment by osworx** [comment]
> what modus "skin" are you using?

The one which is already embedded in the Piwigo package ..
Did'nt know that there is another package for it > that should be mentioned somewhere!

**Comment by plegall** [comment]
If you use the downloadable Piwigo 14.0.0beta3, then the embedded Modus theme is the right version.

If you use the git master branch of Piwigo, then make sure you're also using the git master branch of modus.

**Comment by osworx** [comment]
Okay, thx for clarification.
Used the GH repo of the latest beta version ..
