### ISSUE TITLE
: Attempt to read property "value" on null in

### ISSUE THREAD

**Issue by crisleipnitz** [Piwigo/Piwigo#2004]
Hi, all. Can you help me with this issue:

/config/www/_data/templates_c/1uyas8y_rafr8z^51f34276967318fc82694b733f6652fbc085696f_0.file.header.tpl.php on line
109

Warning
: Attempt to read property "value" on null in
/config/www/_data/templates_c/1uyas8y_rafr8z^51f34276967318fc82694b733f6652fbc085696f_0.file.header.tpl.php
on line
109

">

**Comment by osworx** [comment]
Could you post which versions of Piwigo and php you are using?

**Comment by crisleipnitz** [comment]
[Piwigo 14.0.0.beta3]
Using this docker img: https://hub.docker.com/r/linuxserver/piwigo

**Comment by crisleipnitz** [comment]
Tag 13.8.0

**Comment by crisleipnitz** [comment]
PHP: 8.1.22

**Comment by osworx** [comment]
Unfortunetaly are there several uninitialized variables through the whole system.
Guess (without closer checking that file) one of those bugs.
The core devs of Piwigo should check that an fix.

**Comment by osworx** [comment]
Sorry, tried to help you (soving that bug is easy), but my installation (got it from here: https://piwigo.org/forum/viewtopic.php?id=33105) has less lines.
Therefore I don't know what your lin 109 contains.
Maybe post it here or open a new thread in the piwigo forum: https://piwigo.org/forum/viewforum.php?id=8

**Comment by crisleipnitz** [comment]
The line is not always the same. For now, the message I got is:

/config/www/_data/templates_c/rr6dxn_rafr8z^afffd7bc43f1f2b35d1815b0cc89de72f825b1df_0.file.header.tpl.php on line 63

Warning: Attempt to read property "value" on null in /config/www/_data/templates_c/rr6dxn_rafr8z^afffd7bc43f1f2b35d1815b0cc89de72f825b1df_0.file.header.tpl.php on line 63
">

**Comment by erAck** [comment]
You have to open that file and look in the header comment what source template file actually generated the file. It might not even be Piwigo core but some plugin.

**Comment by osworx** [comment]
Correct what @erAck said.
Not only the error/warning message is the important part, also that mentioned line.

And if the line is changing, it seems that a plugin is changing that file.
Can be easely tested wehn you disable all plugins and perfom the same action - repeat that by enabling the plugins one by one.
Once you should then know which cause this error - then a help is possible.

**Comment by crisleipnitz** [comment]
Guys, problem solved. The Meta Plugin caused this error. I had to disable all the plugins to find it out. I appreciate your help and want to thank you for taking a moment on this.
