### ISSUE TITLE
Minimum reqirements for Piwigo

### ISSUE THREAD

**Issue by Wernfried** [Piwigo/Piwigo#2013]
In your requirements it says:

- PHP 5.3 or greater (7+ recommended)

Is this still true? I consider to contribute to this project, mainly the SQL related part. PHP 5.3 is ancient, and even version 7 is "end of life". Do I really have to make my code working for PHP version 5.3?
 
If yes, then I will refuse my plans contributing to this project.

Kind Regards
Wernfried

**Comment by osworx** [comment]
Would like to know the same.

5.3 ended 9 years ago!
Nowadays 7.x (7.4 ended 1 year ago!) should be the minimum.
But developing new plugins/modules/etc. should be done in mind of php 8.2 where support will end in 2 years ..

**Comment by plegall** [comment]
We're going to remove 5.x on the website. It is already 7.0 in include/constants.inc.php

I don't see the PHP end-of-life the same way as official releases. I see it as "which version of PHP are provided by Debian official versions". Debian 12, just released, is the very one to provide PHP 8 (8.2 to be specific). Debian 11 provides PHP 7.3.

It is simply deconnected from reality to require PHP 8 for now. Everybody can't update to Debian 12 as quickly as we would like.

**Comment by plegall** [comment]
from wordpress statistics 

![image](https://github.com/Piwigo/Piwigo/assets/9326959/1cb1331f-bf74-42c9-83d2-7f4dc64b3cbb)

**Comment by osworx** [comment]
Means the majority ( 79,51 % ) use php >= 7.4 (up to 8.2.x).

Saying at https://github.com/Piwigo/Piwigo#requirements that 
**PHP 5.3 or greater (7+ recommended)**

leads to the opinion, that 5.3 (or general 5.4) maybe good to use.
php 5.x has serious security leaks.
Beside this, the performance between 5.5 > 7.x is approx. 27%
Compared 7.x to 8.x, the perfomance is again approx. 20% better.

Not to speak about security.

**Everyone who use php 5.x does not know what he is doing.
And act irresponsible.**

And hoster/provider which offering php 5.x should be avoided.

Why do you think are all great(er) providers going over to php 8.x?

I would recommend to state that at least the **minimum should be php 7.x**
_Recommended php 7.4_
### But best option to use php 8.x

That' a clear statement to all, and devs are knowing how to develope.

**Comment by osworx** [comment]
Thanks, very good.
