### ISSUE TITLE
Error in functions_search.inc.php

### ISSUE THREAD

**Issue by ibaib** [Piwigo/Piwigo#2030]
Piwigo 13.8.0
Apache 2.4
PHP 8.0
MariaDB 10

When performing search ONLY "tags" selected, following error appears:

_**Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /Sites/piwigo/include/functions_search.inc.php:78 
Stack trace: 
#0 /Sites/piwigo/include/functions_search.inc.php(235): get_sql_search_clause(Array) 
#1 /Sites/piwigo/include/functions_search.inc.php(1499): get_regular_search_results(Array, '') 
#2 /Sites/piwigo/include/section_init.inc.php(364): get_search_results('46', NULL) 
#3 /Sites/piwigo/index.php(12): include('/volume1/web/pi...') 
#4 {main} thrown in /Sites/piwigo/include/functions_search.inc.php on line 78**_

Please find attached search page capture:

<img width="894" alt="Search_page_capture" src="https://github.com/Piwigo/Piwigo/assets/47954029/2e65919a-b26d-402a-8451-abd002511d21">

**Comment by klaoun** [comment]
Hello
Which theme ?

**Comment by ibaib** [comment]
Bootstrap Darkroom

**Comment by plegall** [comment]
I indeed reproduce this bug on Piwigo 13. I don't reproduce the same bug on Piwigo 14 but I've found other problems that I fixed in https://github.com/Piwigo/Piwigo/commit/13ea43e2efb562cec78a45657399361c7391130f

We won't fix Piwigo 13. This bug is too minor and search engine comes quite modified in Piwigo 14.

**Comment by ibaib** [comment]
Then I will have to wait, because it is impossible for me to install version 14 beta 3, because when I install it I get the following message:

_Array ( [0] => Access denied for user 'piwigo'@'localhost' (using password: YES) )_

Indeed I enter the correct password, and the process is successful, since I can install version 13.8.0 perfectly following the same procedure.

Thanks
