### ISSUE TITLE
Make compatible Maintenance

### ISSUE THREAD

**Issue by klaoun** [Piwigo/Piwigo#2038]
hello
![maint](https://github.com/Piwigo/Piwigo/assets/36087587/42f36c35-6f13-45cc-acd3-1a3be4399902)
PHP Warning:  Undefined array key "Optimal" in .maintenance_actions.tpl.php on line 334

**Comment by plegall** [comment]
Hi @klaoun 

On which version of Piwigo?

**Comment by klaoun** [comment]
Hi @plegall 
piwigo version beta 3 or from November 7

**Comment by plegall** [comment]
@klaoun can you make a new test on 14.0.0RC1 ? we have fixed many of those error/warning messages

**Comment by plegall** [comment]
@klaoun I'm sorry but I can't reproduce. I close this issue (we will reopen it if you can bring more details and I can reproduce)
