### ISSUE TITLE
API returned-page URL warning

### ISSUE THREAD

**Issue by grantiago** [Piwigo/Piwigo#2052]
Hi I've been working with the API to fetch some images for another web app. Works great for my needs. 
I am seeing a small error in the page URL generated by the API. 

Piwigo 13.8.0  
Installed on 7 May 2022, 1 year 6 months 3 weeks 1 day ago 
Operating system: Linux 
PHP: 8.1.25 (Show info) [2023-11-29 19:02:30] 
MySQL: 8.0.35-0ubuntu0.20.04.1 [2023-11-29 19:02:30] 
Graphics Library: ImageMagick 6.9.10-23

`var tag = 'whatever';`

The URL generated by
`//piwi.lan/ws.php?format=json&method=pwg.tags.getImages&tag_name=${tag}`

```
{
"stat": "ok",
"result": {
"paging": {
"page": 0,
"per_page": 100,
"count": 2,
"total_count": 2
},
"images": [
{
"rank": 0,
"is_favorite": false,
"id": 11,
"width": 1280,
"height": 793,
"hit": 1,
"file": "inverted.jpg",
"name": "inverted",
"comment": null,
"date_creation": null,
"date_available": "2023-11-24 11:14:54",
"page_url": "http://piwi.lan/picture.php?/11",
...
```
```
"page_url": "https://piwi.lan/picture.php?/11"
"page_url": "http://piwi.lan/picture.php?/11"
```
both give the error: 

```
Deprecated: strncmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /www/piwi/public_html/include/functions_url.inc.php on line 447

Warning: Cannot modify header information - headers already sent by (output started at /www/piwi/public_html/include/functions_url.inc.php:447) in /mnt/tera/www/piwi/public_html/include/page_header.php on line 99
```

If I use the navigation arrow to go up the the album view. the url is 
`http://piwi.lan/index.php?/categories/flat` -- no error
Then click to return to the photo the url is:
`http://piwi.lan/picture.php?/11/categories` -- no error
if I edit the url to `https://piwi.lan/picture.php?/11/` -- no error.

persists in rc 14
Piwigo 14.0.0RC1  
Installed on 23 November 2023, 6 days ago 
Operating system: Linux 
PHP: 8.1.25 (Show info) [2023-11-29 18:58:30] 
MySQL: 8.0.35-0ubuntu0.20.04.1 [2023-11-29 18:58:30] 
Graphics Library: ImageMagick 6.9.10-23

**Comment by klaoun** [comment]
Hello
Do you have test and try with piwigo 14rc2
And no plugins
Thanks

**Comment by plegall** [comment]
I don't reproduce this problem :-/ In both 13.8.0 and 14.0.0RC2

**Comment by grantiago** [comment]
The problem does not occur on my production server.
Piwigo 13.6.0
**PHP: 8.1.20**

I was mistaken. It is not occurring on the RC01 on my dev server. 

Still occurring on 13.8.0 on my dev server: 
**PHP: 8.1.25**

And I did a quick install of 14 RC2. Not there either. 

I thought it might be a hidden bug in the API since I don't see a lot of API activity in the forums. 

It was an easy fix in the javascript. 
`anchorElement.href = pageUrl + '/';`

I'll mark this as closed. Sorry for the confusion.
