### ISSUE TITLE
Database upgrade via command line

### ISSUE THREAD

**Issue by nebulade** [Piwigo/Piwigo#2063]
Hi, I was just looking into updating the Cloudron Piwigo package to 14. Firstly, thanks for the great release :)
So once the code is updated, it will present the upgrade.php page in the browser, which asks for admin credentials to submit that form to run the database migration as I understand. In our case the app is updated automatically on behalf of the user, so unless the database migration is run automatically other users will incur some downtime until the admin gets to it. Is there any way this could also be run on the server itself via some commandline?

**Comment by plegall** [comment]
You mean "without providing credentials", the answer is no. There is no "command line only" tool in Piwigo, that would require no authentication.

**Comment by nebulade** [comment]
Thanks for the quick answer. Looks like we have to then wait for the admin of that app to come online to perform that step then and accept the potential downtime for other users.
