### ISSUE TITLE
Batch Manager: Trying to run action on all items leads to "Hacking attempt" error

### ISSUE THREAD

**Issue by akuropka** [Piwigo/Piwigo#2079]
```
Server environment:
    Piwigo: 14.0.0
    Operating Systen: WINNT
    PHP: 8.1.28-dev
    MySQL: 11.4.0-MariaDB
    Image library: ImageMagick 7.1.1-23
   
Plugins active:
    LocalFiles Editor
    OpenStreetMap
    Security Headers
    VideoJS
```
**How to reproduce:**
Go to Photos > Batch Manager, select "All" as filter, update the set, select the whole set and go for thumbnail generation.

Shortly afterwards the following error is thrown:
> Piwigo ist auf einen nicht behebbaren Fehler gestoßen.
> 
> [Hacking attempt] the input parameter "whole_set" is not valid
> 
> #1	check_input_parameter C:\Inetpub\wwwroot\piwigo\admin\batch_manager_global.php(54)
> #2	include C:\Inetpub\wwwroot\piwigo\admin\batch_manager.php(814)
> #3	include C:\Inetpub\wwwroot\piwigo\admin.php(346)

Only entry in PIwigo log:
> [2023-12-27 12:43:02]	[DEBUG]	[admin/intro::299] recent activity calculated in 0.335 s

PHP log shows:
> [27-Dec-2023 12:40:25 Europe/Berlin] PHP Fatal error:  [Hacking attempt] the input parameter "whole_set" is not valid
> #1	check_input_parameter C:\Inetpub\wwwroot\piwigo\admin\batch_manager_global.php(54)
> #2	include C:\Inetpub\wwwroot\piwigo\admin\batch_manager.php(814)
> #3	include C:\Inetpub\wwwroot\piwigo\admin.php(346) in C:\Inetpub\wwwroot\piwigo\include\functions_html.inc.php on line 389

**Comment by plegall** [comment]
@akuropka can you give a try to version 14.1.0 and tell me if it works any better. I think it's going to be OK with the change I made on https://github.com/Piwigo/Piwigo/commit/79423022c850ef87d0ff4164620de3e51d6246e7 but I need you to confirm it also fixes the bug you reported.

**Comment by akuropka** [comment]
@plegall, bonjour!
I updated meanwhile to 14.1.0 (and PHP to 8.3.2) but issue remains the same. It happens only if really all items are selected.
Thank you for your attention!
Bonne Année!

**Comment by plegall** [comment]
I do not reproduce this bug :-/

How many photos do you have? Do you have more than one page of photos in the Batch Manager?

**Comment by akuropka** [comment]
At the moment there are 26990 photos over 1350 pages... I made a screencast below:
https://github.com/Piwigo/Piwigo/assets/22570574/e3cdacd0-f3c2-43c9-a452-86b346ff7bae

**Comment by plegall** [comment]
Very clear, thank you.

**Comment by plegall** [comment]
I've received another feedback and it fixes the issue.

@akuropka don't hesitate to reopen this issue or create another one if my fix doesn't work for you.

**Comment by akuropka** [comment]
@plegall, sorry for late response.
Applying the fix seems to work, will update once tested in detail.
Thank you for your support.

**Comment by akuropka** [comment]
@plegall,. after further testing I can confirm there's no further error coming up.

Showing and selecting the whole set of pictures goes very fast, however, after confirming the generation it first takes some minutes until the process even starts, generation then is comparatively slowly while speeding up towards the end.

Please refer to the timestamps in the log.

It's no issue for me since I use meanwhile the "since last import" option which works good.

[log_2024-02-26_60d885c3d8a5bddcb5586920125c3a6ac98d957d.txt](https://github.com/Piwigo/Piwigo/files/14403268/log_2024-02-26_60d885c3d8a5bddcb5586920125c3a6ac98d957d.txt)
