### ISSUE TITLE
No longer able to search by rating score.

### ISSUE THREAD

**Issue by mthompsonlxi** [Piwigo/Piwigo#2084]
Prior to Piwigo 14, I was about to run a search using "rating:>3" and it would return all the images that have a rating score greater than 3.

Since upgrading to 14 (and now 14.1) it will strip out the **:** and **>** characters and only return the images which have a rating of 3.

This ONLY effects the front end, running the name search in the Batch Manager returns all images with a rating above 3 (the normal behaviour)

Current version and activated plugins below.

![image](https://github.com/Piwigo/Piwigo/assets/25110257/736f7f2c-0649-4960-8687-6d632a5ef0bc)

**Comment by plegall** [comment]
Yes, that's right. We're going to add a new search filter on rating score but for now (14.1.0), you can't search by rating score.

**Comment by plegall** [comment]
see #2193
