### ISSUE TITLE
Search function error after upgrade from 13.8 to 14.1

### ISSUE THREAD

**Issue by kszwaba** [Piwigo/Piwigo#2087]
After upgrade from 13.8 to 14.1 when I try search function I got error
"Unknown column 'search_uuid' in 'where clause' SELECT COUNT(*) FROM piwigo_search WHERE search_uuid = 'psk-20240109-8txoOz4znJ' ; in /var/www/html/piwigo/include/dblayer/functions_mysqli.inc.php on line 847"
No errors in upgrade_feed.php (0 upgrades to apply)

Environment

Before updating

     Piwigo 13.8.0 Check for updates
     Installed April 8, 2023, 9 months/months 1 day ago
     Operating system: Linux (Debian GNU/Linux 11 (bullseye))
     PHP: 7.4.33 (Show info) [2024-01-09 22:21:56]
     MySQL: 5.5.5-10.5.18-MariaDB-0+deb11u1 [2024-01-09 22:21:56]
     Graphics Libraries: GD 2.3.0
     Cache size 2068.42 MB now Refresh

After updating

     Piwigo 14.1.0 Check for updates
     Installed April 8, 2023, 9 months/months 1 day ago
     Operating system: Linux
     PHP: 7.4.33 (Show info) [2024-01-09 22:28:05]
     MySQL: 5.5.5-10.5.18-MariaDB-0+deb11u1 [2024-01-09 22:28:05]
     Graphics Libraries: GD 2.3.0
     Cache size 2056.59 MB   calculated now Refresh

![search_error](https://github.com/Piwigo/Piwigo/assets/80651892/28e7069f-c0c7-4ffa-8566-390b9ea4a523)

**Comment by plegall** [comment]
Can you show us the structure of your table `piwigo_search` ?
And also, the latest lines in your table `piwigo_upgrade`?

**Comment by plegall** [comment]
For me it's an upgrade issue. Please run upgrade.php or see our upgrade guide https://piwigo.org/guides/update/manual

**Comment by kszwaba** [comment]
On Thu, 18 Jan 2024 03:04:59 -0800
Pierrick Le Gall ***@***.***> wrote:

> Can you show us the structure of your table `piwigo_search` ?
> And also, the latest lines in your table `piwigo_upgrade`?
> 

Hello Pierrick
Thank You for the update.
Sorry I didn't reply, but I've been very busy lately and haven't had
time to debug the problem in the database.

Regards
Chrisopher
