### ISSUE TITLE
New Search not available with Bootstrap Darkroom Theme

### ISSUE THREAD

**Issue by jheinitz** [Piwigo/Piwigo#2090]
Hello,

I'm using the Bootstrap Darkroom theme for my [gallery](https://sandbox.seboto.de/). I read about the new search engine which was introduced with version 14 and I was wondering why it is not available on my page. I tried to switch to the **Modus** theme and then it appears, but I'm not able to make it visible using the **Bootstrap Darkroom** theme.

Any ideas? Here is my setup and config:
```
Piwigo: 14.1.0
Installiert auf 4 Januar 2015, vor 9 Jahre 1 Woche 6 Tage
Betriebssystem: Linux
PHP: 7.4.33
MySQL: 5.5.5-10.6.5-MariaDB-1:10.6.5+maria~focal
Grafikbibliothek: GD 2.3.0
Größe des Cache 301.08 Mo   berechnet vor 1 Woche

Plugins:
Additional Pages
Admin Tools
Advanced Menu Manager
Batch Downloader
Batch Manager Prefilters
Batch Manager, Description
BBCode Bar
Charlie's content 3.2.4a
Comments Blacklist
Comments on Albums
Community
Contact Form
Cookie Consent
Crypto Captcha
Download by Size
Download Counter
Evil_Blog
Extended Description
Force HTTPS
Grum Plugins Classes.3
GuestBook
Header Manager
Language Switch
LocalFiles Editor
Manage Properties Photos
OpenStreetMap
Perso About
Perso Footer
Personal Favicon
PWG Stuffs
Rotate Image
SmartAlbums
Smilies Support
Statistics
Stop Spammers
Subscribe To Comments
User Collections
User Tags
VideoJS
Write Metadata
```

Kind regards

Jens

**Comment by klaoun** [comment]
Hello
Bootstrap darkroom 2.5.18 ?

**Comment by jheinitz** [comment]
Not when I opened the issue ....

After upgrading, it works as expected. 

Sorry for the confusion, but maybe it helps other people.

Thanks and best regards

Jens
