### ISSUE TITLE
Unable to batch upload

### ISSUE THREAD

**Issue by macstrat** [Piwigo/Piwigo#2100]
Unable to batch upload files to piwigo hosted site via Remote-Sync. Errors given on all files are 

15:34:23.044 [Thread-4] INFO  o.p.r.api.sync.SyncDirectoryWalker - Uploading Dunkers_0053.jpeg in album with ID null
15:34:23.044 [Thread-4] ERROR o.p.r.api.sync.ConnectedWalker - Cannot upload an image without an album. Please move the image in a subfolder.

Additionally unable to upload via FTP as the documentation is out of date (Photos>Add>FTP+Sync does not exist anymore)

Version: 14.1.0

**Comment by plegall** [comment]
For the record, it's related to #1920 : we have added a new output parameter to API method `pwg.session.getStatus` and the Java code of PiwigoRemoteSync doesn't like, at all, when something new appears in the response. Not very flexible in my opinion...

**Comment by plegall** [comment]
@macstrat because you're a Piwigo.com client, specific information: this bug fix has been backported on your Piwigo. No need to wait for the 14.3.0

**Comment by macstrat** [comment]
> For the record, it's related to #1920 : we have added a new output parameter to API method `pwg.session.getStatus` and the Java code of PiwigoRemoteSync doesn't like, at all, when something new appears in the response. Not very flexible in my opinion...

Thank you for the quick fix. I would agree its not very flexable at all. The code is no longer maintained. Has Piwigo thought about forking the git and creating their own uploader?

**Comment by plegall** [comment]
> Has Piwigo thought about forking the git and creating their own uploader?

It's not the problem. Piwigo Remote Sync is already our code. I mean we can maintain it. We just don't have much people willing to work on it. But we will if we have to.
