### ISSUE TITLE
[Album Selector] albums full hierarchy

### ISSUE THREAD

**Issue by LintyDev** [Piwigo/Piwigo#2132]
![Capture d’écran 2024-03-08 à 16 03 50](https://github.com/Piwigo/Piwigo/assets/137212265/267d1f8d-f4c9-4340-bfe8-5166f39f9e1b)

![Capture d’écran 2024-03-08 à 16 04 24](https://github.com/Piwigo/Piwigo/assets/137212265/81b7e0b8-425c-4db9-8539-66f0f4c513c4)

**Comment by MaikelvanGorkom** [comment]
Will the searches for albums be the same?
Move to album  works completely different as the linked album when you edit a single image.
My prefference has the move to album way.

**Comment by LintyDev** [comment]
We have decided to export the new album selector to other pages such as: Photo editing, Album editing and the Batch manager unit. We have also improved the album selector by integrating an album creation mode (only for admin pages).

![Capture d’écran 2024-07-31 à 11 30 38](https://github.com/user-attachments/assets/a353f4fc-dfb5-466d-b26a-bffbd8c3f0b3)
![Capture d’écran 2024-07-31 à 11 31 07](https://github.com/user-attachments/assets/285da155-e709-4379-b472-7bde08351e92)
![Capture d’écran 2024-07-31 à 11 31 31](https://github.com/user-attachments/assets/76a10286-56f7-4bc9-9e28-60f4995b5cdf)
