### ISSUE TITLE
Error during update of library or album

### ISSUE THREAD

**Issue by teicors** [Piwigo/Piwigo#2152]
Hi,
after update to the latest version (from 14.3.0 to 14.4.0) when I try to sync or only a dir or a full album album, I get this error

Fatal error: Cannot redeclare strip_html_in_metadata() (previously declared in /home/user/public_html/photo/include/functions_metadata.inc.php:186) in /home/user/public_html/photo/include/functions_metadata.inc.php on line 186

But the library, subfolders and photo are published.

BR,
Angelo

**Comment by klaoun** [comment]
Hello
Try reupload this application zip
