### ISSUE TITLE
[Users] New user edit pop in

### ISSUE THREAD

**Issue by LintyDev** [Piwigo/Piwigo#2158]
We are currently updating the interface for the user edit pop-in to enhance usability and integrate additional features.

![new pop in user](https://github.com/Piwigo/Piwigo/assets/137212265/fdd179dc-adcd-4108-9039-5703ff76e775)

![Capture d’écran 2024-05-10 à 18 06 08](https://github.com/Piwigo/Piwigo/assets/137212265/0068708b-4efd-4912-97d0-8ee0082d81bc)

**Comment by klaoun** [comment]
![Capture d'écran 2024-06-13 013652](https://github.com/Piwigo/Piwigo/assets/36087587/fceb5d74-cc83-4c6a-86de-8b0e2bbf793f)

**Comment by klaoun** [comment]
hello

I think we should test with several webmaster statuses

> ![Capture d'écran 2024-06-13 013652](https://private-user-images.githubusercontent.com/36087587/339161134-fceb5d74-cc83-4c6a-86de-8b0e2bbf793f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MzQzMjcsIm5iZiI6MTcxODUzNDAyNywicGF0aCI6Ii8zNjA4NzU4Ny8zMzkxNjExMzQtZmNlYjVkNzQtY2M4My00YzZhLTg2ZGUtOGIwZTJiYmY3OTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDEwMzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZjM1N2QwYzk2ZmI3ZjJhMjFjOTU5YWQwMzE0MmViMTBjNzdkZDVmYzJhMzhkNmM1MjI2YWQxNTExNTI5YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ijxspiJ-ctkuRakI34er1xDzITGxAUZo4g7UpDGyXEs)
