### ISSUE TITLE
"Deprecated: addslashes()...." when syncing gallery

### ISSUE THREAD

**Issue by zetheroo** [Piwigo/Piwigo#2159]
Piwigo 14.4.0 (Truechart on TrueNAS SCALE)

When I sync thousands of photos, the sync page errors to repeating this message over and over:

`Deprecated: addslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /app/www/public/admin/include/functions_metadata.php on line 107`

Until it stops this this message:

`Fatal error: Maximum execution time of 30 seconds exceeded in /app/www/public/admin/include/functions_metadata.php on line 185`

**Comment by dvarrel** [comment]
you have got php 8.x ?

solve : `    $exif[$pwg_key] = addslashes($exif[$pwg_key] ?? '');`
