### ISSUE TITLE
Creating new user fails / Firefox - Strict mode

### ISSUE THREAD

**Issue by 7tonin** [Piwigo/Piwigo#2176]
Hi,
for a while now, under some circumstances like mine, creating a user fails. No error, the submit button seems asleep.
I have not dug to find why, but I suspect some problem with Firefox in strict mode. Sorry for being so loose.
This problem reminds me that hard time I had with https://github.com/Piwigo/Piwigo/issues/1296#issuecomment-772222380

**Comment by plegall** [comment]
Hi @7tonin can you test with the new version 15.0.0beta1 ? the user manager has received many changes.

**Comment by 7tonin** [comment]
Creating a user works fine with 15.0.0beta1. Great !
