### ISSUE TITLE
[search] filter by rating should be hidden when feature is disabled

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#2195]
When ratings are disabled (which is the default configuration), Piwigo should not list the filter by ratings in the gallery search.

**Comment by neehhaa06** [comment]
Hello @plegall 
Would you be able to explain the issue with this problem??
Thankyou!!

**Comment by plegall** [comment]
@neehhaa06 well, I re-read my original description and it means pretty understandable. Tell me what you don't understand so that I can provide details if necessary.

**Comment by flop25** [comment]
I saw that in my emails and I thought: is it possible to actually have disabled the action to rate but still display a rating and wanting that filter? Like getting rating from the metadata and it have a specific meaning like the rating from the owner...?

**Comment by plegall** [comment]
> Like getting rating from the metadata and it have a specific meaning like the rating from the owner...?

I understand the question because in software like Adobe Lightroom, there is a rating from the photographer. I have never seen a Piwigo importing the star rating from metadata (is it even stored in the IPTC metadata?) to its rating system. Never.

So for me, if rating is disabled, we should not have the rating filter in the search.

**Comment by HWFord** [comment]
closed with previous commit (not done automatically due to typo ##)
