### ISSUE TITLE
Photos uploaded by Remote Sync are orphaned but not shown

### ISSUE THREAD

**Issue by jradwan** [Piwigo/Piwigo#2204]
I was trying the Remote Sync tool (https://[piwigo.org/ext/index.php?eid=851](https://piwigo.org/ext/index.php?eid=851)) against my 15.0.0beta2 installation and although an album was created and the photos were uploaded (according to the log), the album appears empty and the photos are listed as orphans but are not actually displayed.

![image](https://github.com/user-attachments/assets/253b2846-e2f8-4e61-b086-3934b421563d)

![image](https://github.com/user-attachments/assets/4a07f1bf-c4bf-451b-b1cd-26e7a340b18d)

I've never use the Remote Sync tool before, and it doesn't look like it's been updated in a while (5 years?), so not sure if this is an issue with the tool or the v15 beta.

**Comment by plegall** [comment]
If you upload a photo on page [Administration > Photos > Add], does it solves the problem?

**Comment by jradwan** [comment]
Yes, adding photos via "Add" seems to work as expected. And if I purposely orphan a photo (unlink it from an album), it appears on the Orphans page properly. I just seems to be when using the Remote Sync tool.

**Comment by plegall** [comment]
In the following workflow:
1) you add photos with sync
2) you see them as orphans
3) you add 1 photo with upload form (of course this one is not orphan)
4) are the photos added by sync earlier still orphans?

**Comment by plegall** [comment]
I'll see if someone can work on https://github.com/Piwigo/Piwigo-Java/issues/26

For now I close this issue (as it is already described on the Piwigo Remote Sync repository)

**Comment by jradwan** [comment]
Ah, nice! Sorry, I didn't realize there was a separate repo for the sync tool.
