### ISSUE TITLE
Deprecated: Creation of dynamic property Inflector_en::$er2ing is deprecated in include/inflectors/en.php

### ISSUE THREAD

**Issue by shutterfreak** [Piwigo/Piwigo#2213]
I'm using Piwgo version 14.5.0 with PHP 8.2 and MySql 8.0 on an hosted environment.

Wien I tried to delete a number of files I uploaded by accident in a physical album by using Photos > Batch Manager, the following PHP errors were reported at the top of the page:

> Deprecated: Creation of dynamic property Inflector_en::$er2ing is deprecated in /home/user/gallery/include/inflectors/en.php on line 82
> Deprecated: Creation of dynamic property Inflector_en::$ing2er is deprecated in /home/user/gallery/include/inflectors/en.php on line 87

The affected lines in include/inflectors/en.php are:

```php
    $this->er2ing = array_reverse(array(
      '/ers?$/' => 'ing',
      '/(be|draw|liv)ers?$/' => '\0'
    ));

    $this->ing2er = array_reverse(array(
      '/ing$/' => 'er',
      '/(snow|rain)ing$/' => '\1',
      '/(th|hous|dur|spr|wedd)ing$/' => '\0',
      '/(liv|draw)ing$/' => '\0'
    ));
```

Apparently this relates to those properties not having been defined in the class: https://stackoverflow.com/questions/74878889/php-warning-deprecated-creation-of-dynamic-property-is-deprecated

**Comment by hugochinchilla** [comment]
Maybe the same change is needed in the fr inflector https://github.com/Piwigo/Piwigo/blob/master/include/inflectors/fr.php @LintyDev
