### ISSUE TITLE
Adding subalbum under unopened album results in not showing subalbum without refresh

### ISSUE THREAD

**Issue by MaikelvanGorkom** [Piwigo/Piwigo#2247]
Piwigo version: 15

When you select an album (example "test"), but not opening it (clicking on the >) and click on "add album" you can create a new sub album (example "test2") under the first album. But when you click on the ">" the sub albums aren't shown, not the new one, but also not the old ones. You have to refresh the complete page (F5). Then you see the sub albums, old and new.

**Comment by MaikelvanGorkom** [comment]
Have tested some further: If you create the first subalbum, the parent album is immediately opened after creating it, the second (and maybe 3rd etc) just doen't do anything.

**Comment by LintyDev** [comment]
Hello, I can't reproduce the problem, can you tell me if I'm reproducing what you do in the recording?


https://github.com/user-attachments/assets/7247d692-8c01-48b0-9518-84ee4e0ad20f

**Comment by MaikelvanGorkom** [comment]
After you create test5 do a refresh of the page. then open test, don't open test3 and create a new album in test3 called test6.

**Comment by LintyDev** [comment]
Ok, I see the problem, I'll fix the bug. Thanks for your feedback! 😃
