### ISSUE TITLE
 Activate icon "Photo sizes" 

### ISSUE THREAD

**Issue by catmurdock** [Piwigo/Piwigo#2248]
Hi,

when I uncheck  Activate icon "Photo sizes" from the settings page, the Photo sizes icon is still there.
i'm using piwigo to sell photo's to clients, disable download icon does work and I also using the watermark,
but when users simple selecting original the watermark is gone.

**Comment by catmurdock** [comment]
it is within the theme modus and tried things like editing the ccs but that is not working

**Comment by LintyDev** [comment]
Hello, I've just seen that this is a problem with the Modus theme. I've found a solution and fixed the problem! An update of the Modus theme will arrive soon.

Thanks for your feedback
