### ISSUE TITLE
SQL -error with 15.0.0

### ISSUE THREAD

**Issue by Jannie62** [Piwigo/Piwigo#2262]
After from 14.5.0 to 15.0.0 i see this after a click on one of the albums:
> Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC' at line 7 in include/dblayer/functions_mysqli.inc.php:132 Stack trace:
> 0 include/dblayer/functions_mysqli.inc.php(132): mysqli->query('\nSELECT DISTINC...')
> 1 include/dblayer/functions_mysqli.inc.php(888): pwg_query('\nSELECT DISTINC...')
> 2 include/section_init.inc.php(317): query2array('\nSELECT DISTINC...', NULL, 'image_id')
> 3 index.php(12): include('/var/www/client...')
> 4 {main} thrown in include/dblayer/functions_mysqli.inc.php on line 132

I use MySQL on a server with PHP 8.2

**Comment by plegall** [comment]
Can you edit this album in the administration, go to the "photos sort order" tab and change options?

**Comment by Jannie62** [comment]
Thank you for reply! This did the job. It's visible now

**Comment by Jannie62** [comment]
I close this ticket
