### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by winstoy** [Piwigo/Piwigo#2269]
When I am about to add a new plugin, a prompt box pops up
Chaged should be changed
![1730932698607](https://github.com/user-attachments/assets/4f0aad3d-70d7-453c-a490-96c14a5e8f1f)

**Comment by plegall** [comment]
On which version? I don't find this bug.

**Comment by winstoy** [comment]
15.0.0
This problem also existed in the previous version, because I found that this sentence was not translated. Yesterday I accidentally discovered that it might be a word error.

**Comment by winstoy** [comment]
piwigo\admin\themes\default\template\plugins_new.tpl

![1405d7ee99111ba387ec4c84f60c60be](https://github.com/user-attachments/assets/cf8bab09-98b8-4d07-bd7e-214bd3625033)
