### ISSUE TITLE
[15.2.0] Fatal error: Declaration of PwgSession::open must be compatible with SessionHandlerInterface::open

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#2296]
See https://piwigo.org/forum/viewtopic.php?id=34068
and also https://piwigo.org/forum/viewtopic.php?pid=191477#p191477

**Comment by prbt2016** [comment]
Hello ,

Getting the same above error thrown but with a fresh install on Centos7 with PHP 7.4.27 , MYSQL 5.6.46, Apache 2.2.34.

```
Fatal error: Declaration of PwgSession::open(string $path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $session_name) in /{{PATH}}/{{TO}}/{{PIWIGO}}/include/functions_session.inc.php on line 15 

```

Please fix. 

Regards.
