### ISSUE TITLE
[users & groups] User list Admin page: search

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#264]
**Reported by flop25 on 22 Jul 2014 19:47**

several things are wrong:
*it searches on recent period and users id
*usernames are case sensitive whereas emails or status are not
*the status &quot;User&quot; doesn&#039;t match
*can&#039;t search on Group (regression but I&#039;ve seen why on the code; seems tricky)
*the privacy levels match on the number only (tricky too)

**Additional information:** plg added just for being notif and because he did that, but feel free to unassign :)

[Piwigo Bugtracker #3102](http://piwigo.org/bugs/view.php?id=3102)

**Comment by plegall** [comment]
**Comment posted by plg on 22 Jul 2014 20:51**

I know we have a regression compared to Piwigo 2.5 on user filtering. I have to implement a smarter filtering.

**Comment by plegall** [comment]
**Comment posted by plg on 16 Feb 2015 13:50**

Once a good search/filter is implemented we can remove columns &quot;Privacy level&quot; and &quot;registration date&quot; from the list. They are not much useful and make the lines long and sometimes break the display (see #3204 )

**Comment by zorodimanche** [comment]
+1

**Comment by plegall** [comment]
Fixed with #1265
