### ISSUE TITLE
[albums] upload error not report to user with new HTML5 form

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#279]
**Reported by gnunux on 10 Oct 2014 20:27**

**Version:** 2.7.0

I&#039;ve some right problems in my last installation. I&#039;ve upload a photo with new HTML5 upload form. But, instead of seeing an error, the page freeze in progressbar page.

This form should report the error message (&#039;error during buffer directory creation&#039; here).

**Steps to reproduce:** chown -R root:root piwigo/upload
chmod -R 755 piwigo/upload

Upload a photo with new HTML5 form.

[Piwigo Bugtracker #3160](http://piwigo.org/bugs/view.php?id=3160)

**Comment by samwilson** [comment]
+1 to this, it took me a while to figure out that the `/upload/buffer` directory wasn't writable by the web server (because all others were, somehow).
