### ISSUE TITLE
[users & groups] [user manager] on Internet Explorer, bad position of the list

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#304]
**Reported by plg on 16 Feb 2015 13:01**

**Version:** 2.7.3

CSS issue, the list of users is after the menu, on the vertical scale.

[Piwigo Bugtracker #3204](http://piwigo.org/bugs/view.php?id=3204)

**Comment by plegall** [comment]
**Comment posted by plg on 16 Feb 2015 13:19**

Whatever I try, I always encounter the problem one way or another. Only with Internet Explorer.

Maybe an update of Datatables (to version 1.10) for Piwigo 2.8 will fix the problem !

With a redesign of the list (remove some columns), new filter system, the problem could also be fixed.

I change the target version to 2.8

**Comment by plegall** [comment]
**Comment posted by plg on 16 Feb 2015 13:48**

&quot;bAutoWidth&quot;:false is also a good option to use.

**Comment by plegall** [comment]
I change to 2.9 because I haven't implemented all changes I wanted for 2.8. In Piwigo 2.9 we will have a whole new version of Datatables https://github.com/Piwigo/Piwigo/issues/378

**Comment by plegall** [comment]
I've checkd on latest master ea7e6d76e6cbd37a80892a9eda00d5eba6a5f977 and the problem still occur on Internet Explore :-/

@tkuther I think you're better than me on CSS, can you take a look at this issue?

**Comment by tkuther** [comment]
The issue is that the dataTables table has an explicit `style="width: 1686px"` attribute in the DOM`, no matter what viewport size the browser window actually has.

IE messes up the rendering then as soon as the browser window is smaller than the table width. Works OK if it's larger (e.g. 1920px).

Adding something like this helps (maybe using jQuery
```
.dataTables_wrapper {
  -ms-overflow-y: scroll;
}
```
I don't know dataTables. How does it calculate the table width?

**Comment by plegall** [comment]
You've pushed in the right direction :-) I don't how how dataTables calculates the width but I disabled autoWidth and it seems much better now. What do you think?

**Comment by tkuther** [comment]
Maybe use flexible width instead, by adding `width="100%"` to the raw table.
See also https://datatables.net/examples/basic_init/flexible_width.html -> HTML

I guess autoWidth is unneeded then, too, because all it does is add style="width: 100%", but doesn't hurt either.

That makes IE happy, too.

**Comment by tkuther** [comment]
Uhm, nevermind my last comment, because your change behaves exactly the same already :)
