### ISSUE TITLE
[tags] Tags for parent album without images

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#316]
**Reported by JanisV on 3 Mar 2014 18:10**

**Version:** 2.6.1

Piwigo don&#039;t show tags for parent album without images. Only for albums with images. Will be great to show tags of sub-albums in their parent.

**Additional information:** Simple patch for improve this http://piwigo.org/forum/viewtopic.php?pid=150227

[Piwigo Bugtracker #3052](http://piwigo.org/bugs/view.php?id=3052)

**Comment by plegall** [comment]
**Comment posted by JanisV on 14 Oct 2014 14:34**

Implemented as personal plugin: http://piwigo.org/forum/viewtopic.php?id=24595

**Comment by plegall** [comment]
**Comment posted by flop25 on 14 Oct 2014 14:48**

i&#039;m just wondering about the perf when showing the root page

**Comment by flop25** [comment]
moving to https://github.com/Piwigo/Piwigo/issues/759
