### ISSUE TITLE
Quick search should propose album names

### ISSUE THREAD

**Issue by modus75** [Piwigo/Piwigo#343]
Propose album names in the quick search results (albums are fully ignored by the quick search in 2.7)

**Comment by plegall** [comment]
I fully agree with that :+1:

**Comment by plegall** [comment]
if the album description matches, also list the album in the search result

**Comment by plegall** [comment]
@modus75 do you think you will be able to it "soon"? (2.8 is not far)

**Comment by modus75** [comment]
Not for 2.8. I have to find several hours for this...

**Comment by wolf-box** [comment]
Guys, I'm silently watching this issue for over a year now and we are actually holding off a large migration from gallery2 since it's impossible to find any album name in piwigo. We are desperately waiting for this.

**Comment by modus75** [comment]
In the meantime you can try and use the rv autocomplete plug-in. It will
autocomplete the quick search box with album and tag names and allow direct
navigation to it

**Comment by plegall** [comment]
If @modus75 does not work on this issue, I will. Search is an important feature in Piwigo and we need to albums to be taken into account for search results.

**Comment by modus75** [comment]
I need to find some free time for this... Unfortunately I don't know when
this will be possible...

**Comment by plegall** [comment]
@modus75 please review/test before I merge :-)

I had an album "lorem really ipsum". If I search "lorem" or "ipsum", I find the album (match/against) but a search on "really" does not find the album! I suppose there is a list of excluded words for fulltext search.

**Comment by modus75** [comment]
Ok @plg
- in the new function there is still a reference to tag_id's instead of
cat_id's
- the 'category' scope is used but never added (the parser will not give
any consideration to category:toto)
- There should be some permission checking on the proposed album names.

**Comment by plegall** [comment]
thanks, I'm going to fix that. Not sure if I implement the scope yet (we can do that later)

**Comment by plegall** [comment]
https://github.com/Piwigo/Piwigo/commit/f0195903c2ba30931ce26819b1d8ca5d08b92a61 + https://github.com/Piwigo/Piwigo/commit/2ef52d20b5461f3f0b9342a40d149e038b33f982
