### ISSUE TITLE
API - need a method to rank multiple photos at once

### ISSUE THREAD

**Issue by vvinogradsky** [Piwigo/Piwigo#349]
pwg.images.setRank takes only one photo as an argument, which means the external application has to send a separate request for every photo in a gallery. With a high-latency connection and a large number of photos in the gallery, this causes a noticeable delay.
Please modify the call (or create a new call) to accept multiple photo IDs an array of image_id/rank pairs - this way all photos in a gallery can be re-ordered with just a single call.

**Comment by plegall** [comment]
@vvinogradsky in Piwigo 2.8 you will be able to send the full list of image_ids for a given category_id. Just give them in the appropriate order. If you provide image_id as a list, rank won't be used.
