### ISSUE TITLE
One-shot resize at upload

### ISSUE THREAD

**Issue by mistic100** [Piwigo/Piwigo#356]
I sometimes want to resize the original photos at upload time without changing the global setting in "Photo Size".

It would be nice to replicate the "Resize after upload" settings on the upload page but applied only to this set.

~~Also display a message when the resizing is configured globally~~ (already the case) + ability to disable it.

**Comment by plegall** [comment]
I'm going to reject this request :-/ We're trying to make the upload form as simple as possible, see the changes brought in Piwigo 2.10. Adding such advanced settings is not the way to go, in my opinion.
