### ISSUE TITLE
SERVER_NAME used on class.phpmailer.php

### ISSUE THREAD

**Issue by IGLOU-EU** [Piwigo/Piwigo#364]
Hi,

 `$_SERVER['SERVER_NAME']`, must return ` Server_Name XXX` provided by the server. But by default apache allows to return the `Host Header` ... `UseCanonicalName Off`

Apache escaped all HTML host value for `$_SERVER['SERVER_NAME']`, no probleme for XSS, but undesirable and dangerous for sql injections.

**Comment by mistic100** [comment]
Hi

nothing from phpMailer is used in SQL queries

you can submit the issue to https://github.com/PHPMailer/PHPMailer if you want but we won't alter the lib in Piwigo

**Comment by IGLOU-EU** [comment]
Ok sorry,
i close this issue !
