### ISSUE TITLE
upgrade datatables js

### ISSUE THREAD

**Issue by modus75** [Piwigo/Piwigo#378]
not very straightforward because api functions have changed names (no more hungarian notation)

need to do user list and rating users.

**Comment by plegall** [comment]
Yes, I saw yesterday (while implementing a dataTable for plugin Private Share) that API functions now have new (and better) names.

Please do it on a branch and I will handle the user list.

**Comment by modus75** [comment]
I saw it's backward compatible so I will wait until 2.8 is released and then commit it directly on master ...
