### ISSUE TITLE
Grading

### ISSUE THREAD

**Issue by Eothred** [Piwigo/Piwigo#381]
I was wondering if there is a minor issue with the grading system? I see e.g. "3.63 (1 review)" if I have myself put '3 stars' (or 4 out of 6 if you want, the first is 0). Shouldn't the average then be 3 and not 3.63?

Please mark this as minor, it is of very little importance but I thought it might also be a reasonably easy fix (or maybe I misunderstand something of course).

**Comment by plegall** [comment]
Hi @Eothred 

The rating score is much more complex than a simple "average". Read http://piwigo.org/releases/2.3.0#rating_score and if you like details http://piwigo.org/forum/viewtopic.php?id=17858

**Comment by Eothred** [comment]
Aah, and of course your explanation is very correct&clever as well! Completely agree about your logic :)
