### ISSUE TITLE
Write GPS location to image file

### ISSUE THREAD

**Issue by jheinitz** [Piwigo/Piwigo#382]
Hello,

I use the "Write Metadata" plugin to write description, author, tags etc to my image files into the corresponding IPTC fields. However using this plugin it is not possible to write the GPS location into the image. Is there an easy way to add this feature?

Kind regards

Jens
PS: Thanks for this cool software! Keep on going ...

**Comment by mistic100** [comment]
Please post this request on Write Metadata repository https://github.com/plegall/Piwigo-write_metadata
