### ISSUE TITLE
Button "delete this album and its content"

### ISSUE THREAD

**Issue by mistic100** [Piwigo/Piwigo#388]
http://fr.piwigo.org/forum/viewtopic.php?id=26535

In the albums manager, add a button "Delete this album and its content", it will open a confirmation dialog with a checkbox "Also delete items associated to other albums".

**Comment by plegall** [comment]
This is a duplicate for #153 (and I 100% agree, we should implement something simple for users instead of generating orphans, even if Piwigo 2.8 will highlight them)
