### ISSUE TITLE
keys for automatic authentication

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#392]
Like ?auth=12345abcde would automatically log you as "peter". Piwigo would be able to send such authentication keys in notification emails.

The key will be valid for just a few hours (configurable).

**Comment by mistic100** [comment]
You forgot to update the main structure script 
http://fr.piwigo.org/forum/viewtopic.php?id=26572

**Comment by eberkund** [comment]
I love when sites implement this feature

**Comment by plegall** [comment]
I close this issue, because released in 2.8.0RC1, and I created a new issue in #404
