### ISSUE TITLE
Question: How to participate in Beta-Test for 2.8?

### ISSUE THREAD

**Issue by jheinitz** [Piwigo/Piwigo#394]
Hello!

I'm using Piwigo for my personal picture gallery. I really like this piece of software. Thanks a lot. I starred the project on github.com and read through the mails coming in. I would like to know if it is possible to participate in beta testing the 2.8 release?

Can this be achieved by simply downloading the latest software repository?

Kind regards

Jens

**Comment by mistic100** [comment]
Hi,

yes you can just download the repo as well as the core plugins in their repos.
But we are not in beta test phase yet.

**Comment by plegall** [comment]
@jheinitz your tests are welcome :-) You can even look at pending pull-requests, test them and give your feedback.

Piwigo 2.8.0beta1 should come soon (I hope) but you can already test now :-)
