### ISSUE TITLE
missing style in emails

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#405]
Since I updated Smarty to version 3.1.28 (for compatibility with PHP 7), emails have lost their style.

**Comment by plegall** [comment]
This is certainly the same problem @mistic100 fixed in 9cc816d364057828cecc26dc1432448a57f261e9 and then in efbc08e537e26dde5f1bd98de4f8608ad6e81501

We have to fix it in the latest version of Smarty too.

**Comment by mistic100** [comment]
We should check what is the real impact of this and notify Smarty team.

**Comment by modus75** [comment]
The strip is intended for html where removing all white space is intended and desired. 
I used it first time for inlined javascript properly checking that it works. Others used it for css which is obviously broken.
I think that ideally :
- strip should work as initially designed
- we could add smarty blocks for minifying inline css and javascript based on css and js minifiers but this is going to be bad for performance (more php code loaded, lots of regex and js/css parsing would make the page be slower) ...

**Comment by plegall** [comment]
If the "problem" is only for "stripped" CSS in emails templates, then I think we would just drop the {strip} in email templates (themes/default/template/mail/text/html/*css*). Considering emogrifier will move CSS rules as inline attributes, there is no real utility to use {strip}.

**Comment by mistic100** [comment]
You are totally right. I think I added the {strip} tags in the early development of the new email templates, when I didn't know that webmailers require inline CSS.

**Comment by plegall** [comment]
OK, I reverted the change on Smarty and removed the {strip} instruction for email CSS. See branch bug/405-css-emails

My test goes fine, I have style in emails.
