### ISSUE TITLE
PHP7, Catchable fatal error: session_regenerate_id(): Failed to create(read) session ID

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#408]
http://piwigo.org/forum/viewtopic.php?id=26239

This is a PHP 7 bug, that should be fixed in version 7.0.3 (release date = 2016-02-07), see https://github.com/php/php-src/blob/PHP-7.0/NEWS#L70

**Comment by fcoiffie** [comment]
With PHP 7.0.3, the problem still occurs... (PHP 7.0.3-1~dotdeb+8.1 on Debian Jessie)

**Comment by plegall** [comment]
@fcoiffie thank you for this report

@nikrou also reported a problem with PHP 7.0.2 and proposed a fixed. Can you create a PR?

**Comment by nikrou** [comment]
Of course I can but I cannot already test with PHP 7.0.3

**Comment by plegall** [comment]
Unfortunately, even with fix from @nikrou, I still have error on PHP 7.0.3

Catchable fatal error: session_regenerate_id(): Failed to create(read) session ID: user (path: /var/lib/php/sessions) in .../include/functions_user.inc.php on line 953

I'm going to remove the 7.0.3 test.

**Comment by plegall** [comment]
@fcoiffie can you make a new try with https://github.com/Piwigo/Piwigo/commit/e71b61aee1b3e077899bb8276398f4c705586e51 ?

**Comment by fcoiffie** [comment]
I manually applied this patch on my Piwigo version and it works : no error. (But I can't say if it's safe...)

**Comment by plegall** [comment]
When session_regenerate_id() will be fixed on PHP 7, we will use it again.
