### ISSUE TITLE
[API] return list of photo sizes

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#416]
Following discussion with @mistic100 on https://github.com/Piwigo/Piwigo/commit/6af4590f01c7ea249c6d03b37fb1001ce96b7f4c#commitcomment-15854194 we should return the list of available sizes in pwg.session.getStatus

**Comment by modus75** [comment]
Quick question: because api results are structured, wouldn't be nicer to return an array of strings instead of a joined string ? (It would simplify double join/split) ...
(Not really important though - just a matter of principle)
