### ISSUE TITLE
Count views from mobile

### ISSUE THREAD

**Issue by Eothred** [Piwigo/Piwigo#426]
Not sure if this is by design or an issue, but I noticed that if I look through an album on my phone, the view count on the images are not increased.

In case the theme is relevant, I am using the 'smart pocket' one for mobile. In case I might have some other funny configuration which causes this, you are welcome to have a look at yngve.piwigo.com.

**Comment by plegall** [comment]
Hi @Eothred this is a very valid request (and we have the same "issue" with Fotorama for example)
