### ISSUE TITLE
Plugin "Edit Filename" does not rename the file on the disk

### ISSUE THREAD

**Issue by jheinitz** [Piwigo/Piwigo#433]
Hello,

I tried to rename some of my files in my gallery using the "Edit Filename" plugin, but I recognized that the file does not get renamed on the disk. I'm using Piwigo 2.7.4 on Ubuntu Linux using NGINX.

After pressing the "Save" button, I get no error and when I reload the picture, I can see that the filename is the one that I have set, but the file on the disk still has the old name.

I'm running the gallery in "German" and I also tried it with 2.8.0_RC2, same thing.

What am I doing wrong???

Best regards

Jens

**Comment by mistic100** [comment]
Hi

Sorry but this is the issue tracker for Piwigo only.
You can contact the author of the plugin on the forum or it's own issue tracker if he has one.
