### ISSUE TITLE
correct e-mail syntax not working

### ISSUE THREAD

**Issue by Eothred** [Piwigo/Piwigo#437]
I was trying to add a user to my web site, with e-mail on the form first.second.third@gmail.com. Piwigo claimed that the e-mail did not have the right syntax. Apologies that the text in screen shot is in Norwegian, but hopefully you can understand the issue.

![screen shot 2016-03-11 at 09 47 07](https://cloud.githubusercontent.com/assets/187567/13697579/8a0f17ee-e76e-11e5-981d-31314f8d35c2.png)

**Comment by mistic100** [comment]
Which version ?

**Comment by Eothred** [comment]
Sorry for adding info so quickly. I was wrongly assuming that the issue was that I there was a . in the mail (or maybe two, I already have users with one period before the @). However... Seems I do not get to add users regardless of how the e-mail address look like.

![screen shot 2016-03-11 at 09 51 13](https://cloud.githubusercontent.com/assets/187567/13697632/fa4b43f2-e76e-11e5-9c2d-86b69a89e4ec.png)

I have the "social connect" plugin enabled for Facebook and Google accounts. Could that be related perhaps?

**Comment by Eothred** [comment]
2.8, it is on piwigo.com

**Comment by mistic100** [comment]
no idea then.... emails verification using the standard PHP validator
https://github.com/Piwigo/Piwigo/blob/master/include/functions.inc.php#L2069

**Comment by plegall** [comment]
and if you add the user with a wrong email and then edit the user to change the email address?

**Comment by Eothred** [comment]
Hmm, now I am very confused. It is working perfectly again, but I did not change anything (other than closing the tab and opening a new one).

**Comment by Eothred** [comment]
Tried again now, and it all still works perfectly. I close this issue for now then and I suggest you rather reopen in case someone else manage to reproduce the issue. Maybe I followed a very specific set of clicks in order to trigger this issue.
