### ISSUE TITLE
[user manager] JSON data from server could not be parsed

### ISSUE THREAD

**Issue by ucodus** [Piwigo/Piwigo#446]
After Installation of the Version 2.8 this Error Message appears when starting the function User Management (.../admin.php?page=user_list).
At the moment the administration of existing users is not possible.

**Comment by plegall** [comment]
This problem certainly hides a deeper problem. Can you check the http request in the browser console and see what it is the error/warning message preventing javascript from parsing the list of users?

**Comment by ucodus** [comment]
Thanks for the quick answer. I´m not a web developer so i hope the following hardcopy is nearly what you need.

![consol](https://cloud.githubusercontent.com/assets/18014888/14041327/fb4689ea-f26f-11e5-9ebf-1ed631f1fd31.jpg)

**Comment by plegall** [comment]
No, it's not exactly what I need :-/ In the list of HTTP requests, you have selected o0939y.js file. What is actually interesting is the user_list_backend.php and in the right pane the "response" tab.

**Comment by ucodus** [comment]
Sorry for not understanding the first time. Here the contend of the "reponse" tab without the personal data. Ich hope they are not necessary for analysing the problem.

<br />
<b>Strict Standards</b>:  date(): We selected 'Europe/Berlin' for 'CET/1.0/no DST' instead in <b>/homepages/42/d316229954/htdocs/www.bilder.webservice-duesseldorf.de/include/common.inc.php</b> on line <b>134</b><br />
<br />
<b>Strict Standards</b>:  date(): We selected 'Europe/Berlin' for 'CET/1.0/no DST' instead in <b>/homepages/42/d316229954/htdocs/www.bilder.webservice-duesseldorf.de/include/common.inc.php</b> on line <b>134</b><br />
<br />
<b>Warning</b>:  session_start(): Cannot send session cache limiter - headers already sent (output started at /homepages/42/d316229954/htdocs/www.bilder.webservice-duesseldorf.de/include/common.inc.php:134) in <b>/homepages/42/d316229954/htdocs/www.bilder.webservice-duesseldorf.de/include/common.inc.php</b> on line <b>149</b><br />
{"sEcho":1,"iTotalRecords":"50","iTotalDisplayRecords":"50","aaData":[["1","uwe","Webmaster","uwe 
    *** Remarks: At this point are a lot of personel Data like Mailadress, Name and so on. I think it is better not to post this data***
 der","Freunde","2013-02-10 13:14:20"]]}

**Comment by plegall** [comment]
OK, so you have a problem with PHP setting on timezone, see http://piwigo.org/forum/viewtopic.php?pid=115421#p115421

**Comment by ucodus** [comment]
After Setting the Timezone to 
  <?php
     date_default_timezone_set('Europe/Berlin');
  ?>
the System works well. Thank your very very much !

**Comment by GuillaumeCale** [comment]
Hi, i have the same problem as original one. 

Timezone problem was resolved quickly with a php.ini file in the folder "piwigo" on 1and1 host.

But when I open the user managment page, I got the message : 

`DataTables warning: table id=userList - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`

The Php version is 5.6.30 (but my own private server got the same version and it works perfectly)

Please give me some help, i'm turning mad ;)
