### ISSUE TITLE
Url Upload via API?

### ISSUE THREAD

**Issue by kamijoutouma** [Piwigo/Piwigo#457]
I'm not really sure if im doing this right considering the server is returning s 405 error.
but

```
http://pic.ilp.moe/ws.php?format=json

    {
        "name": "http://static.tumblr.com/6f107309664ab5dbb2bcd4d1165353bd/tzdpqgk/lSgnypupw/tumblr_static_aev1my375zc4cwgsgcg4wc8so.png",
    }
```

I had assumed that the api had the ability to do url uploads. If it doesn't then i just had a wrench thrown in because thats really a deal breaker for me. I like the library but URL uploading is a must.

I saw that there was a plugin but i need an API plugin for this as well. since i need the api for my bot.

**Comment by kamijoutouma** [comment]
Oh nvm found it wish it had tag adding though.

**Comment by plegall** [comment]
how did you do? It would be a good idea to have this feature I think.

**Comment by kamijoutouma** [comment]
@plegall I did it from this https://github.com/mistic100/Piwigo-URL-Uploader However the plugin is a bit oudated (throws mysql errors because certain catches aren't in place) and needs a tag section (so that you can add tags immediatly to the upload via the api instead of calling an extra api or 2 to get the image id and set the tag.

**Comment by mistic100** [comment]
If there are errors in the plugin just tell it. Otherwise it will never be fixed.

**Comment by kamijoutouma** [comment]
@mistic100 i only noticed the this morning lol

**Comment by kamijoutouma** [comment]
Gonna close this now @plegall as the plugin has been updated however plans should be put in place for piwigo and this plugin to be merged @mistic100

**Comment by mistic100** [comment]
Why ? The design of Piwigo has always been to have a minimal core and many plugins. If I ever _totally_ drop development I will give the plugin to someone else (probably plegall) but I don't see why it "should" be merged. Many people do not care about this functionality.
