### ISSUE TITLE
windows 10 does not list *.jpg files

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#463]
when trying to select photos for upload, only *.jpe, *.png and *.gif

**Comment by plegall** [comment]
We need testers on this bug. I have encountered it on a specific laptop, not sure all Windows 10 users have it as well. @patdenice has not been able to reproduce it, for example.

**Comment by flop25** [comment]
can't reproduce on any win10 or win7 computers available for me

**Comment by jeremydurand** [comment]
It's not specific to Piwigo, Plupload knows also this problem.

https://github.com/moxiecode/plupload/issues/1270

**Comment by plegall** [comment]
Unfortunately we can't do anything on our side about it. I prefer to close the bug (but we keep it in our database of course)
