### ISSUE TITLE
Use https on piwigo.org

### ISSUE THREAD

**Issue by J0WI** [Piwigo/Piwigo#464]
Please force https on all Piwigo domains.

http is insecure and can be compromised: Links to download site could be manipulated, user data can be manipulated or stolen, logins can be hijacked...

You may be interested in CSP upgrade-insecure-requests for a quick and smooth migration.

**Comment by kamijoutouma** [comment]
I disagree with this. Sure there should be an OPTION to force https on piwigo in the admin control panel however blatantly just forcing https when not everyone has an ssl cert can cause issues. @J0WI

**Comment by J0WI** [comment]
@kamijoutouma I'm not sure if you understood me correctly. I'm refering to domains/hosts that are owned by Piwigo itself (eg. *.piwigo.org, *.piwigo.com, piwigo.es etc.).

**Comment by kamijoutouma** [comment]
@J0WI when you said "all Piwigo domains" i had assumed you meant "all domains that use piwigo's source code". But since that's not the case you should really place this on the forums instead of on github as this issue page is for the Piwigo image hosting source code and not the piwigo domain. @plegall

**Comment by plegall** [comment]
If the issue is about switching piwigo.org to HTTPS, then I reply that we're not at the right place to discuss about that :-) http://piwigo.org/forum/viewforum.php?id=28 is the right place.

**Comment by J0WI** [comment]
@plegall the cause why I posted it here is because I refuse to create an account only for this post.
And I also feel uncomfortable to do this on a site, that provide no secure login or contact form. ;)
Furthermore this also affect the security of Piwigo itself because of the scenario explained above with downloading from an insecure page.

So I hope you will address this issue of this anyway.

**Comment by plegall** [comment]
Well OK you're coherent ;-)

We have not planned to "fix" that "soon" but we will do it. Switching to HTTPS is not as easy as adding an SSL cert.
