### ISSUE TITLE
http redirect for forbidden guest access

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#476]
If $conf['guest_access'] is false, we'd better perform an http redirect and not an html redirect.

**Comment by modus75** [comment]
@plegall, Can you try this on as many browsers as possible ? I'm not sure all browsers follow the http header redirects if status code is 401 (the http protocol specify it for 3xx status codes but not for 401)

**Comment by plegall** [comment]
@modus75 you're right. I even think that the HTTP code automatically becomes 302 when redirecting. You can't have a redirect and code 401, it is not logical.

So I propose to set_status_header(401) only when we do no redirect (the first case of access_denied). Do you agree?

**Comment by modus75** [comment]
It's ok with me (because I don't use this case), but it's somehow strange to redirect in case of authorization error...

**Comment by plegall** [comment]
the idea behind guest_access=false is to force connection. Whatever the page the visitor tries to open, he is redirected to identification.php as long as he is not connected. Including the home page.
