### ISSUE TITLE
deactivate rating by default

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#496]
Rating is actually an advanced feature. Most of the time, this feature is not used at all. I would like it to be provided as a plugin, but it requires quite a lot of work. As a first step it would be good to deactivate rating by default (during installation I mean)

**Comment by flop25** [comment]
I would rather prefer options instead of migrating features on plugins. At least until we have a correct and browsable extension manager. But still with a perfect PEM, code fragmentation is a pending long term issue. I'm more an 'integrator'
Just my 2cents

**Comment by plegall** [comment]
For now, I just want this feature to be deactivated by default, nothing more.

On one side you say "I prefer an option [in Piwigo core]" and on the other side, you say "I'm more an integrator" which sounds to me like "I prefer choosing in a list of plugins".

In my opinion, some features can't be removed from core, like users or albums, but some features like rating or user comments can perfectly be moved in a plugin. Considering how little the rating feature is used, I'm convinced it must be deactivated by default (and I feel quite the same about user comments, but that would be another issue). On a technical point of view, I would prefer to have it outside Piwigo core, but it doesn't really hurt as it is currently.
