### ISSUE TITLE
Feature request: Max rows instead max photos

### ISSUE THREAD

**Issue by big-ant** [Piwigo/Piwigo#499]
Dear Contributors

I would like to have a config options where I could define a **max row per page** instead of **max pictures per page**. IMHO that would like much nicer, i.e. with the Modus theme.

Cheers
Roman

**Comment by flop25** [comment]
Hello
that's entirely theme-dependant; themes can and should have an admin page to manage such settings. But for responsive design that's kind of impossible to have such options

**Comment by big-ant** [comment]
Nothing is impossible ;) No, I see the point ...
