### ISSUE TITLE
Check mysql extension on install (for PHP7)

### ISSUE THREAD

**Issue by DrLuke** [Piwigo/Piwigo#515]
It seems that piwigo is making use of mysql_\* functions a lot. However, this has been deprecated in php7, and instead mysqli_\* is supposed to be used.

This prevents installation with php7, as it obviously fails to connect to the mysql database because the function mysql_connect() isn't defined.

**Comment by DrLuke** [comment]
Turns out that it falls back to mysql_* when mysqli isn't enabled, which was the case (I forgot to restart the php daemon). However, piwigo still shouldn't fall back to mysql_* when running on php7 anyhow.

**Comment by plegall** [comment]
OK @DrLuke so you suggest that we change https://github.com/Piwigo/Piwigo/blob/master/install.php#L136 to include additional check on PHP version : "die" if php_version>7 and mysqli not loaded.

**Comment by DrLuke** [comment]
It seems to be the correct. However I'm not a php developer, so take my opinion with some salt.
