### ISSUE TITLE
do not mark tag as orphan if new

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#537]
If you create a new tag, you immediately get a warning saying it is an orphan tag. Of course there is no photo associated to this tag, this is "obvious". We should not warn the user for this.

We could add a tags.created_on column and wait for at least1 day before warning the user.

**Comment by modus75** [comment]
Why not use the already existing lastmodified column?

**Comment by plegall** [comment]
You're right, that should be fine (but I'm preparing a new version of the tag manager and this column might be interesting)
