### ISSUE TITLE
Consider using InnoDB instead of MyISAM?

### ISSUE THREAD

**Issue by martinstefany** [Piwigo/Piwigo#539]
Hi,

isn't there an ongoing effort or discussion to switch from MyISAM engine to InnoDB? MyISAM is not really supported (considered "still experimental": https://mariadb.com/kb/en/mariadb/galera-cluster-system-variables/#wsrep_replicate_myisam) with Galera clustering, and since I've deployed Piwigo into MariaDB cluster, I had to mysqldump the initial DB, "fix" all create table statements from MyISAM to InnoDB and re-import the DB. It seems to work now, but I'm sure some more testing will be needed.

Thank you in advance.
Martin

**Comment by plegall** [comment]
Hi @martinstefany 

MyISAM has 2 advantages over InnoDB: performances on reads (what Piwigo does nearly all the time) and full-text search (used for quick search). InnoDB has full-text search only starting with MySQL 5.6.

Just to give an idea on how MySQL 5.6 is deployed : current Debian 8 (the stable version) is only MySQL 5.5!

So for now I would say it's still early to switch to InnoDB :-/

**Comment by plegall** [comment]
I close this issue, but it doesn't mean Piwigo won't make the move in the future. It's just "too early".
