### ISSUE TITLE
File Inclusion Attack

### ISSUE THREAD

**Issue by Shinkurt** [Piwigo/Piwigo#572]
Hello,

There is a File Inclusion attack in the file Piwigo/admin/batch_manager.php

It does:

```
600: $page['tab'] = 'global';  // if(isset($_GET)) else ,
596: $page['tab'] = $_GET['mode']; 
768: include (PHPWG_ROOT_PATH . 'admin/batch_manager_' . $page['tab'] . '.php');  // batch_manager_global.php
```
The user controlled variable $page['tab'] is being sent to an include() without no checks. this will create file inclusion attacks possible. in older php versions, using a nullbyte attack, a code execution is also possible. 

Fix: put an array of allowed strings.

Thanks,

**Comment by Shinkurt** [comment]
@plegall can we please get a CVE to this? thanks!

**Comment by plegall** [comment]
A CVE? I admit I've never filled any. When a security issue is reported, the reporter sometimes gives us a CVE.

In my opinion this security issue is really minor because it requires to be administrator.
