### ISSUE TITLE
Cross Site Scirpting #2

### ISSUE THREAD

**Issue by Shinkurt** [Piwigo/Piwigo#576]
In Piwigo/admin/site_update.php
```
46: $site_id = $_GET['site']; 
55: die ('site ' . $site_id . ' does not exist'); 
```
Unsanitized GET paramenter site is being sent to die() without no santization
Fix: use htmlentities();

Thanks,

**Comment by plegall** [comment]
Can you give us an example when it can be problematic?

**Comment by Shinkurt** [comment]
@plegall that code is equivallent to:
`die ('site ' . $_GET['site']; . ' does not exist'); `

Which can be used to perform XSS by sending parameters like:

http://localhost/tez.php?site=%3Csvg/onload=alert%28document.cookie%29%3E%3C/svg%3E

^ that will alert your cookies in Firefox.

Thanks,

**Comment by Shinkurt** [comment]
@plegall you can use htmlentities() on $site_id it will sanitize it. example:

46: $site_id = htmlentities($_GET['site'],ENT_QUOTES);

**Comment by plegall** [comment]
Thanks for your example.

Actually, in admin/site_update.php I find:

```
if (!is_numeric($_GET['site']))
{
  die ('site param missing or invalid');
}
$site_id = $_GET['site'];
```

is that not safe?
