### ISSUE TITLE
impossible to log on as admin

### ISSUE THREAD

**Issue by satyan01** [Piwigo/Piwigo#580]
Hello

how Can I reset my admin password  ? I have tried with md5 translation 

go to mysite/admin.php 

I am redirected to identification.php but my credentials don't work.

Help please

**Comment by plegall** [comment]
In your database, you can apply the SQL query:

```
update piwigo_users set password=md5('secret') where id=1;
```

Then you can use password "secret". Piwigo will automatically convert to a more secure hashing algorithm.

Warning: username and password are case-sensitive

**Comment by dr-coctor** [comment]
i have lost password etc but i have admin access to database and files on server in db i have some like this http://prntscr.com/imsqxc what i should do to restore admin credentials/password?
maby i doing some thing wrong but copy those query dont work im my case

**Comment by BlackH137** [comment]
Hi 

Our old administrator left.
I can log into the Linux PC that hosts the Files, but I do not have the username or password to log into the WebUI. is there a way to change or reset passwords on the server locally?

**Comment by in8sworld** [comment]
You'll need to follow the instructions above to reset the password in the database.  Look for phpmyadmin somewhere in the live web files folder.  If it doesn't exist you you can either set it up yourself (get ready to do some googling) or you'll have to use the terminal to run the update command against the mysql database.  

You can get phpmyadmin here: https://www.phpmyadmin.net/downloads/

If its already installed, you just point your browser to load up that location and it provides a nice GUI to modify data in your database no command line necessary.  Either way you still have to run the update command as given earlier in this thread:

```
update piwigo_users set password=md5('secret') where id=1;
```
