### ISSUE TITLE
Piwigo 2.8.3 session_start() - error with PHP 7.1 on Windows Server 2016 (IIS10)

### ISSUE THREAD

**Issue by mcinternet** [Piwigo/Piwigo#586]
Hello,

I cannot login on a fresh installation and on an older one I have a lot of problems regarding this error. With other application (like wordpress or others) there are no errors. So the problem must be in the piwigo. I am not a php-crack therefore I ask here to get help.

Error: Warning: session_start(): Failed to read session data: user (path: ) in ..... include\common.inc.php on line 149

The same is with a fresh piwigo 2.9b installation on line 156 - and there I cannot login.

kind regards

mcinternet

**Comment by mirlang** [comment]
same here, started  after upgrade to php-7.1

`Warning: session_start(): Failed to read session data: user (path: /tmp) in /var/www/default/gal/include/common.inc.php on line 156`

/tmp has proper permission

**Comment by mcinternet** [comment]
tmp / _data also has proper permissions

regards

**Comment by plegall** [comment]
Hi @mcinternet and @mirlang it sounds "a lot" like http://piwigo.org/forum/viewtopic.php?id=27103 where Zentalquabula seems to have found how it could be fixed.

**Comment by mirlang** [comment]
no time to register in the forum, but i tried rvelices' suggestion, works for me :)

```
diff --git a/include/functions_session.inc.php b/include/functions_session.inc.php
index e75f22e12..9d887355d 100644
--- a/include/functions_session.inc.php
+++ b/include/functions_session.inc.php
@@ -145,7 +145,7 @@ SELECT data
   WHERE id = \''.get_remote_addr_session_hash().$session_id.'\'
 ;';
   $result = pwg_query($query);
-  if ($result)
+  if (pwg_db_num_rows($result))
   {
     $row = pwg_db_fetch_assoc($result);
     return $row['data'];

```

**Comment by mcinternet** [comment]
That works for me - fine! Tanks!
No I have other two problems. During the error I created 2 new galeries. The have been created with errors and I cannot delete them.
2nd: in the user-account area is this error:
DataTables warning (table id = 'userList'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error.

Regards

**Comment by mcinternet** [comment]
AND: I cannot delete any galery

Regards

**Comment by mcinternet** [comment]
Now all seams to work!
My workaround: I deleted the DB-User and created a new one with all rights. Now it works!
best wishes 
kind regards

**Comment by paulD1968** [comment]
Had same issue after upgrading to 2.8.6 
Applying @mirlang  suggestion resolved my login issue. 
Login was going in a loop not capturing the credentials on server and redirecting to home page. 
All working now
