### ISSUE TITLE
[Batch Manager] delete photos by blocks

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#593]
Instead of trying to delete all selected photos "at once" on the form submission, Piwigo should delete photos by "blocks" of 100 photos (for example). It would make deletion of 5672 photos much more user friendly: less chance to fail, show a progression instead of a very long page to display.

**Comment by plegall** [comment]
@modus75 can you review before I merge on master?

**Comment by plegall** [comment]
It works fine on my dev environment. Tomorrow I will test on a Piwigo with tens of thousands of photos and try to delete several thousands photos.

**Comment by modus75** [comment]
@plegall looks fine except for the return from Web service (IMHO) because
success is useless (otherwise pwg error)
Just the details array should be fine (or the number of photos deleted as I
cannot see what else you could ever return)
