### ISSUE TITLE
Please update https://github.com/Piwigo/Piwigo/releases/latest

### ISSUE THREAD

**Issue by FanchTheSystem** [Piwigo/Piwigo#601]
As I use it to get current version to create piwigo package on archlinux.
`curl -Is https://github.com/Piwigo/Piwigo/releases/latest | awk -F'/' '/^Location/ {print $NF}' |  sed 's/[^[:print:]]//'`

**Comment by plegall** [comment]
done :-)

But I recommend you use http://piwigo.org/download/all_versions.php instead

**Comment by FanchTheSystem** [comment]
thanks ! (build script updated with your url)
