### ISSUE TITLE
replace include file='comment_list.tpl'

### ISSUE THREAD

**Issue by flop25** [Piwigo/Piwigo#603]
so comment_list can be replaced via template extension or extensions
No HTML changes just tpl and php

**Comment by flop25** [comment]
I have assigned this to 2.10 since the tpl code changed a bit 
awaiting CP

**Comment by plegall** [comment]
Can we have more details on this issue? Why do we need this change? What does it imply? Do themes and plugins developers need to know about this change?

**Comment by plegall** [comment]
OK @modus75 but at the beginning, @flop25 what does this issue tries to fix? Is there a problem with the `{include}` directive in Smarty? (I have no idea, I'm trying to understand the origin of this issue)

**Comment by flop25** [comment]
Hi Thx modus
Plg: Check the comment of my commit

**Comment by plegall** [comment]
OK, I get it :-)

**Comment by flop25** [comment]
Thank you for your hard work Have a good summer

**Comment by plegall** [comment]
I close this issue, it will be available starting with Piwigo 2.10.0. This change is detailed on documentation for theme developpers https://piwigo.org/doc/doku.php?id=dev:changes_in_2.10
