### ISSUE TITLE
Piwigo needs the short_open_tags directive to be On in php

### ISSUE THREAD

**Issue by goulou** [Piwigo/Piwigo#604]
I just spent 2 hours trying to make my gallery work (after moving server). I noticed at last that the source of the files provided by the server started with the following text : 
```
<?

ini_set('display_errors', 'On');
ini_set('log_errors', 'On');
#ini_set('error_log', PHPWG_ROOT_PATH . '/../piwigo-logs/error'.date(y-m-d).'.log'); 
error_reporting(E_ALL);
ini_set('error_log', PHPWG_ROOT_PATH . '/../piwigo-logs/error.log'); 


?>
```
This opened my eyes on the php configuration, and the "short_open_tags" directive was Off (while it was On on the old server).
Apparently, the gallery _almost_ works with this setting, but some of the client-side scripts seems to disfunction. Hence the upload page, together with some feature are buggy (if working at all...).

I don't know yet which part of piwigo uses the "<?" short tag, but I'm looking to it.

I definitely think that Piwigo should work with short_open_tags set to Off (or eventually put a note on the administration page).

**Comment by goulou** [comment]
After more investigations, I found that the file responsible for this code was local/config/config.inc.php
It contains the exact above-mentionned code. Should this be regarded as an issue?
I don't remember creating of modifying this file, but I may be wrong...

**Comment by plegall** [comment]
Hi @goulou file local/config/config.inc.php is not provided by Piwigo : it is a "local" file. Piwigo itself always use "<?php" tag, never "<?"

**Comment by goulou** [comment]
Well, I can imagine that...
I think the bug could be closed if you confirm that Piwigo did not create this file (in this installation or in any previous version).
I searched Google to find why and how I could have invented those lines, but it didn't find anything...

**Comment by flop25** [comment]
did you use an automatic script to install Piwigo?

**Comment by goulou** [comment]
I cannot remember, my installation is quite old now... Sorry...
When I did it, it was a conversion from a Menalto Gallery 3 instance, so if there was an automatic conversion script, I might very likely have used it.
