### ISSUE TITLE
Newest release constantly refreshes page

### ISSUE THREAD

**Issue by kde99** [Piwigo/Piwigo#608]
Hello!

I've just did a fresh install of piwigo (never used it before) on my pc and when I get to the admin panel it constantly refreshes. It always brings me back to "localhost/gallery/admin.php?page=album--permissions" (I installed it into a folder called gallery). If I stop the reloading then I click something it happens again and no matter what I do it always bring me back to the said URL. No buttons work (they all bring be back) also the left side menu blinks and expands then reloads the page. No error in log files or in the JS console. I also happens in both firefox and chrome. Also restarting the server or reinstalling doesn't do anything. What could cause this behavior? Also logging our or in again doesn't do anything.

**Comment by flop25** [comment]
Hello
did you launch a Tour from Take A Tour plugin?

**Comment by kde99** [comment]
@flop25 yes I did and I finished it. It wants to start again every time I go back to the main page. Should I select the "don't appear again"?

**Comment by flop25** [comment]
I don't get it: you took which tour?
As as stated in the first message, you can go to galerie/admin.php?page=plugin-TakeATour from the the menu or the direct url, to end instantly the Tour

**Comment by kde99** [comment]
@flop25 I choose a tour. The security one. Then completed it and it took the there.

**Comment by flop25** [comment]
ok I see, you don't have any album?

**Comment by kde99** [comment]
@flop25 Nope it's a new installation.

**Comment by flop25** [comment]
https://github.com/Piwigo/TakeATour/issues/4
