### ISSUE TITLE
JSON Error after updating to 2.8.6.

### ISSUE THREAD

**Issue by mcinternet** [Piwigo/Piwigo#609]
Hi, 
after updating to 2.8.6 I get an error when I use the user-manager
"DataTables warning (table id = 'userList'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error"

What´s wrong?

best regards
Jörg

**Comment by plegall** [comment]
We need more details because this is just the generic message when Piwigo displays an error in the ajax call.

With Firefox, right-click on the page and "inspect element". Then go to the "network" tab, refresh the page and click on the "user_list_backend.php" line, to see what is the exact output.

![piwigo-286-users-network-tool](https://cloud.githubusercontent.com/assets/9326959/22371861/02058d90-e49a-11e6-81b6-b5bbefdfb824.png)

**Comment by mcinternet** [comment]
![json1](https://cloud.githubusercontent.com/assets/7591544/22372026/f44d71a8-e49a-11e6-8f79-877780072c1d.JPG)
![json2](https://cloud.githubusercontent.com/assets/7591544/22372029/f846df7e-e49a-11e6-8f15-511f4da3e8dd.JPG)


And also in the topline (you see on pic1): 
Warning: session_start(): Failed to read session data: user (path: d:\session) in E:\db-webs\becker.pics\include\common.inc.php on line 149

best regards

Jörg

**Comment by plegall** [comment]
OK, so the important here is this warning "Warning: session_start()" it breaks the parsing for the user list. Fix this and your user list will come back.

What can be wrong with d:\session ?

**Comment by mcinternet** [comment]
The joke is: there is no drive d:\
and nothing shows to that

**Comment by flop25** [comment]
Hello
what is you environment? OS, server type, php version etc

**Comment by mcinternet** [comment]
This error was not before the update!
It is windows Server 2016 - IIS10

**Comment by flop25** [comment]
please also overwrite the file again with the 2.8.6 ones to be sure Or use Check Files Integrity

**Comment by mcinternet** [comment]
what file?

**Comment by flop25** [comment]
http://piwigo.org/forum/viewtopic.php?id=27637 https://github.com/Piwigo/Piwigo/issues/586

**Comment by mcinternet** [comment]
Don´t know what file it should be??? 
PS: It is PHP 7.1

**Comment by flop25** [comment]
Oh but you are the original posters of the issue 586!
Does your old workaround with the DB user recreation works again

**Comment by mcinternet** [comment]
I did, and now I have two errors!

Notice: Undefined variable: results in E:\db-webs\becker.pics\include\functions_session.inc.php on line 148

Notice: Trying to get property of non-object in E:\db-webs\becker.pics\include\dblayer\functions_mysqli.inc.php on line 216

**Comment by flop25** [comment]
those are just Notices but still they shouldn't appear. Is anything not operational?

**Comment by mcinternet** [comment]
The JSON Error see postings before

**Comment by flop25** [comment]
Yeah but the JSON Error happens when debug messages are displayed in the JSON respond so if you lower the level of Php error reporting, it shoudl work.
And your screen shot doesn't show the content of the JSON call but the content of the css file.

**Comment by mcinternet** [comment]
![json3](https://cloud.githubusercontent.com/assets/7591544/22372640/2582d9fe-e49e-11e6-93a9-452464e6b201.JPG)

**Comment by flop25** [comment]
> Then go to the "network" tab, refresh the page and click on the "user_list_backend.php" line, to see what is the exact output.

**Comment by mcinternet** [comment]
![json4](https://cloud.githubusercontent.com/assets/7591544/22372765/d2b3d01a-e49e-11e6-811d-4e8f70a6de87.JPG)

**Comment by flop25** [comment]
Almost there Now Antwort

**Comment by mcinternet** [comment]
whats that????? I did nothing and the error is away???????

**Comment by flop25** [comment]
I think that the clues points toward an instability of the server. Your installation might not be totally reliable especially the mysql server. Then maybe a caching issue maintains the error a little longer after it has been fixed. But by far I'm not the most skilled one from the team.
