### ISSUE TITLE
Support sort-direction for API call pwg.categories.getImages

### ISSUE THREAD

**Issue by samwilson** [Piwigo/Piwigo#613]
At the moment it's possible to order by id, file, name, hit, rating_score, date_creation, date_available, or random with the `pwg.categories.getImages` API call. It would be great to be able to reverse the direction of the sorting (with the exception of random).

So for example `https://example.org/ws.php?format=php&method=pwg.categories.getImages&order=date_creation&direction=desc` would give the most recently-created images (at the moment, without the direction sort option, it returns images *without any creation date* first).

**Comment by modus75** [comment]
you can fill the order parameter with "date_creation desc" to sort descending

**Comment by samwilson** [comment]
Thanks! I didn't see that in the documentation.
