### ISSUE TITLE
Video management

### ISSUE THREAD

**Issue by zorodimanche** [Piwigo/Piwigo#615]
Hi, piwigo allows to download pictures but it would also be interresant so that it also downloads videos.

**Comment by tkuther** [comment]
You don't see a download button when you're on a picture.php page that contains a video?
See for example https://pwgdemo.kuther.net/picture/18-samplevideo_1280x720_20mb/category/11-video

I don't think the button is theme dependent. At least I didn't add any code for the button, it's just there out-of-the-box.

**Comment by zorodimanche** [comment]
Hello thank you for your reaction I think I am wrongly expressed because I say download in the sense of sending a video from a computer to a server of heaviness and not the other way around.
And this from the user interface piwigo car allows only these types of files: jpg, jpeg, png, gif and it would be necessary to add mp4, flv ... without using plugins

**Comment by abrenoch** [comment]
@zorodimanche 

I would suggest using this plugin:
http://piwigo.org/ext/extension_view.php?eid=610

Works perfectly for me!

**Comment by tkuther** [comment]
You can add video file extension to local/config/config.php by extending $conf['file_ext']
