### ISSUE TITLE
extension update does not work

### ISSUE THREAD

**Issue by tessus** [Piwigo/Piwigo#623]
Piwigo tells me 'Some upgrades are available for extensions'. When I click the link I can see that there's an update for 'Bootstrap Default'. 1.0.5 -> 1.0.6.

After clicking install I get the popup message that it was updated successfully
(Update Complete
Bootstrap Default has been successfully updated.) and it says 'All extensions are up to date.'

But when I click on the admin home link, the same message appears again and eveything starts all over again.

Update: I don't know, if this is a piwigo or extension issue.

**Comment by ThomasDaheim** [comment]
Same thing happens here

**Comment by plegall** [comment]
It was fixed, it was a problem of version of this specific theme

**Comment by tessus** [comment]
@plegall I now get an error, if I click on _install_ or _update all_

<img width="306" alt="screen shot 2017-03-28 at 16 44 59" src="https://cloud.githubusercontent.com/assets/223439/24426530/e84cbaf2-13d5-11e7-9683-f1ec9e8a63a8.png">

**Comment by garz75** [comment]
I have the same issue with Piwigo 2.8.6. @plegall in which version has it been fixed ?
Thank you.

**Comment by flop25** [comment]
https://github.com/Piwigo/Piwigo/issues/655#issuecomment-294918150
