### ISSUE TITLE
related albums

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#626]
Like tags, it would be nice to have the ability to:

* combine several albums
* display the list of albums linked to the current photo set

Why would that be useful since tags seem to be appropriate? Because albums have a hierarchy, not tags. So we're filling a more complex need. It will make Piwigo an even better choice when organizing a large collection of photos with a Thesaurus.

**Comment by flop25** [comment]
I agree with that especially the second feature which is quite fundamental
when coming from a web search through the canonical url

Le 17 févr. 2017 10:17, "Pierrick Le Gall" <notifications@github.com> a
écrit :

**Comment by plegall** [comment]
> So, if I read it correctly.. subalbums could have multiple parent albums? Or did I misunderstand?

no, sorry you misunderstood, the feature is only about giving the possibility to the visitor to "combine albums" to filter a set of photos.

**Comment by DaoKakao** [comment]
This feature breaks pagination / navigation as through albums/categories, as through images in album.
When taking "old" code from 2.10 branch, everything's working.

PS I use nginx, and pagination don't work in all cases - when rewrites are on an off.

**Comment by plegall** [comment]
@DaoKakao yes, I already saw it and I have to work on it (obviously). Can you create a new issue for that please?
