### ISSUE TITLE
Piwigo loading speed

### ISSUE THREAD

**Issue by zorodimanche** [Piwigo/Piwigo#628]
Hello I found that piwigo takes longer to load than other script like zenphoto or koken. Would not it improve the speed of loading the script ?

**Comment by zorodimanche** [comment]
Two solutions to accelerate the load:
 - A caching plugin
 - A compression plugin for your images 

This will improve your SEO and your visitors will consult your content faster! You will not let them sink in front of their computer until your site loads;)

**Comment by flop25** [comment]
until a correct report is provided, this stays closed
