### ISSUE TITLE
"combined" folder occupies a lot of space on hosting

### ISSUE THREAD

**Issue by konservat0r** [Piwigo/Piwigo#629]
The "combined" folder occupies a lot of space on hosting - 2.63Gb. Although all my photos take only 200 megabytes

![screenshot-18feb2017-14 55 51](https://cloud.githubusercontent.com/assets/25728333/23093218/fa6f142e-f5ed-11e6-900a-77957032af97.png)

**Comment by flop25** [comment]
you can empty it
That's the combined css and js which are dynamically generated
Use cron job to empty it on a regular basis adapted to your website
