### ISSUE TITLE
ADVERTISING

### ISSUE THREAD

**Issue by zorodimanche** [Piwigo/Piwigo#631]
I have a PIWIGO gallery and I want to monetize my site to pay the fees (domane name, hosting, maintenance ...) but when I searched on piwigo.com there is no plugin to insert Ad site for google adsense. Can you integrate it into the development please to make my site live. Thank you

**Comment by flop25** [comment]
Hello
about your question : http://piwigo.org/ext/extension_view.php?eid=220 then custom theme/template etc
But please, search on our community forum before asking then ask there. http://piwigo.org/forum/
