### ISSUE TITLE
pLoader doesn't support https

### ISSUE THREAD

**Issue by habakuk007** [Piwigo/Piwigo#645]
pLoader does not support sites that use https (and every site that uses logins should use https....)

**Comment by plegall** [comment]
pLoader is no longer maintained (last release 7 years ago). It won't be updated as far as I can see.

Use Piwigo web upload form instead.

**Comment by habakuk007** [comment]
The html uploader in the admin area is very nice, but I need user upload...

And the community plugin doesn't work as well (flash doesn't exist any longer, html form has a poor usability & cannot be used with /$conf['question_mark_in_urls'] = false;/)...

**Comment by plegall** [comment]
OK, I understand the problem with Community upload form. We have to fix that.
