### ISSUE TITLE
Add functionality for multi-language support.

### ISSUE THREAD

**Issue by zorodimanche** [Piwigo/Piwigo#652]
I open this post because Piwigo lacks an essential functionality, that of allow users to translate the tags, titles of photos and their descriptions.
Indeed the software is multilingual so it is paradoxical that this is not integrated.

**Comment by plegall** [comment]
activate plugin Extended Description, then you can use [lang=default]hello[/lang][lang=fr]bonjour[/lang]. It can be used nearly anywhere.

**Comment by zorodimanche** [comment]
Hello @plegall  thank you for your reply. I want to know if this could not be integrated directly into the kernel without going through plugins because it's complicated.

**Comment by plegall** [comment]
activating a plugin is complicated? come on :-) it's just a matter of clicks on the plugin manager!

What may be complicated is to know all what Piwigo can do thanks to plugins. But if all plugins were integrated into Piwigo core (or kernel), it would make Piwigo over featured! We have to make some choices and multiple language for user labels is not one of them.

**Comment by zorodimanche** [comment]
Ok I understand

**Comment by zorodimanche** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/25553946/26014617/9e18b534-375d-11e7-825c-cf297fdea6bb.png)
