### ISSUE TITLE
extension update does not work #623

### ISSUE THREAD

**Issue by J-Kendrick** [Piwigo/Piwigo#655]
Fault is closed but the same problem persists
(Bootstrap default v1.0.5 - 1.0.6)

_Piwigo tells me 'Some upgrades are available for extensions'. When I click the link I can see that there's an update for 'Bootstrap Default'. 1.0.5 -> 1.0.6.

After clicking install I get the popup message that it was updated successfully
(Update Complete
Bootstrap Default has been successfully updated.) and it says 'All extensions are up to date.'

But when I click on the admin home link, the same message appears again and eveything starts all over again._

**Comment by flop25** [comment]
not a bug and not from Piwigo And please don't open a new issuer while there is already one ; the extension labels itself with a wrong version. I already submitted a PR to its git

**Comment by J-Kendrick** [comment]
But I still get the recurring message when Bootstrap default theme isn't installed!
  ----- Original Message -----
