### ISSUE TITLE
Why picture_coi change derivative_url_style?

### ISSUE THREAD

**Issue by joshuaavalon** [Piwigo/Piwigo#659]
In `picture_coi.php`,  row 70
```
  if ($conf['derivative_url_style']==1)
  {
    $conf['derivative_url_style']=0; //auto
  }
```
Why would it changes derivative_url_style to 0?

**Comment by modus75** [comment]
In order to force reloading the image after coi change (coi is not part of
the url)

**Comment by joshuaavalon** [comment]
I was thinking the same at first but after I removed those line and the image still reloaded.

**Comment by modus75** [comment]
This depends on your Apache/nginx configuration and if there is none on the
browser heuristics to refresh the cache

**Comment by joshuaavalon** [comment]
Thx, for the quick reply
