### ISSUE TITLE
Advanced Menu Manager broken on Php7

### ISSUE THREAD

**Issue by PrismSub7** [Piwigo/Piwigo#665]
From: https://wp.peters-webcorner.de/2017/01/piwigo-umstellung-auf-php7/

Changing Piwigo to PHP7 is actually problem-free. If this was not a plugin: Advanced Menu Manager. Depending on the configuration of the web server you can see warnings on the page.

The logfile then reads:

[Fri xxx xx 16:xx:xx.914143 2017] [:error] [pid xxxxx] [client xxxx] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; AMM_AIM has a deprecated constructor in /xx/xx/xx/plugins/AMenuManager/amm_aim.class.inc.php on line 20, referer: https://xx.xx.xx/

We are looking for the folder plugins / AMenuManager in our Piwigo installation. There are two files with the names amm_pip.class.inc.php and amm_aim.class.inc.php.

Change 1: amm_pip.class.inc.php, line 19

Original: function AMM_PIP($prefixeTable, $filelocation)
Replace with: public function __construct($prefixeTable, $filelocation)

Change 2: amm_aim.class.inc.php, line 20

Original:  function AMM_AIM($prefixeTable, $filelocation)
Replace with: public function __construct($prefixeTable, $filelocation)

**Comment by modus75** [comment]
That's a plugin
