### ISSUE TITLE
Filter by file type

### ISSUE THREAD

**Issue by youssefelmourabit** [Piwigo/Piwigo#666]
Add a plugin that sort the contents by file type: eg "Image" show only jpeg, png "Video" files only mp4, avi, flv ... "GIF" only gif files.
Thank you 
View the forum : http://fr.piwigo.org/forum/viewtopic.php?id=27274

**Comment by plegall** [comment]
Piwigo 14 and it's new search should do the job

![image](https://github.com/Piwigo/Piwigo/assets/9326959/c51d9572-c055-479e-b5ae-a39886c84635)
