### ISSUE TITLE
The quick edit album popup doesn't work (it's invisible)

### ISSUE THREAD

**Issue by extorn** [Piwigo/Piwigo#671]
The following lines of code when added to the theme.css file at the end solve the problem and make it look to my eye in line with the rest of the theme.

#cboxOverlay {
    background: #000;
    opacity: 0.9;
    filter: alpha(opacity = 90);
    position: fixed;
    width: 100%;
    height: 100%;
}

#cboxContent a.icon-ato-cancel.close-edit:hover {
   color: #fff;
}

#cboxContent a.icon-ato-cancel.close-edit {
   color: #ccc;
   font-size: 0.8em;
   font-family: Arial,Helvetica,sans-serif;
}

#cboxContent .ui-submit .ui-btn-hidden {
   position: absolute;
   top: 0;
   left: 0;
   width: 100%;
   height: 100%;
   -webkit-appearance: none;
   cursor: pointer;
   background: #fff;
   background: rgba(255,255,255,0);
   filter: Alpha(Opacity=0);
   opacity: .1;
   font-size: 1px;
   border: none;
   text-indent: -9999px;
}

**Comment by plegall** [comment]
please post this issue on https://github.com/Piwigo/AdminTools

**Comment by extorn** [comment]
New issue opened in admin tools - 
https://github.com/Piwigo/AdminTools/issues/7
