### ISSUE TITLE
batch downloader can not create large zip files after update from 2.8.6 to 2.9.0

### ISSUE THREAD

**Issue by Jomelo** [Piwigo/Piwigo#672]
Hi, 
i cannot download large foto archrives in one or more zip files because there comes the error message without php tags. 

$lang['Sorry, there is nothing to download. Some files may have been excluded because of <i title="Authorized types are : %s">filetype restrictions</i>.'] = 'Entschuldigung, es gibt nichts herunterzuladen. 
Einige Dateien könnten wegen Typen-Beschränkung(en) ausgeschlossen sein, <i title="Erlaubte Typen sind : %s">Datei-Typen-Beschränkungen</i>';

**Comment by flop25** [comment]
Hello
please go there https://github.com/mistic100/Piwigo-BatchDownloader Thank you

**Comment by Jomelo** [comment]
Thanks the reasen is the new pricture extension list without upper extension.
