### ISSUE TITLE
PHP 7 RSS error

### ISSUE THREAD

**Issue by Youp3** [Piwigo/Piwigo#678]
Hello,

I have piwigo 2.9.0 and when I go on feed.php page, I have this error:

> Erreur d’analyse XML : données incompréhensibles après l’élément de document
> Emplacement : https://url/feed.php?feed=123456789
> Numéro de ligne 2, Colonne 1 :<b>Deprecated</b>:  Methods with the same name as their class will not be constructors in a future version of PHP; FeedHtmlField has a deprecated constructor in <b>/path/include/feedcreator.class.php</b> on line <b>275</b><br />
> ^

The solution is given [on the forum](http://piwigo.org/forum/viewtopic.php?pid=166362#p166362) : 
```
to fixed the deprecated Message:
open include/feedcreator.class.php

Find the line ( ... FeedHtmlField has a deprecated constructor in /****/include/feedcreator.class.php on line 275 )
275 = class FeedHtmlField {
Finde the function with same name (291: function FeedHtmlField($parFieldContent) { )
Replace ["function NAME" (function FeedHtmlField) by public function __construct
=> don't change the content of ( ) - only replace function NAME !
=> do this with every deprecated line ...
=> Save
```

Please include this fix in the offical release.

Regards
Yann

**Comment by plegall** [comment]
@MaximeBOURMAUD please check this
