### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by simodelle** [Piwigo/Piwigo#684]
Hi, i have installed correctly piwigo but when i go to start tour display this fatal error message 

Fatal error: Uncaught --> Smarty: Unable to load template file './plugins/TakeATour/tours/first_contact/tour.tpl' <-- thrown in /web/htdocs/www.claudiamonachetti.com/home/piwigo/include/smarty/libs/sysplugins/smarty_internal_template.php on line 139

how can i resolve it?

**Comment by flop25** [comment]
Hello
can you check if the mentioned file is there?

**Comment by simodelle** [comment]
ok i resolved it, the file name was tour.ptl.bak so i rename it as tour.ptl and now its work good

**Comment by flop25** [comment]
Nope don't use it! it's file left from devt (https://github.com/Piwigo/TakeATour/tree/master/tours/first_contact) Download again Piwigo and resend all files or use the plugin Check Files Integrity
