### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by feric** [Piwigo/Piwigo#702]
# **Issue on Photo Edit**

After upload an image, an administrator can edit their metadata as Title, Author, etc.

The image editor is similar to this URL /piwigo/admin.php?page=photo-5 where the number is an Image ID, the application does not validate strings passed to page parameter been possible to retrieve some files from the server similar to a Local File Inclusion.

**Comment by flop25** [comment]
why did you publish that?!?

**Comment by feric** [comment]
Where can I send you a complete detail?

**Comment by flop25** [comment]
Thank you

did you use the contact form?
team at piwigo.org works too (any team user at piwigo.org also)

**Comment by feric** [comment]
I was looking for a direct contact but this ok, thanks

**Comment by flop25** [comment]
well a email couldn't be more direct?!

**Comment by feric** [comment]
yep (:
