### ISSUE TITLE
[security] identification should redirect within Piwigo only

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#706]
The `$_POST['redirect']` system in identification.php can lead to redirect outside Piwigo. On any location actually. To avoid any "open redirect" security issue, Piwigo should make sure the redirection occurs only with Piwigo, not outside.

**Comment by plegall** [comment]
@modus75 can you review that?

For the "forced redirection" (second commit bbb9c5e6b5bb44ad231050f6fb9f624a4925c5f8), here are 4 examples:

A) http://localhost/piwigo/git/identification.php?redirect=/piwigo/git/admin.php
```
{redirect (raw) = /piwigo/git/admin.php}
{get_absolute_root_url = http://localhost/piwigo/git/}
{cookie_path = /piwigo/git/}
{host = http://localhost}
{redirect (final) = http://localhost/piwigo/git/admin.php}
```
B) http://localhost/piwigo/git/identification.php?redirect=http://piwigo.org
```
{redirect (raw) = http://piwigo.org}
{get_absolute_root_url = http://localhost/piwigo/git/}
{cookie_path = /piwigo/git/}
{host = http://localhost}
{redirect (final) = http://localhosthttp://piwigo.org} => that will fail
```
C) https://pierrick.piwigo.com/identification.php?redirect=%252Fadmin.php
```
{redirect (raw) = /admin.php}
{get_absolute_root_url = https://pierrick.piwigo.com/}
{cookie_path = /}
{host = https://pierrick.piwigo.com}
{redirect (final) = https://pierrick.piwigo.com/admin.php}
```
D) https://pierrick.piwigo.com/identification.php?redirect=http://piwigo.org
```
{redirect (raw) = http://piwigo.org}
{get_absolute_root_url = https://pierrick.piwigo.com/}
{cookie_path = /}
{host = https://pierrick.piwigo.com}
{redirect (final) = https://pierrick.piwigo.comhttp://piwigo.org} => that will fail too
```

**Comment by modus75** [comment]
Looks OK to me

Le 14 juin 2017 10:28, "Pierrick Le Gall" <notifications@github.com> a
écrit :

**Comment by plegall** [comment]
Thank you @modus75 commits merged :-)
