### ISSUE TITLE
input parameter "redirect_decoded" is not valid

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#710]
With Piwigo 2.9.1, if you have have set a `$conf['gallery_url']` then the redirect path check will always fail.

```
$_POST[redirect_decoded] = /demo/admin.php
get_gallery_home_url() = http://fr.piwigo.org/demo
```

> Piwigo encountered an irrecoverable error
> 
> [Hacking attempt] the input parameter "redirect_decoded" is not valid
> 
> #1	check_input_parameter identification.php(52)

**Comment by bhlevca** [comment]
Hi, So how can I fix this? I can't log in anymore. If 2.9.2 with the fix appears how can I update without being logged in as admin?

Is there a way to fix the login until a fix is released? 
Thanks Bogdan

**Comment by ipereda** [comment]
Thanks for the fix!
Nacho
