### ISSUE TITLE
user_list not showed after upgrade to 2.9.0 from 2.8.6

### ISSUE THREAD

**Issue by gino909** [Piwigo/Piwigo#712]
Hi
The upgrade to 2.9.0 works well, but after upgrading the user_list is not showed anymore. It say only "No data available in table". When installing 2.9.0 from scratch it works... but not when upgrading from 2.8.6 version.
The user are there, i checked it in the database, the user can also login, only in backend is not possible to browse users or to change it... adding user is also possible, but also new creaed users will not be showed
Thank you
Gino

**Comment by plegall** [comment]
Hi @gino909 

1. Do you have a custom `$conf['gallery_url']` ?
2. If you open the console in your browser, do you see any error ? including in the "network" tab?
3. on the page of the users, do you see the menu bar with dark gray or light gray (like on Piwigo 2.8) ?

**Comment by gino909** [comment]
Hi plegall
Thanks for your feedback.
No, the value of gallery_url in config_default.inc.php is "null"
No error in Browser console, not in Firefox and also not in Chrome, same behaviour in both browsers
I will attach a screenshot, you can see my screen... the strange thing is, with the link select all I can select the users, it says 3 selected... but I do not see the users...
![auswahl_072](https://user-images.githubusercontent.com/3649450/27244868-d2edb47a-52e8-11e7-97d6-11e1d1e5cbc7.png)

**Comment by gino909** [comment]
What I have to say for your knowledge is, that i use the Ldap plugin where I had to make some adjustments to make it working. I installed a clean 2.9.0 installation today and I added all plugins same as in the "corrupt" installation and there the userpanel works... also with ldap login...

**Comment by plegall** [comment]
Do you run 2.9.0 or 2.9.1 ? If 2.9.1, can you open file admin/user_list_backend.php and remove the 2 lines (beginning of the file):

```
check_input_parameter('iDisplayStart', $_REQUEST, false, PATTERN_ID);
check_input_parameter('iDisplayLength', $_REQUEST, false, PATTERN_ID);
```

**Comment by gino909** [comment]
Hi... I am running 2.9.0 and there this 2 lines are not present.
With the new installation, the lines are there and the user_list works fine...
Also when I update from 2.9.0 to 2.9.1 the user_list does not appear...

**Comment by plegall** [comment]
Can you give me access to your Piwigo? please contact me by email http://piwigo.org/contact

**Comment by plegall** [comment]
OK, after nearly 1 hour of search, here is what I found in your themes/default/js/plugins/jquery.dataTables.js

```
 * @summary     DataTables
 * @description Paginate, search and sort HTML tables
 * @version     1.9.4
```

but with Piwigo 2.9.0 you should find:

```
/*! DataTables 1.10.11
```

Obviously the update was not complete. You should download Piwigo 2.9.0, extract files and overwrite them on your Piwigo installation.

**Comment by gino909** [comment]
Hi, you're right... something was wrong in the update... after overwriting the installation again with new files all works as expected... sorry for the inconvenience...probably there was a permission error during upload of files...

Thanks for the fast and professional support!
