### ISSUE TITLE
update notification mail in french/english mix

### ISSUE THREAD

**Issue by e-dschungel** [Piwigo/Piwigo#713]
Hi,

I received the new update mail. The header is english, but the text itself is french, see screenshot below.
My guest user language is french [qc] and  $conf['browser_language'] is not set in local config so its true by default. My browser language is german.
The language should be the same for both and determined by the browser language or the guest user language.

![grafik](https://user-images.githubusercontent.com/601056/27300591-814174be-5530-11e7-87a1-8ba991c1c345.png)

**Comment by plegall** [comment]
Hi @e-dschungel yes I saw that too. My "main" text was in English and the email footer was in French. I must check what is wrong.

The language must be the language of the recipient (the admin user).
