### ISSUE TITLE
synchronize can not sync right with chinese directory (wrong filename)

### ISSUE THREAD

**Issue by fcying** [Piwigo/Piwigo#727]
os : ubuntu 
      docker php:apache
      docker mysql:latest

[./galleries/20161029照片] PWG-UPDATE-1 (wrong filename)

**Comment by flop25** [comment]
have you tried to change the value of $conf['sync_chars_regex'] in the local config?

**Comment by fcying** [comment]
@flop25  I modify the sync_chars_regex `$conf['sync_chars_regex'] = '/^[a-zA-Z0-9-_.].*$/'`, it can work now, thanks~~
