### ISSUE TITLE
Random photo doesn't work

### ISSUE THREAD

**Issue by fabrix95** [Piwigo/Piwigo#730]
Hi,

Random photo shows me the albums instead of photos

https://www.galleria.pescaraspotters.it/random.php

**Comment by flop25** [comment]
Hello
try to disable plugins and try with a core theme

**Comment by flop25** [comment]
Hello
try to disable plugins and try with a core theme

**Comment by fabrix95** [comment]
I've just tried. Nothing to do...

**Comment by flop25** [comment]
may I have a webmaster access temporary on your gallery? flop25 at piwigo.org

**Comment by fabrix95** [comment]
Sent

**Comment by flop25** [comment]
thx
that is so weird because remove just one id works such as https://www.galleria.pescaraspotters.it/index.php?/list/161,464,359,130,1348,133,375,1480,939,111,692,243,1116,412

**Comment by fabrix95** [comment]
But if I click on image on your link there's an error

**Comment by flop25** [comment]
do you have any httaccess at the root of Piwigo or upper?

**Comment by fabrix95** [comment]
Yes

**Comment by flop25** [comment]
could you rename it/them?

**Comment by fabrix95** [comment]
Rename .htaccess to .hataccess1 for example?

**Comment by flop25** [comment]
yes

**Comment by fabrix95** [comment]
Done

**Comment by flop25** [comment]
everything I'm doing doesn't work
arg


![](http://ljdchost.com/XPQKnEJ.gif)

can you upload all 2.9.1 files by overwriting existing ones?

**Comment by fabrix95** [comment]
Uhm... now I'm unable. I should make backup before.

**Comment by flop25** [comment]
you can but no worry it's safe

btw you can set back the htaccess

**Comment by fabrix95** [comment]
Overwriting in progress... (45 mins) :samoa:

**Comment by fabrix95** [comment]
Done. All file raplaced by package http://piwigo.org/basics/downloads

**Comment by flop25** [comment]
so I think now I know what's going on
you probably have a security module from the sever (apache/nginx) which doesn't allow urls to have a parameter exceeding around 65 characters

**Comment by fabrix95** [comment]
Thank you.

In fact https://galleria.pescaraspotters.it/index.php?/list/1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 works. 

So I have to ask to my provider. I don't know where this security modulo is. Any suggestions?

**Comment by flop25** [comment]
found the thread http://piwigo.org/bugs/view.php?id=1651
so it's quite likely suhosin from Php

**Comment by fabrix95** [comment]
Thank you 😃
