### ISSUE TITLE
rename transliterate function 

### ISSUE THREAD

**Issue by flop25** [Piwigo/Piwigo#732]
which seems to collide with Php for some installations
http://piwigo.org/forum/viewtopic.php?id=27606
http://piwigo.org/forum/viewtopic.php?id=27607
http://piwigo.org/forum/viewtopic.php?id=28111

**Comment by modus75** [comment]
Note to myself : this will break 2.9 plugin rvelices autocomplete. Need new version.

**Comment by TallGuysFreeADMIN** [comment]
@modus75 you are correct. I can confirm this has unfortunately broken rv autocomplete. 
`PHP Fatal error:  Call to undefined function transliterate() in /REDACTED/plugins/rv_autocomplete/functions.inc.php on line 225`

**Comment by plegall** [comment]
PWG Stuffs is broken too, I'm going to publish a new version.
