### ISSUE TITLE
 incorrect pagination 

### ISSUE THREAD

**Issue by tomchiverton** [Piwigo/Piwigo#740]
Off by one error in number of photos on each page e.g. 4x4 grid on https://rachaelandtom.info/photos/index/category/194-tom_s_mum_s_65th#content is missing final image

Latest Piwigo release, PHP 7

**Comment by flop25** [comment]
hello
contact the theme author

**Comment by flop25** [comment]
btw it simply comes from the number of picture page which is 15 by default
and since it's a responsive theme, the number should be divisible by 2, 3 and 4 since that's the most usual number of column you will see
