### ISSUE TITLE
Downloaded photos can't be opened - extra blank line at the beginning of the file

### ISSUE THREAD

**Issue by Chartman123** [Piwigo/Piwigo#742]
When I download a photo from my gallery, I can't open the file, because there's an extra blank line at the beginning of the file. After removing this line, the photo can be opened.

Piwigo 2.9.1
PHP: 7.1.7 
MySQL: 5.7.19-log [2017-07-31 13:07:07]

**Comment by flop25** [comment]
https://github.com/Piwigo/Piwigo/pull/643#issuecomment-312667996

**Comment by Chartman123** [comment]
This fixes the issue.

**Comment by flop25** [comment]
have a good day

**Comment by Chartman123** [comment]
Happens again in the latest 2.10 build of Piwigo.

**Comment by iNoels** [comment]
still Exist in 2.10.1 using the German Language and following Plugins Admin Tools, Ldap_Login and User Tags. 

It's the same issue.
https://github.com/Piwigo/Piwigo/pull/643#issuecomment-312656664
