### ISSUE TITLE
New Suggestion

### ISSUE THREAD

**Issue by mcinternet** [Piwigo/Piwigo#743]
Hello, 
I need a kind of extended EXIF-View for piwigo. There are a few Plugins, but they have to less Info. What needed is:
Company: Canon (exists)
Camera  (example)  Canon EOS MK 5d MK IV (exists)
Lens       (example EF 24-70 f2.8 L IS II USM)
Aparture (example) f5.6  -  (exists)
Shutter   (example) 1/250 sek
mm        (example)  55mm
ISO        (example)  ISO 100

who can do this?

kind regards

JB

**Comment by flop25** [comment]
Hello
check with /tools/metadata.php if they are readable by Php , then you can add them thought the local config
If Php can't you would have to use a third party tool like 'exif tool' or change them
