### ISSUE TITLE
Unable to view users - 403 on user_list_backend.php

### ISSUE THREAD

**Issue by nitro322** [Piwigo/Piwigo#748]
Hi.  I just setup a no piwigo gallery and am trying to create a new user.  When browsing the Users, Manage, page, though, I get this error message:

`DataTables warning: table id=userList - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

Tried creating a user anyway and that part actually worked (I can see the new user record in the database and login as that user), but I still get that error every time I try to view the Users, Manage page, and thus I'm unable to view or manage the user.

I checked the server logs and found that I"m getting a 403 when trying to POST to admin/user_list_backend.php:

`[30/Aug/2017:03:04:29 -0500] "POST /photos/admin/user_list_backend.php HTTP/1.1" 403 243 "https://www.website.net/photos/admin.php?page=user_list"`

I loaded Firebug in Firefox and can see the 403, but I can't find any extra insight into what's causing it.  Pasting a screenshot that shows the headers for both admin.php?page=user_list as well as the follow-up request to admin/user_list_backend.php in the hope it may show you something useful.

![image](https://user-images.githubusercontent.com/8563706/29862115-3445e72e-8d31-11e7-9f25-7c215c523128.png)

Any idea what may be causing this?  or what I can do to troubleshoot further?  This is my first piwigo instance, so I don't have have another instance to compare against.

For reference, this is running under apache 2.4.27 w/ PHP 7.0.21 on a Linux host.  Happy to provide more details if it will help.

Thanks.

**Comment by nblanton** [comment]
Also seeing this issue.  Just upgraded from 2.6.x (Cant remember exact version)
Piwigo 2.9.1
Operating system: Linux
PHP: 5.5.38 (Show info) [2017-10-02 21:18:00]
MySQL: 5.5.57-0+deb7u1-log [2017-10-02 21:18:00]
Graphics Library: External ImageMagick 6.8.9-9

**Comment by stueja** [comment]
Also seeing this issue, without the opportunity to add users.
Piwigo 2.9.3
Arch Linux
PHP 7.2.3
