### ISSUE TITLE
Cannot run install/piwigo_structure-mysql.sql twice

### ISSUE THREAD

**Issue by ed-piwigo** [Piwigo/Piwigo#751]
The second time it fails with:
ERROR 1050 (42S01) at line 171: Table `piwigo_image_format` already exists

It is missing a DROP TABLE just before the CREATE TABLE statement.
Same with `piwigo_user_auth_keys` table at line 373.

Best regards.
Eric.

**Comment by flop25** [comment]
Than you

**Comment by flop25** [comment]
awaiting cp

**Comment by plegall** [comment]
cherry-picked on 2.9 for 2.9.2
