### ISSUE TITLE
Sync'ing the metadata send a date creation incorrect for Mysql 5.7 

### ISSUE THREAD

**Issue by flop25** [Piwigo/Piwigo#755]
If the picture as '0000-00-00 00:00:00' in the exif and Piwigo is configured to use it for the creation_date properties, synchronizing the metadata from the picture_modify page will try to send '0000-00-00 00:00:00' to mysql which is forbidden. EVEN if the default value of the creation_date as been set to something different from   '0000-00-00 00:00:00' from Mysql

**Comment by flop25** [comment]
awaiting Cherry-Pick for 2.9.2

**Comment by plegall** [comment]
cherry-picked for 2.9.2 :-)
