### ISSUE TITLE
upload a 3968x2976 jpg with shotwell failed

### ISSUE THREAD

**Issue by benny-de** [Piwigo/Piwigo#766]
Hello,
I use Ubuntu with shotwell 0.26.2 and a debian system with Piwigo 2.9.1
    PHP: 5.6.30-0+deb8u1 (Info anzeigen) [2017-09-12 17:16:52]
    MySQL: 5.5.5-10.1.26-MariaDB-0+deb9u1 [2017-09-12 17:16:52]
    Grafikbibliothek: GD 2.1.1-dev

When I publish pictures with shotwell with 2048x1536 it works fine.
When I have larger pictures in shotwell and select "original size" and the this is 3968x2976
shotwell transferes the picture and say "all fine".
piwigo creates a new album for this picture, but the album is empty - no picture.
In shotwell I have not found an error log. I checked .cache/shotwell/shotwell.log
But in the piwigo apache2/error.log I found:

PHP Warning:  md5_file(): Filename cannot be empty in /.../piwigo/admin/include/functions_upload.inc.php on line 175
PHP Warning:  getimagesize(): Filename cannot be empty in /.../piwigo/admin/include/functions_upload.inc.php on line 226

As a workaround shotwell transferes my pictures only in 2048x1536 fix.
Thank you for fixing this issue :)

**Comment by flop25** [comment]
and if you send the file 3968x2976 normally through the web upload ?
