### ISSUE TITLE
Photosphere plugin problem

### ISSUE THREAD

**Issue by kozobp** [Piwigo/Piwigo#772]
Hello,

first of all, many thanks for the photosphere plugin. I face to the following problem: some of my photosphere pictures are not shown; only a black area is visible. I use always same softwares and methods to create my pictures.
[Working picture](https://kozo.myphotos.cc/picture.php?/7427/category/92)
[Non-working picture](https://kozo.myphotos.cc/picture.php?/7289/category/92)
Could you please help me and advise what goes wrong? What further information shall I provide!
Thanks!

**Comment by flop25** [comment]
Hello
both are working for me
and the plugin is here https://github.com/mistic100/Piwigo-PhotoSphere
