### ISSUE TITLE
Uncaught Error: Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#775]
With PHP 7 (in case it's related...), when opening index.php and seems to detect a new version is available, I get this error. 

```
Fatal error: Uncaught Error: Class 'DOMDocument' not found in include/emogrifier.class.php:406

Stack trace:
#0 include/emogrifier.class.php(233): Emogrifier->createXmlDocument()
#1 include/functions_mail.inc.php(963): Emogrifier->emogrify()
#2 include/functions_mail.inc.php(861): move_css_to_body('<!DOCTYPE html ...')
#3 include/functions_mail.inc.php(473): pwg_mail(Array, Array, Array)
#4 admin/include/updates.class.php(223): pwg_mail_admins(Array, Array, false, true)
#5 include/page_tail.php(63): updates->notify_piwigo_new_versions()
#6 index.php(375): include('/var/www/html/p...')
#7 {main} thrown in include/emogrifier.class.php on line 406
```

**Comment by MaximeBOURMAUD** [comment]
Hello,

To fix this issue you need to install two package : "php-xml" and "php-mbstring".
When you installed these package you need to restart you're Apache server using : "service httpd restart" (Fedora) or "service apache2 restart" (Debian/Ubuntu).

**Comment by Wikinaut** [comment]
Please add configuration checks for these extensions.

**Comment by shapirus** [comment]
...or document them in the requirements section. I've just run into this issue too.

**Comment by plegall** [comment]
OK, I have added it on http://piwigo.org/doc/doku.php?id=user_documentation:learn:install:before

**Comment by davidhbrown** [comment]
Still useful for Ubuntu 24.04.1 LTS which bundles PHP 8.3... but unfortunately plegall's link no longer works. [https://doc-fr.piwigo.org/hebergez-votre-piwigo/installer-piwigo/installer-piwigo-sur-debian](https://doc-fr.piwigo.org/hebergez-votre-piwigo/installer-piwigo/installer-piwigo-sur-debian) seems to still have this information. Not yet in the English version.
