### ISSUE TITLE
Support for FUSE filesystem?

### ISSUE THREAD

**Issue by madisonb** [Piwigo/Piwigo#780]
I have been trying to use the [s3fs](https://github.com/s3fs-fuse/s3fs-fuse) project as way to enable large amounts of storage (for videos) on my Piwigo setup. For those unfamiliar, Amazon S3 is a large scale object store and the s3fs project enables it to be mounted like it is a directory on your local filesystem.

When I use the s3fs folder as the destination behind `upload/`, I get an error that piwigo is unable to create the desired directory needed. Normally this is a permission issue, however even `chmod 777` and chown'ing to different users (root,www-data), I have not been able to get past the following error:

`error during buffer directory creation`

Which appears to be thrown either [here](https://git.io/vdT6e) or [here](https://git.io/vdT6k). I can create that directory, I can create the upload path (`2017/09/...`), and I can manipulate files/folders as the user, but it appears piwigo is failing within the `mkgetdir` method.

Has anyone had success with this?

My s3fs command to mount the folder is:
```
s3fs <s3 bucket> /<bucket mount path> -o passwd_file=<password path> -o use_cache=/tmp/ -o allow_other,uid=0,gid=0
```

I will note that I am using a piwigo docker setup running under root, however even installing piwigo natively it appears to have the same issues.

**Comment by madisonb** [comment]
For anyone who needs this, I was able to get it working by switching to the [yas3fs](https://github.com/danilop/yas3fs) project instead of using s3fs. Appears to be working great so far!

Closing.

**Comment by hesyifei** [comment]
It seems that `s3fs` is also working now:

```bash
sudo s3fs BUCKET_NAME PATH/galleries/s3 -o passwd_file=${HOME}/.passwd-s3fs -o allow_other,uid=1000,gid=33,umask=0022
```
