### ISSUE TITLE
Error with PHP7.

### ISSUE THREAD

**Issue by Jonadabe** [Piwigo/Piwigo#791]
Hi there,

Thank you for your great work on Piwigo.
I got this error accessing profile.php:

Deprecated: Function mcrypt_get_iv_size() is deprecated in /home/.../public_html/piwigo/plugins/Subscribe_to_Comments/include/functions.inc.php on line 579

Deprecated: Function mcrypt_create_iv() is deprecated in /home/.../public_html/piwigo/plugins/Subscribe_to_Comments/include/functions.inc.php on line 580

Deprecated: Function mcrypt_encrypt() is deprecated in /home/.../public_html/piwigo/plugins/Subscribe_to_Comments/include/functions.inc.php on line 581

Warning: Cannot modify header information - headers already sent by (output started at /home/.../public_html/piwigo/plugins/Subscribe_to_Comments/include/functions.inc.php:579) in /home/.../public_html/piwigo/include/page_header.php on line 101

**Comment by flop25** [comment]
Hello
check there https://github.com/mistic100/Piwigo-Subscribe-to-Comments
