### ISSUE TITLE
2.9.2 upgrade fails

### ISSUE THREAD

**Issue by ptilopteri** [Piwigo/Piwigo#792]
2.9.2 upgrade expects o+w perms which are not normal.
was able to complete upgrade by changing perms then disallowing o+w

**Comment by TallGuysFreeADMIN** [comment]
Did you update via web UI or download manually?

**Comment by ptilopteri** [comment]
* Tall Guys Free <notifications@github.com> [10-08-17 16:01]:
> Did you update via web UI or download manually?

I used the web interface.  it appears to want incorrect perms, o+r.  it
will work if the perms are changed.

tks,

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Registered Linux User #207535                    @ http://linuxcounter.net
Photos: http://wahoo.no-ip.org/piwigo		    paka @ IRCnet freenode

**Comment by flop25** [comment]
let's talk in chmod and OS users please

**Comment by ptilopteri** [comment]
chmod and os ??
I use openSUSE 42.2 Leap for server and admin via web from openSUSE Tumbleweed
original installed complained of no write-perms, g+w did not work but o+w did which I immediately returned to o-w
Is that wat you are asking?

**Comment by flop25** [comment]
"os users" in your case linux ones
g+w o-w etc are the command you are using. Talk using the relevant https://en.wikipedia.org/wiki/Chmod value. So we need to assume that you are talking about the files that are not updated while having a chmod 644 (and not the folders which should be 755). Is that right? If that's the case it's quite highly probable that's the server fault. For instance Linux users Vs file owner Vs processes
Have you tried other CMS?

**Comment by ptilopteri** [comment]
* flop25 <notifications@github.com> [10-08-17 20:37]:
> "os users" in your case linux ones

I have only control, am Webmaster.  I do not allow user control at all.

> g+w o-w etc are the command you are using. 

no, perms are pretty much all as:
  drwxr-xr-x 1 root root   1732 Jun 15 08:13 ./admin/
  -rw-r--r-- 1 root root  11351 Oct  8 09:15 ./admin.php

> Talk using the relevant https://en.wikipedia.org/wiki/Chmod value.  So
> we need to assume that you are talking about the files that are not
> updated while having a chmod 644 (and not the folders which should be
> 755).  Is that right?  

piwigo upgrade refused any action reporting missing write permissions.
subject directories had 40755 and files had 100644

changing to 40757 and 100646 provided the write permissions the upgrade
needed/wanted.

> If that's the case it's quite highly probable that's the server fault. 
> For instance Linux users Vs file owner Vs processes

I assume you are referring to my server which is a local machine I
maintain which provides mail and some files and piwigo (previous
gallery2).

most of the /srv/www/htdocs/piwigo structure is root:root with a few lower
directory/files wwwrun:www

I tried to perform the update as advised by the piwigo web admin that
upgrades were available.  initiating upgrade complained of no
write-permissions.  expermentation showed the upgrade wanted o+w, so I
obliged to complete the upgrade, then return to o-w.

I did from above examples:
  chmod -R o+w /srv/www/htdocs/piwigo/*

this allowed update acceptable permissions

then to return perms to as installed:
  chmod -R o-w /srv/www/htdocs/piwigo/*

> Have you tried other CMS?

no, to what end?  I am a single user/manager who provides photo albums for
others to view, primarily high school and college soccer.  I photograph
for Avon Indiana High School and IUPUI.

no one else has any admin rights or ability to upload photos or video. 
only to download and/or view.

I notice piwigo dashboard advises I have:
    Some upgrades are available for extensions. 
    
I initiated the upgrade, told it to proceed and it completed.  apparently
the required permissions were met but there were not o+w:
  drwxr-xr-x 1 wwwrun www 202 Oct  8 20:56 rv_autocomplete/
  drwxr-xr-x 1 wwwrun www 270 Oct  8 20:56 rv_gmaps/ 


I had a similar problem on an earlier upgrade failing but it later
completed successfully and I did not investigate further but I seem to
remember it involved permissions also.

note: the only change to the download from piwigo site, install besides
the addition of extensions also from piwigo site, is I provided a
hard-link to /srv/www/htdocs/piwigo/upload to minimize space usage on /srv
which is a separate partition.

tks,     
-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Registered Linux User #207535                    @ http://linuxcounter.net
Photos: http://wahoo.no-ip.org/piwigo		    paka @ IRCnet freenode

**Comment by flop25** [comment]
> most of the /srv/www/htdocs/piwigo structure is root:root
you should never run a web server while using root as an owner (i did once and things went badly) ; its certainly the source of the conflict here but it also could be the source of major security issues. Since you reported some files/folder with wwwrun www as owner I think this ownership is the right one. This depend on under which user the server is running and its configuration (type of execution of php etc)

It sounds like you are a beginner in server administration (which is fine, I am an amateur too) and you are using a local computer or a NAS as a server. Based on world wide users experiences, never use your local computer, and use your NAS only if it doesn't contain unencrypted sensitive information ; you should consider that you server will be hacked at some point and its data leaked.
Server safety can be quite complex, so I also recommend the use of a cPanel-like script (ipconfig etc) with extra safety measures.

**Comment by ptilopteri** [comment]
the purpose of the bug report is to seek correction of piwigo script upgrade procedure and the insecure method required and not advised.  ownership settings are as piwigo install script provides and there are no apparent instructions to make it otherwise.  if piwigo requires altering those settings, please advise.  the upgrade as provided failed w/o measures noted that definitely provide an insecure environment.

so do you have all the information you requested/need?

ps: the chat/irq forum is apparently unused and should be discontinued.

**Comment by flop25** [comment]
> the purpose of the bug report is to seek correction of piwigo script upgrade procedure and the insecure method required and not advised
the bug report is a dialogue between an user and a community including developers about an issue the user had. During that exchange of information, the causes are identified then a solution could emerge.
If you opened this bug as an assertion that you detain the truth, you are providing the help, the product has to change and you don't want to find the cause and a solution, just tell us.

>  ownership settings are as piwigo install script provides
not exactly; that depends on how you installed it.

Piwigo is not managing any ICQ channel, if that's what you are trying to tell

**Comment by ptilopteri** [comment]
* flop25 <notifications@github.com> [10-09-17 08:46]:
> > the purpose of the bug report is to seek correction of piwigo script
> > upgrade procedure and the insecure method required and not advised
>
> the bug report is a dialogue between an user and a community including
> developers about an issue the user had.  During that exchange of
> information, the causes are identified then a solution could emerge.
>
> If you opened this bug as an assertion that you detain the truth, you
> are providing the help, the product has to change and you don't want to
> find the cause and a solution, just tell us.

the bug report is to advise the web interface upgrade option will not
complete on my piwigo install.
 
> >  ownership settings are as piwigo install script provides
> not exactly; that depends on how you installed it.

I installed piwigo in May current using the web interface. netinstall,
http://piwigo.org/download/dlcounter.php?code=netinstall
 


> Piwigo is not managing any ICQ channel, if that's what you are trying to
> tell
 
please tell me what this is:

-- Sat, 07 Oct 2017 --                                                                                   
| Topic for #Piwigo is "Your own photo gallery! Latest:                              │
| http://piwigo.org/releases/2.9.1 ~ Showcase: http://piwigo.org/showcase/ ~ Forum:  │
| http://piwigo.org/forum/ ~ Docs: http://piwigo.org/doc/"                           │
| Topic set by Kaare (~Kaare@wikipedia/pdpc.professional.kaare) on Thu, 15 Jun 2017  │
| 15:42:19                                                                           │
| Channel created on Mon, 31 Jan 2011 10:45:10  

it may wrap, line begins/ends with "|"


tks,
-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Registered Linux User #207535                    @ http://linuxcounter.net
Photos: http://wahoo.no-ip.org/piwigo		    paka @ IRCnet freenode

**Comment by flop25** [comment]
> Topic set by Kaare 
so contact him

**Comment by flop25** [comment]
> Topic set by Kaare 

so contact him

**Comment by ptilopteri** [comment]
* flop25 <notifications@github.com> [10-09-17 09:42]:
> 
> > Topic set by Kaare 
> so contact him 

ok

about the permissions problem I experience(d)????
  is more information needed?

tks,
-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Registered Linux User #207535                    @ http://linuxcounter.net
Photos: http://wahoo.no-ip.org/piwigo		    paka @ IRCnet freenode

**Comment by ptilopteri** [comment]
* Thomas Kuther <notifications@github.com> [10-10-17 15:20]:
> In order to use the one-click-upgrade feature in the admin panel, your
> webserver's (or PHP interpreter's) OS user, "apache" or "http" in most
> distributions, <needs> to have write permissions to <all> Piwigo files.
> 
> So the real solution here isn't `chmod o+w` (which is totally wrong, you
> got that), but `chown apache:apache`.
> 
> So, that "bug" report is sort of invalid, because your files are owned
> by the wrong user for the one-click-upgrade to work.

ok, that ownership was what I was left with after using
piwigo-netinstall.php.  I am on openSUSE Leap 42.2.  I believe owner
should be wwwrun:www which is present in openSUSE rather than apache:apache
which is not present.

I will change the pers to wwwrun:www and report any new failure where
perhaps I need to create an apache group.

and perhaps mention of that or an ownership assignment should be made to
the net-install script?

thankyou,

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Registered Linux User #207535                    @ http://linuxcounter.net
Photos: http://wahoo.no-ip.org/piwigo		    paka @ IRCnet freenode

**Comment by TallGuysFreeADMIN** [comment]
I had a problem with Net install as well, a year or so ago. I ended up just downloading the archive manually. The language was all messed up or something. I can't remember. I think it was permissions but I didn't spend time trying to fix it. 

Also on Apache.

**Comment by ptilopteri** [comment]
* Tall Guys Free <notifications@github.com> [10-10-17 18:58]:
> I had a problem with Net install as well, a year or so ago. I ended up
> just downloading the archive manually.  The language was all messed up
> or something.  I can't remember.  I think it was permissions but I
> didn't spend time trying to fix it.

I didn't have trouble with the install, but having problems now that
appear to relate to an errant install.  No indication at the time.
 
> Also on Apache.

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Registered Linux User #207535                    @ http://linuxcounter.net
Photos: http://wahoo.no-ip.org/piwigo		    paka @ IRCnet freenode

**Comment by TallGuysFreeADMIN** [comment]
Me neither, sorry for not being specific.
The net install went well but afterwards the language was messed up and parts of the site weren't working

**Comment by plegall** [comment]
This is more a discussion to have on [Piwigo forums](https://piwigo.org/forum/). I close this issue (or it won't ever be closed I'm afraid)
