### ISSUE TITLE
Errors after upgrade to 2.9.2 

### ISSUE THREAD

**Issue by grutchme** [Piwigo/Piwigo#793]
hi guys,
I got problems after upgrading to 2.9.2 version : 
"piwigo-videojs" and  "header_manager" Plugins doesn't work anymore and return "version 0" while displaying info, it looks stange.
I try to reinstall but no change.
"piwigo-videojs" plugin doesn't see my mp4 files (i can see my mp4 files in galleries, no change since upgrade) even after synchronisation.
"header_manager" plugin returns error message when i try to activate : 
Fatal error: Class 'header_manager_maintain' not found in /media/Nextwab4/www/usr_tah6693280beb09b/public_html/websites/famille-tahon.fr/piwigo/admin/include/plugins.class.php on line 96

any help would be appreciated.

**Comment by flop25** [comment]
Hello
When you said you reinstalled them what did you do? Because I would first recommend to re-upload the files

**Comment by grutchme** [comment]
hello flop25

thanks for your answer
you give me the key, i had unsinstall and reinstall plugins from backend control panel.
As you suggest, i uninstall and then fransfer files in ftp, and then plugins come back with good version.
I look thurther if everything is ok.

**Comment by plegall** [comment]
I close this issue. It's related to specific extensions and certainly fixed 7 years after.
