### ISSUE TITLE
script_basename 

### ISSUE THREAD

**Issue by NaveenDA** [Piwigo/Piwigo#794]
When i remove "?" on url it shows something like 

> Warning: script_basename "categories" unknown in /home/sys/var/www/piwigo_master_29/include/section_init.inc.php on line 163

**Comment by flop25** [comment]
Hello
Have you changed the local config of your Piwigo?

**Comment by NaveenDA** [comment]
I don't know, because it is not my site when see showcase i found this http://raia.com/index/category/214-red_rock_canyon

**Comment by flop25** [comment]
Read the Doc, search on the forum etc Thank you and good customization
