### ISSUE TITLE
Programmatically Insert Photo in Gallerries 

### ISSUE THREAD

**Issue by attawit** [Piwigo/Piwigo#799]
I am new Piwigo, If there is already an API for sending picture to specific user and creating new user programmatically, We are trying to port pictures and creates to Piwigo system. Please advise me . Thanks

**Comment by flop25** [comment]
http://piwigo.org/doc/doku.php

**Comment by plegall** [comment]
Maybe a bit more specific with http://piwigo.org/doc/doku.php?id=dev:webapi:start

**Comment by attawit** [comment]
Thanks you, got that.

**Comment by attawit** [comment]
One more question, is there a way to know URL for the  picture that have been inserted in the system, programatically. Thanks you again in advance.

**Comment by plegall** [comment]
upload methods return the image id, then you can use method pwg.images.getInfo

**Comment by attawit** [comment]
Ok, thanks you
