### ISSUE TITLE
PIWIGO WS API - pwg.categories.getImages - categories field always contains just one category

### ISSUE THREAD

**Issue by extorn** [Piwigo/Piwigo#802]
When you call pwg.categories.getImages for a category, all resources are returned with just a single category in their list of categories. This is regardless of how many they are linked to.
This is an issue if you then wish to unlink a resource(s) (e.g. image), because you do not know whether it will result in an orphan unless you first do a call to get the details of that/those image(s) pwg.images.getInfo. This is inefficient.
Given the api appears to return a list of categories, I'd expect it to do so. It seems pointless to just return the one that you requested the images list for using pwg.categories.getImages.

**Comment by Ukrainian-1** [comment]
Hi, 
I am wondering if it is possible to get several images from several albums (e.g 3 images from each of 5 categories) in one query? The way to do several requests for this task looks a bit ugly solution, and there is not much documentation on the API.

**Comment by extorn** [comment]
Your comment sounds interesting, but this should be raised as a separate issue. The issue I've raised is very different, referring to the list of linked  albums returned for each resource when you retrieve the resources in a category.

**Comment by Ukrainian-1** [comment]
Thanks for your attention. I found not much developers activity on this API, so decided to ask in a live thread close to the issue.  Also posted this question to PIWI forum. Finally decided to query PIWI DB directly, this appeared to be the fastest and the simpliest method...
Sorry for off-topic message.

**Comment by EddyLB** [comment]
> Warning: `pwg.images.getInfo` only returns the list of categories accessible to the current user. Not all categories. So you can absolutely not know if the photo would become orphan if you delete an album. Not reliable at all.

This is not reliable (incomplete) for an admin looking for orphans globally on a server, but this is perfectly fine for an admin or non-admin user managing his/her own photos i.e. for most usages. We miss a user status allowing to create/delete/move/etc. albums and upload/delete/edit photos/videos without access to server management tools.

> Currently, with `multiple_value_mode` in {append, replace} you should be able to associate/move/dissociate to albums. The limit is that you have to call `pwg.images.setInfo` for each photo. We've been discussing this topic with @remi-martin and he suggests we had a new method `pwg.images.setCategory` with 3 parameters :
> 
> 1. image_ids (can be a list, that's the whole point)
> 2. action {associate, dissociate, move}
> 3. category_id
> 
> I like this idea. Much more simple to associate/dissociate images to/from albums. We could also have a specific method for each action : `pwg.images.associateToCategory` + `pwg.images.dissociateFromCategory` + `pwg.images.moveToCategory` (or `pwg.images.category.associateTo` + `pwg.images.category.dissociateFrom` + `pwg.images.category.moveTo`)

Sure, a single call would be much more efficient. Similarly, I would welcome an update of the methods `pwg.users.favorites.add` and `pwg.users.favorites.remove` because we must call them repeatedly.

> > As for the proposed `pwg.categories.calculateOrphans` method, I do not believe
> > that we really need it because it would return an information we can deduce from
> > a call to the `pwg.categories.getImages`
> 
> No, you can't deduce the "would be" orphans with `pwg.categories.getImages`, unless we add a new output field "categories_admin_list" which would not take permissions into account.
> 
> The `pwg.categories.calculateOrphans` method has been added by @MatthieuLP to make the computation as less often as possible, because it's an heavy one and it's useful only a very few times compared to the number of requests to `pwg.categories.getImages`.
> 
> > `pwg.categories.getOrphans`
> 
> You mean `pwg.images.getOrphans` because if a photo is associate to a category then it can't be an orphan. So it would be mean "list of orphans if we delete this category" and it would be the exact same as `pwg.categories.calculateOrphans`. Please give me more details :-)

I understood that the `pwg.categories.calculateOrphans` method would return the "future orphans" of a user i.e. taking rights into account, but in fact it returns all future orphans on a server, which is the `pwg.categories.getOrphans` I was proposed. Fine with me.
