### ISSUE TITLE
[Piwigo 2.9.2 and PHP 7.2.0] Incompatible code in gallery/include/functions.inc.php and /include/template.class.php

### ISSUE THREAD

**Issue by Wikinaut** [Piwigo/Piwigo#812]
```
Deprecated: Function create_function() is deprecated
in /gallery/include/functions.inc.php on line 2165

Deprecated: The each() function is deprecated.
This message will be suppressed on further calls 
in /gallery/include/template.class.php on line 293
```
* piwigo 2.9.2
* debian 9
* php 7.2.0

**Comment by plegall** [comment]
Here we go, first incompatibilities with the latest version of PHP :-) If you have coding skills, you may already know how to fix this and keep the code compatible with older versions of PHP (at least PHP 5.4) ? (I will soon install PHP 7.2 on a test environment)

**Comment by Wikinaut** [comment]
@plegall Yes, I will try. I already found several plugins not working with piwigo (this is another issue).

While we are talking, but off-topic here: is there something like a drag&drop function to move images and folders to another location?

**Comment by chrissuttles** [comment]
I just got hit by this after and update this evening.

```
Deprecated: Function create_function() is deprecated in /usr/share/webapps/piwigo/include/functions.inc.php on line 2165
Deprecated: Function create_function() is deprecated in /usr/share/webapps/piwigo/include/functions.inc.php on line 2165
Deprecated: Function create_function() is deprecated in /usr/share/webapps/piwigo/include/functions.inc.php on line 2165
Deprecated: Function create_function() is deprecated in /usr/share/webapps/piwigo/include/functions.inc.php on line 2165
Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /usr/share/webapps/piwigo/include/template.class.php on line 293
```

First four are the "Batch Downloader", "Header Manager", "Thumbnail Tooltip", and "UserAdvManager". If I disable those, they go away.

Also, forgive me if I am wrong, but having these php errors show up even on the main page without login is a bit of a security risk correct? Seems like these should only post when a user is logged in, or even better only for admins.


Piwigo 2.9.2
Operating system: Linux
PHP: 7.2.0 (Show info) [2017-12-08 20:39:21]
MySQL: 5.5.5-10.1.29-MariaDB [2017-12-08 20:39:21]
Graphics Library: External ImageMagick 6.9.9-25

**Comment by plegall** [comment]
As far as I understand for now, we have to replace create_function by anonymous function (closure) which is only available starting on PHP 5.3. Meaning, Piwigo can be compatible with PHP 7.2 if we drop compatibility with PHP 5.2 (I don't say it's a good idea, just a fact). Of course today I think it's more important to be compatible with PHP 7.2 than 5.2 ;-)

**Comment by Wikinaut** [comment]
@plegall Yes, you are correct. Such internal structure information should always be suppressed. This is what for example MediaWiki does (do not show internal information in case of warnings, errors, crashes).

**Comment by maniac0r** [comment]
i have the same issue with php7.2 on archlinux. is it possible to disable error displaying in the piwigo? it seems gallery works just fine and in my php.ini i have display_errors = Off thus I am not grasping why are the errors displayed in the browser?

**Comment by tariq-chameleon** [comment]
The create_function() and eval() should be replaced.

**Comment by mfguasti** [comment]
When trying to see 'users' I get the following error:
(Is this part of the same problem with php7.2 ?)

DataTables warning: table id=userList - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by LucMorizur** [comment]
Hi;
maniac0r you wrote:
> add  $conf['show_php_errors'] = E_NONE;
> to local/config/config.inc.php
Well actually on my 2.9.3 gallery both _$conf['show_php_errors'] = true;_ and _$conf['show_php_errors'] = false;_ are working, but _E_NONE_ is not.

**Comment by deeper26** [comment]
Hi,
my config is php 7.2.3


i re write the source code of functions.inc.php

first time i have :
//  $replace_chars = create_function('$m', 'return ord(strtolower($m[1]));');


i replace by

$replace_chars = function($m) {
return ord(strtolower($m[1]));};




i do the same thing in MultiView.class.php


//    $this->data_url_params = array_map(create_function('$d', 'return "ato_".$d;'), $this->data_url_params);
$this->data_url_params = array_map(
function ($d){
return "ato_".$d;},
$this->data_url_params);
  }

**Comment by deeper26** [comment]
re hi
in template.class.php
my case is

 // while(list($handle, $filename) = each($filename_array))
    foreach ($filename_array as $handle=>$filename)

**Comment by MasterSergeantD** [comment]
deeper26, 
Well done!  This fixed my issue.
Any thoughts on 
Deprecated: The each() function is deprecated. This message will be suppressed on further calls?

**Comment by plegall** [comment]
Piwigo 2.9.4 has fixed incompatibilities with PHP 7.2

**Comment by drder66** [comment]
I'm on 2.10.1 and am still having this issue. I upgraded from 2.9.something and since then trying to edit users produces "DataTables warning: table id=userList - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1". PHP also upgraded from 5 to 7.3

**Comment by maniac0r** [comment]
@drder66 i have just found a fix, in file ./admin/user_list_backend.php look for all occurences of "AS" and put the "as parameter" into the reversed quotes, e.g.:

diff ./admin/user_list_backend.php.dist ./admin/user_list_backend.php
42c42
< $sTable = USERS_TABLE.' INNER JOIN '.USER_INFOS_TABLE.' AS ui ON '.$conf['user_fields']['id'].' = ui.user_id';
---
> $sTable = USERS_TABLE.' INNER JOIN '.USER_INFOS_TABLE.' AS `ui` ON '.$conf['user_fields']['id'].' = ui.user_id';
208c208
<     GROUP_CONCAT(name ORDER BY name SEPARATOR ", ") AS groups
---
>     GROUP_CONCAT(name ORDER BY name SEPARATOR ", ") AS `groups`


i am using php-7.4.0 and MariaDB 10.4.7 (MySQL8.0.16).

**Comment by maniac0r** [comment]
@drder66 i have just found a fix, in file ./admin/user_list_backend.php look for all occurrences of "AS" and put the "as parameter" into the reversed quotes ( ` ).

i can see it's already patched here in master repo.

i am using php-7.4.0 and MariaDB 10.4.7 (MySQL8.0.16).
