### ISSUE TITLE
[Bug or Clarification Request] How can users add new albums and new fotos to albums?

### ISSUE THREAD

**Issue by Wikinaut** [Piwigo/Piwigo#814]
I do not seee a possibility that (how exactly?) users can add a new album or add new fotos.

Please advice. If this is a bug in the software, please add this feature.

**Comment by plegall** [comment]
Plugin Community http://piwigo.org/ext/extension_view.php?eid=303 does this job :-)

**Comment by Wikinaut** [comment]
Pls. make downloads coming via https !!!!!!!!!

**Comment by Wikinaut** [comment]
http is insecure
