### ISSUE TITLE
use xss+csrf attack on configuration pages

### ISSUE THREAD

**Issue by d4wner** [Piwigo/Piwigo#822]
Edit we did see your email  and we are currently discussing privately of the issue. No need to publish that. Thank you for reporting

**Comment by d4wner** [comment]
Well, sir,  I just see your close notification on the github:

*https://github.com/Piwigo/Piwigo/issues/822
<https://github.com/Piwigo/Piwigo/issues/822>*

Ummm, now how do you think about this vulnerability，sir？

I think it's need to be fixed in the future, even if not in recent days
,isn't it?



2017-12-18 1:34 GMT+08:00 flop25 <notifications@github.com>:

**Comment by plegall** [comment]
I'm working on it.
