### ISSUE TITLE
Reset/Update Database User Password

### ISSUE THREAD

**Issue by Rhiani** [Piwigo/Piwigo#835]
I, stupidly, changed the password on the database user for my Piwigo database through my web hosting cPanel interface while troubleshooting an issue I was having.  Now I get the following error:

Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'dbuser'@'localhost' (using password: YES) in /home/.../public_html/gallery/include/dblayer/functions_mysqli.inc.php on line 67

Is there a way to update the password for the database user to properly reflect the new password I set?  I would change the password back, but I changed it in the first place because I wasn't able to remember it and was trying to connect directly to the database.  (in retrospect, I should have created a new database user for the direct connection - like I said, stupid!)

**Comment by flop25** [comment]
use the md5
check our forum next time
