### ISSUE TITLE
Disable Plugins when unable to access a GUI

### ISSUE THREAD

**Issue by Rhiani** [Piwigo/Piwigo#836]
I recently started getting the following on two of my Piwigo installations.  If I do a brand new installation into a new directory, I have no problem.  So I'm thinking it is one of the plugins (community, perhaps, based on some of the paths) I've activated on the two installations.  Is there a way to disable plugins when I can't get to any graphical interfaces?

Warning:  [mysql error 1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'recursive,
    create_subcategories,
    nb_photos,
    storage
  FROM piwi_fp_c' at line 6

SELECT
    id,
    type,
    category_id,
    user_album,
    recursive,
    create_subcategories,
    nb_photos,
    storage
  FROM piwi_fp_community_permissions
  WHERE (type = 'any_visitor')
; in /home/[...]/public_html/.[..]/photos/include/dblayer/functions_mysqli.inc.php on line 845

Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /home/[...]/public_html/[...]/photos/include/dblayer/functions_mysqli.inc.php:226 Stack trace: #0 /home/[...]/public_html/[...]/photos/plugins/community/include/functions_community.inc.php(102): pwg_db_fetch_assoc(false) #1 /home/[...]/public_html/[...]/photos/plugins/community/main.inc.php(48): community_get_user_permissions('2') #2 /home/[...]/public_html/[...]/photos/include/functions_plugins.inc.php(279): community_init() #3 /home/[...]/public_html/[...]/photos/include/common.inc.php(308): trigger_notify('init') #4 /home/[...]/public_html/[...]/photos/index.php(26): include_once('/home/underg10/...') #5 {main} thrown in /home/[...]/public_html/[...]/photos/include/dblayer/functions_mysqli.inc.php on line 226

**Comment by flop25** [comment]
rename/remove/move the folder of the plugin you want to disable
check our forum next time
