### ISSUE TITLE
Use hash of original images to check for duplicate uploads

### ISSUE THREAD

**Issue by darenwelsh** [Piwigo/Piwigo#860]
It appears I am allowed to upload duplicate photos. I was hoping Piwigo would check for duplicates, but it seems it does not. I think one way to do this, as Mediawiki does, is to create a hash for the original image. Then for every image put into the upload queue, create a hash and check if that hash exists in the array of existing hashes.

I believe I'm using Piwigo version 2.7.4. Note this is a "one-click install" on a shared Dreamhost server.

**Comment by samwilson** [comment]
The relevant checksum already exists, it just needs to be checked at upload time.

But maybe it's enough that one can search for duplicates after upload? That's already built into the batch manager.

**Comment by samwilson** [comment]
A slightly related tweak: #910

**Comment by plegall** [comment]
Don't know yet how to implement that, but a quick action to avoid duplicates at upload, or remove them right after upload, would be useful.
