### ISSUE TITLE
increase PHP version required (to 7.0)

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#867]
Piwigo 2.9.3 is still marked as compatible with PHP 5.2. Oldest officially maintained branch is PHP 5.6. Wordpress.org statistics https://wordpress.org/about/stats/ currently says that 5.4+ is 89% of users and 5.5+ is 76%.

I think increasing the required version to 5.4 is "nearly painless".

**Comment by plegall** [comment]
Interesting study on PHP versions https://seld.be/notes/php-versions-stats-2018-1-edition

**Comment by plegall** [comment]
Considering the following facts:

- Piwigo 2.10 is not for "soon" (not this summer I'm afraid)
- compatibility with PHP 7.2 is becoming problematic (Ubuntu 18.04 comes with PHP 7.2)
- compatibility with PHP 7.2 breaks compatibility with PHP 5.2 (requires PHP 5.3)

I'm trying to merge the current pull-request  #834  for branch 2.9, which will require PHP 5.3.

**Comment by plegall** [comment]
See b1cb4e48c03f4ce62b3de66c3337d8b9ef656477

**Comment by J0celyn** [comment]
Note that PHP 5.6 and PHP 7.0 are now no longer maintainted.
Sources: http://php.net/eol.php and http://php.net/supported-versions.php

**Comment by plegall** [comment]
@J0celyn that's right... in theory. In practice however, there are still a vast majority of users running a PHP version older than 7.1. See https://wordpress.org/about/stats/ : 76,2% of users are running an "officially unsupported" version of PHP. We have to deal with that :-)

**Comment by J0celyn** [comment]
@plegall 
My previous message is not theory, it is factual information given on http://php.net about which PHP versions they still support as well as an update to your first post stating "Oldest officially maintained branch is PHP 5.6".

After looking at the Wordpress usage stats I understand your motivation to maintain PHP 5.x compatibility in Piwigo and providing support for users running an old version of PHP.

[Wordpress requirements](https://wordpress.org/support/article/requirements/) page clearly warns about the risks when running old versions of PHP/MySQL:
> Note: If you are in a legacy environment where you only have older PHP or MySQL versions, WordPress also works with PHP 5.2.4+ and MySQL 5.0+, but these versions have reached official End Of Life and as such **may expose your site to security vulnerabilities**.

**Comment by plegall** [comment]
@J0celyn OK, we will add this warning

**Comment by plegall** [comment]
@J0celyn see https://piwigo.org/guides/install/requirements

> PHP 7.3+. Piwigo can run with PHP 5.3+ but these end-of-life versions
> are no longer maintained and may expose your site to security vulnerabilities.
> See officially PHP supported versions.

**Comment by plegall** [comment]
Let's increase to PHP 7.0 for now.
