### ISSUE TITLE
[BUG] all picture accessible with random photo function with plugin protected album

### ISSUE THREAD

**Issue by killpilot80** [Piwigo/Piwigo#869]
hi,

i find a issue in my piwigo installation, i have a plugin proctected album (V0.5.b), i set a password for control access for some album.

but when in the right menu, in the special section, i click in to random photo, the piwigo see me (when i m not loged,piwigo see me as a guest) some photo in the protected album.

i don't know if you are the right interlocutor

ps : i french, if it is more easy in french no prob... my english is so bad ^^

**Comment by flop25** [comment]
Not a Piwigo issue but the plugin itself
those issues are mentioned multiple time, on the plugin page, on the forum etc
