### ISSUE TITLE
Customize the name of the API handler (the ws.php script)

### ISSUE THREAD

**Issue by vvinogradsky** [Piwigo/Piwigo#874]
The ws.php file is a target for cross-scripting attacks, I can rename it to hide it from attackers (of course I need to update which I use to access it). However, this breaks the admin interface as there are multiple places Piwigo's code where the ws.php name is hard-coded. 

Could you implement an option, which would provide a way for users to rename the script and use a custom name without having to go through a dozen of source files?

**Comment by plegall** [comment]
So are admin.php or identification.php. I'm not convinced the solution is to rename ws.php into ws1234.php.

@modus75 what do you think?

**Comment by modus75** [comment]
I'm not sure this is a solution. The api is used on the public side for rating (maybe some other things). So it would be easy for an attacker to find it.
