### ISSUE TITLE
Feature for removing db entries with an invalid file path

### ISSUE THREAD

**Issue by ironhouzi** [Piwigo/Piwigo#885]
I have a lot (!) of orphaned images with no thumbnail and URLs return 404. About 40,000. When I search the file system for the file name in the URL, nothing comes up. I've done the inverse and found files on the file system that does get thumbnails.

Not sure what happened to the images, but I would at least want to remove the invalid file entries from the database. Does piwigo have this functionality, or do I have to do it manually in mysql?

**Comment by plegall** [comment]
Found this issue while searching for "orphan" (problem of speed to compute them...)

Use plugin Check Uploads to find differences between what Piwigo has in its database and what's in the filesystem.
