### ISSUE TITLE
Piwigo have provide APIs for mobile APP?

### ISSUE THREAD

**Issue by cclover** [Piwigo/Piwigo#905]
Hi

I want to set up a web photo gallery on  my VPS.  Then i can access the photos form my mobile phone via APP not webview.

So piwigo have provide APIs for query gallery and photo?  I can write app to access.

Thanks!

**Comment by plegall** [comment]
Hi @cclover 

That's how the iOS app works see https://github.com/Piwigo/Piwigo-Mobile

Several other remote applications works with Piwigo API : https://piwigo.org/doc/doku.php?id=dev:webapi:start
