### ISSUE TITLE
iOS App No Longer Shows Photo Thumbnails or Album Photos after Force HTTPS Upgrade

### ISSUE THREAD

**Issue by laddo618** [Piwigo/Piwigo#908]
<p>Having difficulty viewing photo album after iOS update to force HTTPS. Cannot view any thumbnails or album title photos - the whole album is visible but the thumbnails are just greyed out broken links.
Have checked whole website and now receive a Secure padlock on all website & piwigo pages when using a web browser. </p>Have also installed Force_HTTPS plugin but receive an error stating 'Your hosting server does not support HTTPS, a SSL certificate is required. Plugin activation is disabled.' even though I have a Secure padlock on the site when I attempt to configure the plugin. The certificate is valid through entire cert chain.<p>
I have spent many evenings trying to resolve the iOS app issue and have reached the end of my knowledge on what to try next. I would be interested to mail some private screenshots or let a moderator look at the site to diagnose the issue if possible.</p> The iOS photo album worked flawlessly before the upgrade to forced https url address.

**Comment by yarez0** [comment]
hi 

got the same issue next year see [https://github.com/Piwigo/Piwigo-Mobile/issues/158](url)

what is your configuration ? if you have iOS issues try to open at [https://github.com/Piwigo/Piwigo-Mobile](url)

**Comment by laddo618** [comment]
This is now resolved by the latest release of the mobile app v2.2.3 
My photos were using :80 in the URL and failing to load due to ssl requirement 
The app now manages this automatically by replacing the base URL of the images.
