### ISSUE TITLE
Very confusing UX design regarind the progress of uploading images

### ISSUE THREAD

**Issue by Hund** [Piwigo/Piwigo#909]
I'm new to Piwigo and imagine my confusion when I tried to upload images and it didn't work. I did some extensive debugging before realising that there wasn't ever any issue, just some very unfortunate UX design.

![2018-08-09-002124_282x378_scrot](https://user-images.githubusercontent.com/320498/43867861-4fd22f22-9b6b-11e8-8d43-ff5e2f69272b.png)

**Comment by plegall** [comment]
Please tell me more : what is wrong in your opinion? We are preparing some
redesign for Piwigo 2.10, your feedback would help :-)
-- 
Pierrick LE GALL

**Comment by Hund** [comment]
It looks like it's something wrong with the images. I didn't think I could upload them and ended up debugging my server for a long time before realising that there's no wrong and I just had to press the upload button.

**Comment by plegall** [comment]
OK, so the problem is the icon at the end of the line. You understood it as an "error" icon, instead of a "cancel" icon. I agree it can be confusing. We will change that.

**Comment by plegall** [comment]
Will be solved with #1019

**Comment by Hund** [comment]
Cool! It looks great! :)
