### ISSUE TITLE
Return album photo sort order with API pwg.categories.getList

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo#917]
The `pwg.categories.getList` method does not return the album photo sort order choosen by the user with the web UI and stored on the server, preventing external apps to adopt it. Could this be implemented as requested [here](https://github.com/Piwigo/Piwigo-Mobile/issues/242) ?

**Comment by Teatek** [comment]
Hello, I don't understand why you would need to get the rank because we can already get the global rank therefore the rank. The global rank contains the rank. It is the last number of the global rank.

For example, if you're global rank is this : 1.2.10
Then the rank is : 10

However the idea of adding a function to set the rank through the API is good. So please open a issue.

**Comment by Teatek** [comment]
Ok, sorry I see the #918 .

**Comment by plegall** [comment]
@EddyLB I would like your feeling about the answer of @Teatek : why do you need the `rank` when you already have the `global_rank`?

@Teatek has pushed a pull-request #955 which adds the `rank`in the output of method `pwg.categories.getList` and `pwg.categories.getAdminList` but I fear that some 3rd part apps are expecting N fields and if they receive N+1 it breaks their execution. If we can avoid this change, I would be "more relaxed" :-)

**Comment by EddyLB** [comment]
@plegall I guess there is some misunderstanding and the pull-request #955 I apologise if 
https://github.com/Piwigo/Piwigo-Mobile/issues/242 is unclear. 

To my knowledge, a Piwigo server provides the order in which albums appear on the web interface with `global_rank` but not the option selected by the user for sorting photos inside each album (option set with the web interface in section Albums / Manage / Photos sort order). That is why I opened this issue.

Similarly, #918 requests the possibility to change that option from a third party app so that users get the same photos sort order when returning to the web interface.

**Comment by plegall** [comment]
Allright, my mistake, I understood wrong :-)

**Comment by plegall** [comment]
@EddyLB is this issue fixed?

**Comment by EddyLB** [comment]
@plegall , I have implemented the code shown in the commits in a test server in version 13.7.0 and this works well. The method returns in addition for example: "image_order":"date_creation ASC, file ASC, id ASC".

PS: Returning additional data is not an issue for routines parsing JSON data.

**Comment by plegall** [comment]
OK, I've adapted the pull-request to recent code changes in `pwg.categories.getAdminList` and `pwg.categories.getList` and merged it.
