### ISSUE TITLE
"rank" becomes a mysql reserved keyword in version 8

### ISSUE THREAD

**Issue by pay62** [Piwigo/Piwigo#919]
Warning:  [mysql error 1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', status
  FROM piwigo_categories
  WHERE id_uppercat IS NULL
  ORDER BY rank AS' at line 1

SELECT id, name, permalink, dir, **rank**, status
  FROM piwigo_categories
  WHERE id_uppercat IS NULL
  ORDER BY rank ASC
; in D:\www_root\piwigo-2.9.4\include\dblayer\functions_mysqli.inc.php on line 845

**piwigo version: 2.9.4**
**mysql version: 8.0.11**

**Comment by samwilson** [comment]
`rank` is a reserved word as of MySQL 8.0.

I've attempted to find all the places using `rank` and added backticks: #922

There's also the album 'Manual sort order' that gets saved as "rank ASC" and then I think appended to an SQL query when it's loaded. I might be wrong about that though.

**Comment by UnConundrum** [comment]
There are also column named "name" and "status" which are reserved words:

SELECT id, name, permalink, dir, rank, status
 FROM piwigo_categories
 WHERE id_uppercat IS NULL
 ORDER BY rank

**Comment by samwilson** [comment]
@UnConundrum are you getting errors with them? With MySQL 8.0 as well?

I guess best practice would be to quote every column name.

**Comment by UnConundrum** [comment]
Yes, I am.

I guess it’s unrelated, but I’m also getting a JSON error.

**Comment by UnConundrum** [comment]
Any chance this will be worked on in the near future?

**Comment by samwilson** [comment]
I'm not sure.

@plegall might know.

**Comment by pstimpel** [comment]
> There are also column named "name" and "status" which are reserved words:
> 

Add 'section' to it.

**Comment by plegall** [comment]
I gave a general reply about the "reserved keywords in MySQL 8" on https://github.com/Piwigo/Piwigo/issues/996#issuecomment-479804890

**Comment by Kwaadpepper** [comment]
https://github.com/Piwigo/Piwigo/issues/1095
