### ISSUE TITLE
Watemark not rescaling for thumbnails

### ISSUE THREAD

**Issue by gattancha** [Piwigo/Piwigo#932]
Recently we've noticed that new pictures uploaded to our gallery have an incorrectly sized watermark on the thumbnails.. This is most noticable for the thumbnails used for the album preview.

![watermark error](https://user-images.githubusercontent.com/19567119/46906796-2e175c80-cf01-11e8-8cb3-e1f28f8936da.PNG)

When you get to the original sized image, the watermark is displayed 

This is happening on at least two galleries at (http://www.mylittlecakeco.co.uk/) and an internal test gallery . Deleting the images and/or gallerties have no effect, 

Both sites are running v2.9.4 and there have been no changes to the sites other than updates
It also does not appear to be a plugin/theme conflict as the internal site has no plugins installed on it.

The watermark in use has not been changed since the site was launched.

**Comment by Teatek** [comment]
Hello, I look a you're gallery and I couldn't find the problem.

Do you still have the problem from you're side ?

**Comment by gattancha** [comment]
Apol;ogies - forogt to update this 
The problem is now resolved after I switched from ImageMagick to GD
