### ISSUE TITLE
upgraded to Latest got  [mysql error 1054] Unknown column 'rank' in 'order clause'

### ISSUE THREAD

**Issue by lynnspain** [Piwigo/Piwigo#948]
Just upgraded to latest version of Piwigo and get this error.  can no longer access admin or even see images on site.

**Comment by pstimpel** [comment]
Wait, you updated piwigo to the latest and got this error now? Or did you update your database, like to mysql8? I have seen the issue of not encapsulated keywords like rank, section, date, time and a few more, and there are other issues open about this, including a few pull requests to solve parts of the misery.

**Comment by pstimpel** [comment]
Wow, that sounds harsh. Hopefully the core devs will fix this soon - even it is a monster job.

**Comment by lynnspain** [comment]
Thank you for your response to this.  If you know about the "Dump database " option when updating the software that would be great.  Then I will know for future. Thank you again.

**Comment by pstimpel** [comment]
I am just an user, as you are. However, I would dump my database before every update. I know, I am paranoid somehow

**Comment by lynnspain** [comment]
Think you are right though and again thank you. In future I will dump the database.

**Comment by plegall** [comment]
fixed in #919 (even if we still find some problems, see #1060)
