### ISSUE TITLE
Users not added in user_infos table

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#958]
If you use plugin AddUsersNotes and you set the "guest" usernote with an single quote, you won't be able to add any new user correctly. Indeed, in function `create_user_infos` we simply copy fields from user "guest" to the new user, without protecting string values.

**Comment by in8sworld** [comment]
I'm not sure this is related but there are 5 users with a different user_list issue where the users are *in* the database but can't be displayed on the admin user_list page:
https://github.com/Piwigo/Piwigo/issues/882
