### ISSUE TITLE
Using piwigo with pictures in existing folder structure

### ISSUE THREAD

**Issue by wiwie** [Piwigo/Piwigo#960]
Currently, piwigo requires that pictures are stored in its own folder structure, right? At least I haven't found a way of handling pictures in an existing folder structure.

Why is this restriction necessary?

This is in fact a rather strong counter argument to me for using piwigo, as I want to keep my files being stored the way they already are, but use them with piwigo anyways.

Would it be a big effort adding this kind of functionality?

Alternatively, it would also be an improvement to me, if pictures could be linked via symlinks instead of being duplicated into piwigos folder structure.

**Comment by john-** [comment]
Pwigo does not require its own folder structure.   There is an option to use an existing one.   I am currently using that approach.   As I recall there may be features not available with this option however for me it works well enough.

**Comment by john-** [comment]
You want Physical albums:

    https://piwigo.org/doc/doku.php?id=user_documentation:albums_management

**Comment by sanddevil** [comment]
Unfortunately there is a dependency with this solution that directories and file names must not contain spaces. I have used spaces extensively in my directories so it looks like a deal breaker for me :(

**Comment by jheinitz** [comment]
Hello,

you can add the following lines to your local config file using the Local Files Editor Plugin and allow spaces to be valid characters in your directory and file names.

// permitted characters for files/directoris during synchronization
$conf['sync_chars_regex'] = '/^[ %()äöüÄÖÜßa-zA-Z0-9-+=_.]+$/';

Kind regards

Jens

**Comment by MarcTheSpark** [comment]
Hi, I've tried putting a folder with a picture in out inside of the galleries folder in my piwigo installation, but when I go to the website, no associated album shows up. Are you not allowed to mix virtual albums with physical albums?

**Comment by flop25** [comment]
The synchronisation will only look inside the ./galleries folder so you need to use symlinks of it's outside of it.
Yes you can have virtual and physic albums. 

Don't hesitate to use our forum for questions. Just explain in detail if you do
