### ISSUE TITLE
strpos() is deprecated in php 7.3

### ISSUE THREAD

**Issue by brunobydesign** [Piwigo/Piwigo#988]
I ran into this message after upgrading to php 7.3 : Deprecated function: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior.

The fix is to change the file jshrink.class.php : 
- line 195
if(strpos('(-+{[@', chr($this->b)) !== false)

- line 254
if(($this->b == '/' && strpos('(,=:[!&|?', chr($this->a)) !== false))

Regards
Bruno

**Comment by plegall** [comment]
Hi @brunobydesign 

Your issue is related to #951 

I see 2 options here:
1) we implement the minimum change on `jshrink.class.php` to work on PHP 7.3 and we can have for Piwigo 2.9.5 (coming very very soon)
2) we completely update `jshrink.class.php` to latest version, as suggested by @tkuther but we wait for Piwigo 2.10
3) both

**Comment by plegall** [comment]
For now, I only fixed the compatibility with PHP 7.3 based on https://github.com/tedious/JShrink/commit/91105810dafedba0390608d7465abd602beb6410

cc @tkuther

**Comment by tkuther** [comment]
@plegall cool, thanks!

**Comment by brunobydesign** [comment]
@plegall sorry I didn't answer to your previous post. This is the only issue Piwigo had with php 7.3 as far as i can tell, since my site is running ok since 3 weeks, so, imho, it is worthwhile using a quick fix and ship, to let people who want it move on to 7.3.
Regads
Bruno

**Comment by plegall** [comment]
To give a little details, please note that I didn't have this error message on PHP 7.3.1. It appeared only when I updated to PHP 7.3.3.

**Comment by tkuther** [comment]
Still broken in 2.10

**Comment by plegall** [comment]
I have tested on PHP 7.3.10 before releasing Piwigo 2.10.0 and no issue at all. This is why I didn't ring any bell in my head! We fix #951 for Piwigo 2.10.1

**Comment by tkuther** [comment]
Hm, it looks like this was just an upgrade issue of my darkroom demo instance
No issues on my other instances.

Sorry for the noise :)

**Comment by plegall** [comment]
Hum... did you upgrade your PHP version? Was it just a PHP bug? is updating jshrink to version 1.3.1 required then (considering it has a higher PHP requirement than current version embedded in Piwigo)

**Comment by Commander1024** [comment]
I still have the issue, *although* I updated jshrink.class.php (again) after 2.10 update. Previously it worked with updated jshrink class.

**Comment by Ajtak** [comment]
I upgraded piwigo to version 2.10 today, and I confirm the same message.

    <b>Deprecated</b>:  strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in <b>/var/www/vhosts/stribrnekule.cz/httpdocs/piwigo/include/jshrink.class.php</b> on line <b>195</b><br />;

**Comment by Ajtak** [comment]
I upgraded piwigo to version 2.10 today, and I confirm the same message.

    <b>Deprecated</b>:  strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in <b>/var/www/vhosts/xxxxxx.cz/httpdocs/piwigo/include/jshrink.class.php</b> on line <b>195</b><br />;

**Comment by tkuther** [comment]
Try the check files integrity plugin, does it report anything?

**Comment by tkuther** [comment]
Hm, seems to be related to GThumb+ here. Plain 2.10 with GThumb+ enabled breaks on category view.
