### ISSUE TITLE
div titrePage hidden !

### ISSUE THREAD

**Issue by philigrane** [Piwigo/Piwigo#991]
Hi, 
the div "titrePage" in "admin.php?page=plugins" has a style set to hidden. In the tab "Other plugins available"
 I do not understand why because in this case we have not access to the search or other options.
I hacked the file "admin/themes/default/template/admin.tpl" at the line 42 like this, `jQuery('h2, .titrePage').show();` I changed the hide function by show and apparently it is displayed without any problem. To see if there's not sides effects.
Regards

**Comment by plegall** [comment]
Hi @philigrane 

You're right, I have been a bit "too strong" in https://github.com/Piwigo/Piwigo/commit/6f1b75d13593bf69fa8e4b1c6258c857321a6564#diff-54b4c9c612de0dbe8bcb8164d1b69328R44

This piece of Javascript code is temporary. In Piwigo 2.10 we are moving the old H2 (after the tabs) to an H1 (before the tab). Changing all *.tpl files is quite a big task and we can't do it for extensions, so I've decided to do it with a few javascript instructions.
