### ISSUE TITLE
css #menubar admin

### ISSUE THREAD

**Issue by philigrane** [Piwigo/Piwigo#992]
In the administration, menus (menubar) have bad alignments. For example, "Configuration" is on the line and the right icons (icon-down-open) are not right-aligned.
I modified my theme.css file (in admin / default / themes /) by adding this line in 798
#menubar dl dt [class*="icon-"]:before { float: left; margin: 0.2em 0.5em 0 6px;}

**Comment by plegall** [comment]
A screenshot would help here, I don't see the alignment issue :-/

**Comment by philigrane** [comment]
I'm on Mac, Chrome (Safari, Firefox). I also tried without the extensions.
![menubar](https://user-images.githubusercontent.com/9150840/54833127-c76f4980-4cbd-11e9-9a33-c68a11c308ae.jpg)
I have modified also those lines:
770, remove the display-inline that have any effet when float
895, un empty ruleset
1029, add border-radius for compatibility
-------
in the console i have this:
```
jquery.min.js?v2.9.4:4 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
Fa @ jquery.min.js?v2.9.4:4
Va @ jquery.min.js?v2.9.4:4
show @ jquery.min.js?v2.9.4:4
m.fn.(anonymous function) @ jquery.min.js?v2.9.4:5
(anonymous) @ admin.php?page=maintenance&action=user_cache&pwg_token=b2e0d556acf36f9230dde953353ed22f:249
j @ jquery.min.js?v2.9.4:2
fireWith @ jquery.min.js?v2.9.4:2
ready @ jquery.min.js?v2.9.4:2
J @ jquery.min.js?v2.9.4:2
jquery.min.js?v2.9.4:2 [Violation] 'DOMContentLoaded' handler took 183ms
[Violation] Forced reflow while executing JavaScript took 102ms
```

**Comment by philigrane** [comment]
I have the same pb after last update.
