### ISSUE TITLE
user list : use datatables.ajax instead of datatables.ajaxsource

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo#999]
As proposed by @dadap in 65ac2721791a040ea0da6833c11022fb2c06533c we would need to switch to `datatables.ajax` instead of `datatables.ajaxSource` but this time with more test on pagination and filtering.

**Comment by J0celyn** [comment]
The body of your message incorrectly refers to `datatabase.ajax` instead of `datatables.ajax`.

**Comment by plegall** [comment]
@J0celyn sure, fixed ;-)
